CREATE TABLE "companies" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"aka" text,
	"lat" double precision NOT NULL,
	"lng" double precision NOT NULL,
	"address" text,
	"neighborhood" text,
	"type" text NOT NULL,
	"one_liner" text NOT NULL,
	"problem" text,
	"solution" text,
	"ai_domains" text[] NOT NULL,
	"industries" text[],
	"tags" text[],
	"founded" integer,
	"headcount" text,
	"funding" jsonb,
	"hiring" boolean,
	"notable" text,
	"status" text,
	"website" text,
	"linkedin" text,
	"sources" text[]
);
