import type { AICompany } from './types';

// ── Metro Vancouver's industry scene ─────────────────────────────────────────
// A career-first starter map spanning Vancouver, Burnaby, Richmond, and the
// North Shore. Pins without a street address are intentionally approximate.

const HIGH_TECH_SOURCE = 'https://investvancouver.ca/industries/high-tech/Pages/default.aspx';
const AI_SOURCE = 'https://investvancouver.ca/industries/artificial-intelligence/Pages/default.aspx';
const GAMING_SOURCE = 'https://investvancouver.ca/industries/digital-media/Pages/default.aspx';
const CLEAN_SOURCE = 'https://investvancouver.ca/industries/cleantech/Pages/default.aspx';

export const COMPANIES: AICompany[] = [
  // ── Tech & AI ──────────────────────────────────────────────────────────────
  {
    id: 'microsoft-vancouver',
    name: 'Microsoft Vancouver',
    industry: 'tech',
    type: 'tech-enterprise',
    lat: 49.2824,
    lng: -123.1187,
    address: '725 Granville Street, Suite 700, Vancouver, BC V7Y 1G5',
    neighborhood: 'Downtown',
    oneLiner: 'A major Microsoft development campus with teams across engineering, design, program management, data science and AI.',
    problem: 'Global software products need multidisciplinary engineering teams close to a deep and diverse talent market.',
    solution: 'Vancouver product teams build and operate Microsoft experiences spanning cloud, gaming, AI and business applications.',
    aiDomains: ['cloud-infra', 'ai-ml', 'devtools'],
    industries: ['software', 'cloud computing', 'artificial intelligence'],
    fundingStage: 'Public company',
    hiring: true,
    careersUrl: 'https://careers.microsoft.com/v2/global/en/locations/vancouver.html',
    website: 'https://www.microsoft.com/en-ca/about/locations',
    sources: ['https://www.microsoft.com/en-ca/about/locations', 'https://careers.microsoft.com/v2/global/en/locations/vancouver.html'],
    verifiedAt: '2026-08',
  },
  {
    id: 'amazon-vancouver',
    name: 'Amazon Vancouver',
    industry: 'tech',
    type: 'tech-enterprise',
    lat: 49.2797,
    lng: -123.1146,
    neighborhood: 'Downtown',
    oneLiner: 'One of Metro Vancouver’s largest technology employers, with corporate and engineering teams serving Amazon and AWS products.',
    problem: 'Global commerce and cloud platforms require large engineering, product and operations teams.',
    solution: 'Vancouver teams contribute to Amazon’s consumer, advertising, operations and cloud technology businesses.',
    aiDomains: ['cloud-infra', 'ecommerce', 'ai-ml'],
    industries: ['cloud computing', 'e-commerce', 'technology'],
    fundingStage: 'Public company',
    hiring: true,
    careersUrl: 'https://www.amazon.jobs/en/location/vancouvervictoria-canada',
    website: 'https://www.amazon.ca/',
    sources: [HIGH_TECH_SOURCE, 'https://www.amazon.jobs/en/location/vancouvervictoria-canada'],
    verifiedAt: '2026-08',
  },
  {
    id: 'sap-labs-vancouver',
    name: 'SAP Labs Vancouver',
    industry: 'tech',
    type: 'tech-enterprise',
    lat: 49.2757,
    lng: -123.1184,
    address: '910 Mainland Street, Vancouver, BC V6B 1A9',
    neighborhood: 'Yaletown',
    oneLiner: 'A global SAP research-and-development hub specializing in analytics, database technologies and customer experiences.',
    problem: 'Enterprises need trusted data, analytics and application platforms that operate at global scale.',
    solution: 'The Vancouver lab develops and improves SAP enterprise products as part of the global SAP Labs network.',
    aiDomains: ['saas', 'data-analytics', 'ai-ml'],
    industries: ['enterprise software', 'business intelligence'],
    founded: 1984,
    fundingStage: 'Public company',
    hiring: true,
    careersUrl: 'https://jobs.sap.com/',
    website: 'https://www.sap.com/canada/about/company/innovation/labs.html',
    sources: ['https://www.sap.com/canada/about/company/office-locations/canada.html', 'https://www.sap.com/canada/about/company/innovation/labs.html'],
    verifiedAt: '2026-08',
  },
  {
    id: 'hootsuite-vancouver',
    name: 'Hootsuite',
    industry: 'tech',
    type: 'tech-scaleup',
    lat: 49.2661,
    lng: -123.1018,
    address: '111 East 5th Avenue, Vancouver, BC',
    neighborhood: 'Mount Pleasant',
    oneLiner: 'Vancouver-founded social media performance platform combining publishing, listening, analytics and AI-powered insights.',
    problem: 'Organizations struggle to coordinate and measure customer engagement across fragmented social networks.',
    solution: 'A unified enterprise platform for social publishing, listening, customer care, advocacy and performance measurement.',
    aiDomains: ['saas', 'martech', 'ai-ml', 'data-analytics'],
    industries: ['social media', 'marketing technology'],
    founded: 2008,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://careers.hootsuite.com/',
    website: 'https://www.hootsuite.com/',
    sources: ['https://careers.hootsuite.com/', 'https://blog.hootsuite.com/hidden-costs-downsizing-office-space/'],
    verifiedAt: '2026-08',
  },
  {
    id: 'clio-vancouver',
    name: 'Clio',
    aka: 'Themis Solutions',
    industry: 'tech',
    type: 'tech-scaleup',
    lat: 49.2477,
    lng: -122.9992,
    address: '4611 Canada Way, Burnaby, BC V5G 4X3',
    neighborhood: 'Burnaby',
    oneLiner: 'Cloud legal-technology company building practice management, payments and client-intake software for law firms.',
    problem: 'Law firms lose time and revenue to disconnected case, billing, document and client systems.',
    solution: 'An integrated cloud platform that runs a legal practice from intake and case management through billing and payments.',
    aiDomains: ['saas', 'ai-ml', 'fintech'],
    industries: ['legal technology', 'payments'],
    founded: 2008,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://www.clio.com/ca/about/careers/greater-vancouver/',
    website: 'https://www.clio.com/',
    sources: ['https://www.clio.com/ca/about/careers/greater-vancouver/', 'https://www.clio.com/ca/wp-content/uploads/sites/6/2025/12/Canada-Clio-BC-Pay-Transparency-Report-2025.pdf'],
    verifiedAt: '2026-08',
  },
  {
    id: 'visier-vancouver',
    name: 'Visier',
    industry: 'tech',
    type: 'tech-scaleup',
    lat: 49.2766,
    lng: -123.1154,
    address: '400-858 Beatty Street, Vancouver, BC V6B 1C1',
    neighborhood: 'Yaletown',
    oneLiner: 'Vancouver-headquartered people analytics and workforce-planning platform for enterprise HR and business leaders.',
    problem: 'Organizations have workforce data but lack timely answers about hiring, retention, productivity and skills.',
    solution: 'A people-analytics platform that turns HR and business data into decision-ready workforce insights.',
    aiDomains: ['data-analytics', 'ai-ml', 'saas'],
    industries: ['HR technology', 'analytics'],
    founded: 2010,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://www.visier.com/careers/',
    website: 'https://www.visier.com/',
    sources: ['https://www.visier.com/company/', 'https://www.visier.com/contact-us/'],
    verifiedAt: '2026-08',
  },
  {
    id: 'trulioo-vancouver',
    name: 'Trulioo',
    industry: 'tech',
    type: 'tech-scaleup',
    lat: 49.2669,
    lng: -123.1032,
    address: '400-114 East 4th Avenue, Vancouver, BC V5T 1G2',
    neighborhood: 'Mount Pleasant',
    oneLiner: 'Global identity-verification platform helping businesses verify people and organizations across international markets.',
    problem: 'Digital businesses must establish trust while navigating fraud, fragmented data and country-specific compliance.',
    solution: 'Configurable identity and business verification workflows delivered through a global data and API platform.',
    aiDomains: ['fintech', 'cybersecurity', 'data-analytics'],
    industries: ['identity verification', 'compliance', 'fintech'],
    founded: 2011,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://www.trulioo.com/company/careers',
    website: 'https://www.trulioo.com/',
    sources: ['https://www.trulioo.com/company/contact-us'],
    verifiedAt: '2026-08',
  },
  {
    id: 'geocomply-vancouver',
    name: 'GeoComply',
    industry: 'tech',
    type: 'tech-scaleup',
    lat: 49.2803,
    lng: -123.1173,
    address: '545 Robson Street, 2nd Floor, Vancouver, BC V6B 1A6',
    neighborhood: 'Downtown',
    oneLiner: 'Fraud-prevention and geolocation compliance company protecting regulated digital transactions worldwide.',
    problem: 'Regulated online businesses need to verify that users are real and located where they claim to be.',
    solution: 'Device intelligence, identity and geolocation tools that detect location fraud and strengthen digital trust.',
    aiDomains: ['cybersecurity', 'fintech', 'gis-geospatial'],
    industries: ['fraud prevention', 'gaming compliance', 'fintech'],
    founded: 2011,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://www.geocomply.com/careers/vancouver-canada/',
    website: 'https://www.geocomply.com/',
    sources: ['https://www.geocomply.com/careers/vancouver-canada/'],
    verifiedAt: '2026-08',
  },
  {
    id: 'global-relay-vancouver',
    name: 'Global Relay',
    industry: 'tech',
    type: 'tech-enterprise',
    lat: 49.2836,
    lng: -123.1085,
    address: '220 Cambie Street, 2nd Floor, Vancouver, BC V6B 2M9',
    neighborhood: 'Gastown',
    oneLiner: 'Vancouver-headquartered communications compliance and archiving platform for regulated organizations.',
    problem: 'Financial and regulated firms must securely capture, retain and supervise rapidly changing business communications.',
    solution: 'Cloud archiving, supervision, e-discovery and messaging products built for regulatory compliance.',
    aiDomains: ['cloud-infra', 'cybersecurity', 'saas'],
    industries: ['financial technology', 'compliance', 'enterprise software'],
    founded: 1999,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://www.globalrelay.com/company/careers/',
    website: 'https://www.globalrelay.com/',
    sources: ['https://www.globalrelay.com/company/contact/', 'https://www.globalrelay.com/company/careers/locations/'],
    verifiedAt: '2026-08',
  },
  {
    id: 'sanctuary-ai-vancouver',
    name: 'Sanctuary AI',
    industry: 'tech',
    type: 'tech-startup',
    lat: 49.2668,
    lng: -123.0950,
    neighborhood: 'Mount Pleasant',
    oneLiner: 'Physical-AI company developing general-purpose humanoid robots, dexterous hands and intelligence for real-world work.',
    problem: 'Many essential industrial tasks remain difficult to automate because they require human-like dexterity and reasoning.',
    solution: 'Integrated AI, controls, simulation, sensing and robotic hardware trained through real-world deployments.',
    aiDomains: ['robotics', 'ai-ml', 'computer-vision'],
    industries: ['robotics', 'artificial intelligence'],
    founded: 2018,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://sanctuary.ai/careers/',
    website: 'https://sanctuary.ai/',
    sources: ['https://sanctuary.ai/careers/', AI_SOURCE],
    verifiedAt: '2026-08',
  },
  {
    id: 'ak-robotics-vancouver',
    name: 'A&K Robotics',
    industry: 'tech',
    type: 'tech-startup',
    lat: 49.2832,
    lng: -123.0865,
    neighborhood: 'Railtown',
    oneLiner: 'Autonomous mobility company transforming existing equipment into intelligent robots for airports and public spaces.',
    problem: 'Airports and large public facilities need safer, more accessible mobility without rebuilding their infrastructure.',
    solution: 'Autonomous robotic platforms combining navigation, perception and fleet software for complex public environments.',
    aiDomains: ['robotics', 'ai-ml', 'computer-vision'],
    industries: ['robotics', 'mobility'],
    founded: 2015,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://www.aandkrobotics.com/careers',
    website: 'https://www.aandkrobotics.com/',
    sources: ['https://www.aandkrobotics.com/careers', AI_SOURCE],
    verifiedAt: '2026-08',
  },
  {
    id: 'fortinet-burnaby',
    name: 'Fortinet (Burnaby)',
    industry: 'tech',
    type: 'tech-enterprise',
    lat: 49.2608,
    lng: -123.0010,
    neighborhood: 'Burnaby',
    oneLiner: 'Major Metro Vancouver engineering presence for a global public cybersecurity company spanning networks, cloud and operations.',
    problem: 'Organizations need coordinated protection across users, applications, networks, devices and cloud infrastructure.',
    solution: 'An integrated portfolio of firewalls, secure networking, endpoint, cloud and security-operations products.',
    aiDomains: ['cybersecurity', 'cloud-infra', 'ai-ml'],
    industries: ['cybersecurity', 'networking'],
    fundingStage: 'Public company',
    hiring: true,
    careersUrl: 'https://www.fortinet.com/corporate/careers',
    website: 'https://www.fortinet.com/',
    sources: [HIGH_TECH_SOURCE, 'https://www.fortinet.com/corporate/careers'],
    verifiedAt: '2026-08',
  },
  {
    id: 'dapper-labs-vancouver',
    name: 'Dapper Labs',
    industry: 'tech',
    type: 'tech-startup',
    lat: 49.2675,
    lng: -123.0990,
    neighborhood: 'Mount Pleasant',
    oneLiner: 'Vancouver-founded consumer blockchain company behind Flow and digital-collectible experiences including NBA Top Shot.',
    problem: 'Consumer digital ownership products have historically been difficult to use and expensive to scale.',
    solution: 'The Flow blockchain and branded applications designed to make digital assets accessible to mainstream audiences.',
    aiDomains: ['gaming-tech', 'cloud-infra'],
    industries: ['blockchain', 'consumer technology', 'gaming'],
    founded: 2018,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://www.dapperlabs.com/careers',
    website: 'https://www.dapperlabs.com/',
    sources: ['https://www.dapperlabs.com/', HIGH_TECH_SOURCE],
    verifiedAt: '2026-08',
  },

  // ── Gaming / VFX ──────────────────────────────────────────────────────────
  {
    id: 'electronic-arts-vancouver',
    name: 'Electronic Arts Vancouver',
    aka: 'EA Vancouver',
    industry: 'gaming',
    type: 'gaming-aaa',
    lat: 49.2474,
    lng: -122.9952,
    address: '4330 Sanderson Way, Burnaby, BC V5G 4X1',
    neighborhood: 'Burnaby',
    oneLiner: 'EA’s large Burnaby campus developing major franchises including EA Sports FC, NHL, UFC and Plants vs. Zombies.',
    problem: 'Global game franchises require large multidisciplinary studios and specialized production technology.',
    solution: 'AAA game development, motion capture, live operations and corporate support teams on one Metro Vancouver campus.',
    aiDomains: ['aaa-games', 'live-service', 'animation'],
    industries: ['video games', 'interactive entertainment'],
    fundingStage: 'Public company',
    hiring: true,
    careersUrl: 'https://www.ea.com/en-ca/ea-studios/ea-sports/job-opportunities',
    website: 'https://www.ea.com/en-ca/ea-studios/ea-sports/job-opportunities',
    sources: ['https://www.ea.com/en-ca/ea-studios/ea-sports/job-opportunities', 'https://www.ea.com/en-ca/playtesting/our-locations/burnaby'],
    verifiedAt: '2026-08',
  },
  {
    id: 'the-coalition-vancouver',
    name: 'The Coalition',
    industry: 'gaming',
    type: 'gaming-aaa',
    lat: 49.2824,
    lng: -123.1187,
    address: '725 Granville Street, Vancouver, BC V7Y 1G5',
    neighborhood: 'Downtown',
    oneLiner: 'Microsoft-owned Xbox game studio and steward of the Gears franchise, based in downtown Vancouver.',
    problem: 'Long-running AAA franchises need dedicated creative and technology teams to evolve across console generations.',
    solution: 'A Vancouver studio building Gears games and advancing large-scale Unreal Engine production.',
    aiDomains: ['aaa-games', 'open-world', 'animation'],
    industries: ['video games', 'interactive entertainment'],
    fundingStage: 'Subsidiary of Microsoft',
    hiring: true,
    careersUrl: 'https://www.thecoalitionstudio.com/careers',
    website: 'https://www.thecoalitionstudio.com/',
    sources: ['https://www.thecoalitionstudio.com/', 'https://www.microsoft.com/en-ca/about/locations'],
    verifiedAt: '2026-08',
  },
  {
    id: 'sony-imageworks-vancouver',
    name: 'Sony Pictures Imageworks',
    industry: 'gaming',
    type: 'gaming-vfx',
    lat: 49.2795,
    lng: -123.1164,
    address: '658 Homer Street, Vancouver, BC V6B 2R4',
    neighborhood: 'Downtown',
    oneLiner: 'Academy Award-winning visual-effects and animation studio with its main production operation in Vancouver.',
    problem: 'Feature films and animated productions demand highly scalable artistry, rendering and production technology.',
    solution: 'End-to-end character animation and visual effects for major studio films and streaming productions.',
    aiDomains: ['vfx-film', 'animation', 'vfx-tv'],
    industries: ['visual effects', 'animation', 'film'],
    fundingStage: 'Subsidiary of Sony',
    hiring: true,
    careersUrl: 'https://www.imageworks.com/index.php/job-postings',
    website: 'https://www.imageworks.com/',
    sources: ['https://www.imageworks.com/contact-us', 'https://www.imageworks.com/index.php/job-postings', GAMING_SOURCE],
    verifiedAt: '2026-08',
  },
  {
    id: 'dneg-vancouver',
    name: 'DNEG Vancouver',
    industry: 'gaming',
    type: 'gaming-vfx',
    lat: 49.2836,
    lng: -123.1089,
    neighborhood: 'Gastown',
    oneLiner: 'Vancouver studio of the global visual-effects and animation company behind award-winning film and television work.',
    problem: 'Large productions need global teams capable of delivering complex visual effects at feature-film scale.',
    solution: 'Visual effects, animation and virtual-production services connected to DNEG’s worldwide studio network.',
    aiDomains: ['vfx-film', 'vfx-tv', 'animation'],
    industries: ['visual effects', 'animation', 'film'],
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://www.dneg.com/careers/',
    website: 'https://www.dneg.com/',
    sources: ['https://www.dneg.com/', GAMING_SOURCE],
    verifiedAt: '2026-08',
  },
  {
    id: 'disney-animation-vancouver',
    name: 'Walt Disney Animation Studios Vancouver',
    industry: 'gaming',
    type: 'gaming-vfx',
    lat: 49.2863,
    lng: -123.1190,
    neighborhood: 'Downtown',
    oneLiner: 'Walt Disney Animation’s Vancouver production studio, the organization’s major feature-animation site outside Burbank.',
    problem: 'Feature animation requires deep artistic and technical capacity across long, complex production schedules.',
    solution: 'Vancouver-based artists and technologists contribute to Disney animated features and long-form projects.',
    aiDomains: ['animation', 'vfx-film'],
    industries: ['animation', 'film'],
    fundingStage: 'Subsidiary of Disney',
    hiring: true,
    careersUrl: 'https://www.disneyanimation.com/careers/',
    website: 'https://www.disneyanimation.com/',
    sources: ['https://www.disneyanimation.com/', GAMING_SOURCE],
    verifiedAt: '2026-08',
  },

  // ── CleanTech ─────────────────────────────────────────────────────────────
  {
    id: 'ballard-power-systems',
    name: 'Ballard Power Systems',
    industry: 'cleantech',
    type: 'cleantech-utility',
    lat: 49.1998,
    lng: -123.0089,
    address: '9000 Glenlyon Parkway, Burnaby, BC V5J 5J8',
    neighborhood: 'Burnaby',
    oneLiner: 'Burnaby-headquartered public company developing and manufacturing hydrogen fuel-cell power systems.',
    problem: 'Heavy transportation and stationary power need zero-emission alternatives where batteries alone are difficult to use.',
    solution: 'PEM fuel-cell stacks and modules for buses, trucks, trains, ships and stationary power applications.',
    aiDomains: ['hydrogen', 'renewable-energy', 'green-shipping'],
    industries: ['hydrogen', 'transportation', 'energy'],
    founded: 1979,
    fundingStage: 'Public company',
    hiring: true,
    careersUrl: 'https://www.ballard.com/careers/',
    website: 'https://www.ballard.com/',
    sources: ['https://www.ballard.com/our-company/', 'https://www.ballard.com/careers/'],
    verifiedAt: '2026-08',
  },
  {
    id: 'svante-burnaby',
    name: 'Svante',
    industry: 'cleantech',
    type: 'cleantech-startup',
    lat: 49.1989,
    lng: -123.0080,
    address: '8800 Glenlyon Parkway, Burnaby, BC',
    neighborhood: 'Burnaby',
    oneLiner: 'Industrial carbon-capture company manufacturing structured filters designed to trap CO₂ from hard-to-abate emissions.',
    problem: 'Cement, steel, energy and other industries need practical ways to capture carbon from concentrated exhaust streams.',
    solution: 'Solid-sorbent filters and rotary adsorption equipment designed for scalable post-combustion carbon capture.',
    aiDomains: ['carbon-capture', 'industrial-decarbonization'],
    industries: ['carbon capture', 'industrial technology'],
    founded: 2007,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://svanteinc.com/careers/',
    website: 'https://svanteinc.com/',
    sources: ['https://svanteinc.com/', CLEAN_SOURCE],
    verifiedAt: '2026-08',
  },
  {
    id: 'general-fusion-richmond',
    name: 'General Fusion',
    industry: 'cleantech',
    type: 'cleantech-research',
    lat: 49.1956,
    lng: -123.1688,
    address: '6020 Russ Baker Way, Richmond, BC V7B 1B4',
    neighborhood: 'Richmond',
    oneLiner: 'Richmond-based fusion-energy company developing magnetized target fusion technology for commercial power.',
    problem: 'The world needs firm, abundant zero-carbon energy that is not constrained by weather or geography.',
    solution: 'A pulsed fusion system that compresses magnetized plasma using mechanically driven liquid-metal walls.',
    aiDomains: ['fusion-energy', 'renewable-energy'],
    industries: ['fusion energy', 'advanced engineering'],
    founded: 2002,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://generalfusion.com/careers/',
    website: 'https://generalfusion.com/',
    sources: ['https://generalfusion.com/contact/', CLEAN_SOURCE],
    verifiedAt: '2026-08',
  },
  {
    id: 'nano-one-burnaby',
    name: 'Nano One Materials',
    industry: 'cleantech',
    type: 'cleantech-startup',
    lat: 49.2042,
    lng: -122.9762,
    address: '101B-8575 Government Street, Burnaby, BC V3N 4V1',
    neighborhood: 'Burnaby',
    oneLiner: 'Battery-materials technology company developing lower-cost, lower-impact production of lithium-ion cathode materials.',
    problem: 'Cathode manufacturing is energy intensive, complex and exposed to constrained global supply chains.',
    solution: 'A patented One-Pot process for producing cathode active materials with fewer steps and flexible raw-material inputs.',
    aiDomains: ['battery-materials', 'industrial-decarbonization'],
    industries: ['battery materials', 'advanced manufacturing'],
    founded: 2011,
    fundingStage: 'Public company',
    hiring: true,
    careersUrl: 'https://nanoone.ca/careers/',
    website: 'https://nanoone.ca/',
    sources: ['https://nanoone.ca/careers/', CLEAN_SOURCE],
    verifiedAt: '2026-08',
  },
  {
    id: 'ionomr-innovations',
    name: 'Ionomr Innovations',
    industry: 'cleantech',
    type: 'cleantech-startup',
    lat: 49.2606,
    lng: -123.2471,
    neighborhood: 'UBC',
    oneLiner: 'Advanced-materials company developing ion-exchange membranes and polymers for hydrogen and carbon-capture systems.',
    problem: 'Electrolysers, fuel cells and carbon-capture equipment depend on durable, efficient membrane materials.',
    solution: 'Hydrocarbon ion-exchange polymers engineered for demanding clean-energy electrochemical applications.',
    aiDomains: ['hydrogen', 'carbon-capture', 'industrial-decarbonization'],
    industries: ['advanced materials', 'hydrogen', 'carbon capture'],
    founded: 2018,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://ionomr.com/careers/',
    website: 'https://ionomr.com/',
    sources: ['https://ionomr.com/', CLEAN_SOURCE],
    verifiedAt: '2026-08',
  },
  {
    id: 'minesense-vancouver',
    name: 'MineSense Technologies',
    industry: 'cleantech',
    type: 'cleantech-startup',
    lat: 49.2680,
    lng: -123.0900,
    neighborhood: 'False Creek Flats',
    oneLiner: 'Mining-technology company using sensors and data to separate waste from ore earlier in the extraction process.',
    problem: 'Mines waste energy, water and processing capacity moving material that contains little valuable ore.',
    solution: 'Shovel- and belt-mounted sensing systems that measure ore grade in real time and improve material routing.',
    aiDomains: ['mining-tech', 'data-analytics', 'industrial-decarbonization'],
    industries: ['mining technology', 'industrial analytics'],
    founded: 2008,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://minesense.com/careers/',
    website: 'https://minesense.com/',
    sources: ['https://minesense.com/', CLEAN_SOURCE],
    verifiedAt: '2026-08',
  },

  // ── Life Sciences ─────────────────────────────────────────────────────────
  {
    id: 'abcellera-vancouver',
    name: 'AbCellera',
    industry: 'lifesci',
    type: 'lifesci-biotech',
    lat: 49.2670,
    lng: -123.1087,
    address: '150 West 4th Avenue, Vancouver, BC V5Y 1G6',
    neighborhood: 'Mount Pleasant',
    oneLiner: 'Vancouver biotechnology company discovering and developing antibody medicines from target through clinical manufacturing.',
    problem: 'Finding antibodies against difficult disease targets is slow and requires many disconnected scientific capabilities.',
    solution: 'An integrated platform combining biology, protein engineering, data science, development and manufacturing.',
    aiDomains: ['drug-discovery', 'biotech-rd', 'immunotherapy', 'ai-ml'],
    industries: ['biotechnology', 'therapeutics'],
    founded: 2012,
    fundingStage: 'Public company',
    hiring: true,
    careersUrl: 'https://www.abcellera.com/careers',
    website: 'https://www.abcellera.com/',
    sources: ['https://www.abcellera.com/contact-us', 'https://www.abcellera.com/careers'],
    verifiedAt: '2026-08',
  },
  {
    id: 'stemcell-technologies-vancouver',
    name: 'STEMCELL Technologies',
    industry: 'lifesci',
    type: 'lifesci-biotech',
    lat: 49.2728,
    lng: -123.0892,
    address: '1618 Station Street, Vancouver, BC V6A 1B6',
    neighborhood: 'False Creek Flats',
    oneLiner: 'Vancouver-headquartered life-science company supplying cell-culture, cell-separation and research tools worldwide.',
    problem: 'Researchers need consistent, specialized tools to isolate, grow and study cells across complex disease areas.',
    solution: 'Research reagents, media, instruments and services for stem-cell, immunology, cancer and regenerative-medicine workflows.',
    aiDomains: ['biotech-rd', 'cell-gene-therapy', 'diagnostics'],
    industries: ['life-science tools', 'biotechnology'],
    founded: 1993,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://www.stemcell.com/careers/',
    website: 'https://www.stemcell.com/',
    sources: ['https://www.stemcell.com/locations/north-america/vancouver-bc', 'https://www.stemcell.com/careers/'],
    verifiedAt: '2026-08',
  },
  {
    id: 'acuitas-therapeutics',
    name: 'Acuitas Therapeutics',
    industry: 'lifesci',
    type: 'lifesci-biotech',
    lat: 49.2612,
    lng: -123.2466,
    address: '6190 Agronomy Road, Suite 205, Vancouver, BC V6T 1Z3',
    neighborhood: 'UBC',
    oneLiner: 'Private Vancouver biotech developing lipid-nanoparticle delivery systems for nucleic-acid therapeutics.',
    problem: 'RNA and other nucleic-acid medicines need safe, effective delivery into the right cells.',
    solution: 'Proprietary lipid-nanoparticle formulations and development expertise used by pharmaceutical and research partners.',
    aiDomains: ['drug-discovery', 'biotech-rd', 'precision-medicine'],
    industries: ['drug delivery', 'biotechnology'],
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://acuitastx.com/careers/',
    website: 'https://acuitastx.com/',
    sources: ['https://acuitastx.com/contact/', 'https://acuitastx.com/careers/'],
    verifiedAt: '2026-08',
  },
  {
    id: 'aspect-biosystems-vancouver',
    name: 'Aspect Biosystems',
    industry: 'lifesci',
    type: 'lifesci-biotech',
    lat: 49.2085,
    lng: -123.1418,
    neighborhood: 'Marpole',
    oneLiner: 'Vancouver biotech combining microfluidics and 3D bioprinting to develop implantable tissue therapeutics.',
    problem: 'Conventional drug development and transplantation cannot adequately replace complex biological tissue function.',
    solution: 'Bioprinted cell therapies built from living cells, biomaterials and programmable microfluidic manufacturing.',
    aiDomains: ['cell-gene-therapy', 'biotech-rd', 'precision-medicine'],
    industries: ['bioprinting', 'cell therapy'],
    founded: 2013,
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://aspectbiosystems.com/careers',
    website: 'https://aspectbiosystems.com/',
    sources: ['https://aspectbiosystems.com/', 'https://aspectbiosystems.com/careers'],
    verifiedAt: '2026-08',
  },
  {
    id: 'xenon-pharmaceuticals-burnaby',
    name: 'Xenon Pharmaceuticals',
    industry: 'lifesci',
    type: 'lifesci-pharma',
    lat: 49.2503,
    lng: -122.9978,
    neighborhood: 'Burnaby',
    oneLiner: 'Clinical-stage neuroscience company developing ion-channel therapeutics for epilepsy and other neurological disorders.',
    problem: 'Many neurological conditions remain poorly controlled by existing medicines and impose severe quality-of-life costs.',
    solution: 'Precision medicines designed around validated ion-channel biology, advanced through clinical development.',
    aiDomains: ['drug-discovery', 'clinical-trials', 'precision-medicine'],
    industries: ['biopharmaceuticals', 'neuroscience'],
    founded: 1996,
    fundingStage: 'Public company',
    hiring: true,
    careersUrl: 'https://www.xenon-pharma.com/careers/',
    website: 'https://www.xenon-pharma.com/',
    sources: ['https://www.xenon-pharma.com/', 'https://www.xenon-pharma.com/careers/'],
    verifiedAt: '2026-08',
  },

  // ── Marine ────────────────────────────────────────────────────────────────
  {
    id: 'seaspan-vancouver-shipyards',
    name: 'Seaspan Vancouver Shipyards',
    industry: 'marine',
    type: 'marine-services',
    lat: 49.3120,
    lng: -123.1031,
    address: '50 Pemberton Avenue, North Vancouver, BC',
    neighborhood: 'North Vancouver',
    oneLiner: 'Canada’s West Coast strategic shipbuilding partner constructing and supporting vessels for the Navy and Coast Guard.',
    problem: 'Canada needs sovereign capacity to design, build, repair and maintain complex government and commercial vessels.',
    solution: 'Long-horizon shipbuilding, engineering and refit programs delivered from North Vancouver under the National Shipbuilding Strategy.',
    aiDomains: ['ship-services', 'green-shipping', 'marine-logistics'],
    industries: ['shipbuilding', 'defense', 'marine engineering'],
    fundingStage: 'Private',
    hiring: true,
    careersUrl: 'https://www.seaspan.com/why-seaspan/',
    website: 'https://www.seaspan.com/',
    sources: ['https://www.seaspan.com/why-seaspan/', 'https://www.seaspan.com/the-future-is-yours-to-build/'],
    verifiedAt: '2026-08',
  },
  {
    id: 'port-of-vancouver',
    name: 'Vancouver Fraser Port Authority',
    aka: 'Port of Vancouver',
    industry: 'marine',
    type: 'marine-port',
    lat: 49.2882,
    lng: -123.1112,
    address: '100-999 Canada Place, Vancouver, BC V6C 3T4',
    neighborhood: 'Downtown',
    oneLiner: 'Federal port authority overseeing Canada’s largest port and its trade, environmental and infrastructure mandate.',
    problem: 'A complex gateway must move national trade efficiently while managing land, navigation, communities and environmental impacts.',
    solution: 'Port planning, infrastructure, permitting, marine operations and stewardship across the Vancouver gateway.',
    aiDomains: ['port-operations', 'marine-logistics', 'green-shipping'],
    industries: ['ports', 'logistics', 'trade'],
    fundingStage: 'Federal port authority',
    website: 'https://www.portvancouver.com/',
    sources: ['https://www.portvancouver.com/', 'https://www.portvancouver.com/sites/default/files/2024-08/2018_FinancialReport.pdf'],
    verifiedAt: '2026-08',
  },
];
