import type { AICompany } from './types';

// ── Metro Vancouver ecosystem expansion ────────────────────────────────────
// This second pass closes the largest gaps in the original career-first
// starter set. Company selection is anchored in current Invest Vancouver,
// BC Tech, DigiBC, Life Sciences BC, and BCMEA ecosystem sources. Locations
// without a sourced street address are deliberately neighbourhood-level pins.

const TECH_SOURCE = 'https://investvancouver.ca/industries/artificial-intelligence/Pages/default.aspx';
const GAMING_SOURCE = 'https://investvancouver.ca/industries/digital-media/Pages/default.aspx';
const CLEAN_SOURCE = 'https://investvancouver.ca/industries/cleantech/Pages/default.aspx';
const LIFE_SOURCE = 'https://investvancouver.ca/industries/life-sciences/Pages/default.aspx';
const MARINE_SOURCE = 'https://www.bcmea.com/who-we-are/our-members/';
const AERO_SOURCE = 'https://investvancouver.ca/resources/events/web-summit-vancouver/Pages/default.aspx';

type EcosystemCompany = Omit<AICompany, 'verifiedAt'>;

const companies: EcosystemCompany[] = [
  // ── Tech & AI: global anchors, local scaleups, and applied-AI firms ───────
  {
    id: 'google-vancouver', name: 'Google Vancouver', upsideKey: 'google-deepmind-montreal',
    industry: 'tech', type: 'tech-enterprise', lat: 49.2818, lng: -123.1165, neighborhood: 'Downtown',
    oneLiner: 'Google engineering and business teams working from the company’s Vancouver office.',
    aiDomains: ['ai-ml', 'cloud-infra', 'data-analytics'], industries: ['technology', 'cloud', 'artificial intelligence'],
    fundingStage: 'Public company', hiring: true,
    careersUrl: 'https://www.google.com/about/careers/applications/jobs/results/', website: 'https://about.google/locations/',
    sources: [TECH_SOURCE, 'https://about.google/locations/'],
  },
  {
    id: 'apple-vancouver', name: 'Apple Vancouver', upsideKey: 'apple',
    industry: 'tech', type: 'tech-enterprise', lat: 49.2840, lng: -123.1143, neighborhood: 'Downtown',
    oneLiner: 'Apple teams in Vancouver spanning software, services, operations, and product engineering.',
    aiDomains: ['ai-ml', 'cloud-infra', 'devtools'], industries: ['consumer technology', 'software'],
    fundingStage: 'Public company', hiring: true,
    careersUrl: 'https://jobs.apple.com/en-ca/search', website: 'https://www.apple.com/ca/', sources: ['https://jobs.apple.com/en-ca/search'],
  },
  {
    id: 'ibm-vancouver', name: 'IBM Vancouver', upsideKey: 'ibm',
    industry: 'tech', type: 'tech-enterprise', lat: 49.2488, lng: -122.9805, neighborhood: 'Burnaby',
    oneLiner: 'IBM technology and consulting teams serving Western Canadian clients from Metro Vancouver.',
    aiDomains: ['ai-ml', 'cloud-infra', 'cybersecurity'], industries: ['enterprise software', 'consulting'],
    fundingStage: 'Public company', hiring: true,
    careersUrl: 'https://www.ibm.com/careers/search', website: 'https://www.ibm.com/ca-en', sources: [AERO_SOURCE, 'https://www.ibm.com/careers/search'],
  },
  {
    id: 'mastercard-vancouver', name: 'Mastercard Vancouver', upsideKey: 'mastercard',
    industry: 'tech', type: 'tech-enterprise', lat: 49.2828, lng: -123.1171, neighborhood: 'Downtown',
    oneLiner: 'Mastercard’s global Intelligence and Cyber Centre advances security, AI, and digital-payment technology.',
    aiDomains: ['cybersecurity', 'ai-ml', 'fintech'], industries: ['payments', 'cybersecurity'],
    fundingStage: 'Public company', hiring: true,
    careersUrl: 'https://careers.mastercard.com/us/en', website: 'https://www.mastercard.ca/', sources: [TECH_SOURCE, 'https://careers.mastercard.com/us/en'],
  },
  {
    id: 'workday-vancouver', name: 'Workday Vancouver', upsideKey: 'workday',
    industry: 'tech', type: 'tech-enterprise', lat: 49.2766, lng: -123.1154, neighborhood: 'Yaletown',
    oneLiner: 'Workday product and engineering teams building enterprise finance and human-capital software.',
    aiDomains: ['saas', 'ai-ml', 'data-analytics'], industries: ['enterprise software', 'HR technology'],
    fundingStage: 'Public company', hiring: true,
    careersUrl: 'https://workday.wd5.myworkdayjobs.com/Workday', website: 'https://www.workday.com/', sources: ['https://workday.wd5.myworkdayjobs.com/Workday'],
  },
  {
    id: 'salesforce-vancouver', name: 'Salesforce Vancouver', upsideKey: 'salesforce',
    industry: 'tech', type: 'tech-enterprise', lat: 49.2852, lng: -123.1120, neighborhood: 'Downtown',
    oneLiner: 'Salesforce teams delivering cloud CRM, analytics, collaboration, and AI products.',
    aiDomains: ['saas', 'ai-ml', 'cloud-infra'], industries: ['enterprise software', 'CRM'],
    fundingStage: 'Public company', hiring: true,
    careersUrl: 'https://careers.salesforce.com/en/jobs/', website: 'https://www.salesforce.com/ca/', sources: ['https://careers.salesforce.com/en/jobs/'],
  },
  {
    id: 'telus-vancouver', name: 'TELUS', upsideKey: 'telus',
    industry: 'tech', type: 'tech-enterprise', lat: 49.2818, lng: -123.1180, neighborhood: 'Downtown',
    oneLiner: 'Vancouver-headquartered telecommunications and digital-services company operating across Canada.',
    aiDomains: ['cloud-infra', 'data-analytics', 'healthtech'], industries: ['telecommunications', 'digital health'],
    fundingStage: 'Public company', hiring: true,
    careersUrl: 'https://www.telus.com/en/about/careers', website: 'https://www.telus.com/', sources: ['https://www.telus.com/en/about/careers'],
  },
  {
    id: 'd-wave-burnaby', name: 'D-Wave Quantum',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2488, lng: -122.9805, neighborhood: 'Burnaby',
    oneLiner: 'Quantum-computing company building annealing systems, hybrid solvers, and cloud access to quantum processors.',
    aiDomains: ['cloud-infra', 'devtools', 'ai-ml'], industries: ['quantum computing', 'enterprise software'],
    fundingStage: 'Public company', hiring: true,
    careersUrl: 'https://jobs.ashbyhq.com/d-wave', website: 'https://www.dwavequantum.com/', sources: ['https://www.dwavequantum.com/company/careers/'],
  },
  {
    id: 'thinkific-vancouver', name: 'Thinkific',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2661, lng: -123.1018, neighborhood: 'Mount Pleasant',
    oneLiner: 'Vancouver-founded platform for creating, marketing, and selling online learning products.',
    aiDomains: ['saas', 'edtech', 'ecommerce'], industries: ['education technology', 'creator economy'],
    fundingStage: 'Public company', hiring: true,
    careersUrl: 'https://www.thinkific.com/careers/', website: 'https://www.thinkific.com/', sources: ['https://www.thinkific.com/careers/'],
  },
  {
    id: 'jane-app-north-vancouver', name: 'Jane App',
    industry: 'tech', type: 'tech-scaleup', lat: 49.3200, lng: -123.0720, neighborhood: 'North Vancouver',
    oneLiner: 'Practice-management software for clinics covering scheduling, charting, billing, payments, and telehealth.',
    aiDomains: ['saas', 'healthtech', 'fintech'], industries: ['health technology', 'practice management'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://jane.app/careers', website: 'https://jane.app/', sources: ['https://jane.app/careers'],
  },
  {
    id: 'unbounce-vancouver', name: 'Unbounce',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2665, lng: -123.1010, neighborhood: 'Mount Pleasant',
    oneLiner: 'Conversion-intelligence platform for building and optimizing landing pages and marketing campaigns.',
    aiDomains: ['saas', 'martech', 'ai-ml'], industries: ['marketing technology', 'software'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://unbounce.com/careers/', website: 'https://unbounce.com/', sources: ['https://unbounce.com/careers/'],
  },
  {
    id: 'later-vancouver', name: 'Later',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2766, lng: -123.1154, neighborhood: 'Yaletown',
    oneLiner: 'Social-media management and influencer-marketing software used by brands and creators.',
    aiDomains: ['saas', 'martech', 'data-analytics'], industries: ['social media', 'creator economy'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://later.com/careers/', website: 'https://later.com/', sources: ['https://later.com/careers/'],
  },
  {
    id: 'procurify-vancouver', name: 'Procurify',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2668, lng: -123.1030, neighborhood: 'Mount Pleasant',
    oneLiner: 'Spend-management platform giving organizations control over purchasing, approvals, cards, and expenses.',
    aiDomains: ['saas', 'fintech', 'data-analytics'], industries: ['procurement', 'financial technology'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://www.procurify.com/careers/', website: 'https://www.procurify.com/', sources: ['https://www.procurify.com/careers/'],
  },
  {
    id: 'hiive-vancouver', name: 'Hiive',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2820, lng: -123.1170, neighborhood: 'Downtown',
    oneLiner: 'Marketplace connecting buyers and sellers of private-company shares.',
    aiDomains: ['fintech', 'saas', 'data-analytics'], industries: ['private markets', 'financial technology'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://www.hiive.com/careers', website: 'https://www.hiive.com/', sources: ['https://www.hiive.com/careers', 'https://wearebctech.com/technology-impact-awards-tias/'],
  },
  {
    id: 'klue-vancouver', name: 'Klue',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2768, lng: -123.1190, neighborhood: 'Yaletown',
    oneLiner: 'AI-powered competitive-enablement platform helping revenue teams understand and act on market intelligence.',
    aiDomains: ['ai-ml', 'saas', 'data-analytics'], industries: ['competitive intelligence', 'sales technology'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://klue.com/careers', website: 'https://klue.com/', sources: ['https://klue.com/careers'],
  },
  {
    id: 'spare-vancouver', name: 'Spare',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2670, lng: -123.1010, neighborhood: 'Mount Pleasant',
    oneLiner: 'Transit software platform for planning and operating on-demand and paratransit services.',
    aiDomains: ['saas', 'data-analytics', 'gis-geospatial'], industries: ['mobility', 'public transit'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://sparelabs.com/en/company/careers', website: 'https://sparelabs.com/', sources: ['https://sparelabs.com/en/company/careers'],
  },
  {
    id: 'apryse-vancouver', name: 'Apryse', aka: 'PDFTron',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2848, lng: -123.1125, neighborhood: 'Downtown',
    oneLiner: 'Document-processing SDK and workflow platform used to build secure digital-document products.',
    aiDomains: ['devtools', 'saas', 'cloud-infra'], industries: ['developer tools', 'document technology'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://apryse.com/company/careers', website: 'https://apryse.com/', sources: ['https://apryse.com/company/careers'],
  },
  {
    id: 'safe-software-surrey', name: 'Safe Software',
    industry: 'tech', type: 'tech-scaleup', lat: 49.1044, lng: -122.8011, neighborhood: 'Surrey',
    oneLiner: 'Data-integration platform specializing in spatial, enterprise, and cloud data interoperability.',
    aiDomains: ['gis-geospatial', 'data-analytics', 'cloud-infra'], industries: ['geospatial', 'data integration'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://www.safe.com/careers/', website: 'https://www.safe.com/', sources: ['https://www.safe.com/careers/'],
  },
  {
    id: 'copilot-ai-vancouver', name: 'CoPilot AI',
    industry: 'tech', type: 'tech-startup', lat: 49.2820, lng: -123.1170, neighborhood: 'Downtown',
    oneLiner: 'AI-assisted prospecting platform helping sales teams start and manage business conversations.',
    aiDomains: ['ai-ml', 'saas', 'martech'], industries: ['sales technology', 'artificial intelligence'],
    fundingStage: 'Private', website: 'https://www.copilotai.com/', sources: [TECH_SOURCE, 'https://www.copilotai.com/'],
  },
  {
    id: 'gumloop-vancouver', name: 'Gumloop',
    industry: 'tech', type: 'tech-startup', lat: 49.2824, lng: -123.1187, neighborhood: 'Downtown',
    oneLiner: 'No-code platform for building and operating AI-powered business automations.',
    aiDomains: ['ai-ml', 'saas', 'devtools'], industries: ['artificial intelligence', 'automation'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://www.gumloop.com/careers', website: 'https://www.gumloop.com/', sources: [TECH_SOURCE, 'https://www.gumloop.com/'],
  },
  {
    id: 'browse-ai-vancouver', name: 'Browse AI',
    industry: 'tech', type: 'tech-startup', lat: 49.2766, lng: -123.1154, neighborhood: 'Yaletown',
    oneLiner: 'No-code web-data extraction and monitoring platform built around trainable robots.',
    aiDomains: ['ai-ml', 'saas', 'data-analytics'], industries: ['web data', 'automation'],
    fundingStage: 'Private', website: 'https://www.browse.ai/', sources: [TECH_SOURCE, 'https://www.browse.ai/'],
  },
  {
    id: 'apera-ai-burnaby', name: 'Apera AI',
    industry: 'tech', type: 'tech-startup', lat: 49.2488, lng: -122.9805, neighborhood: 'Burnaby',
    oneLiner: 'AI vision software enabling industrial robots to identify and handle complex objects.',
    aiDomains: ['ai-ml', 'robotics'], industries: ['industrial automation', 'robotics'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://apera.ai/careers/', website: 'https://apera.ai/', sources: [TECH_SOURCE, 'https://apera.ai/careers/'],
  },
  {
    id: 'wayve-vancouver', name: 'Wayve Vancouver',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2822, lng: -123.1173, neighborhood: 'Downtown',
    oneLiner: 'Vancouver AI hub for Wayve’s embodied driving intelligence and autonomous-vehicle software.',
    aiDomains: ['ai-ml', 'robotics', 'data-analytics'], industries: ['autonomous vehicles', 'artificial intelligence'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://wayve.ai/careers/', website: 'https://wayve.ai/', sources: [TECH_SOURCE, 'https://wayve.ai/careers/'],
  },
  {
    id: 'semios-vancouver', name: 'Semios',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'Precision-agriculture platform combining field sensors, analytics, and automation for crop management.',
    aiDomains: ['ai-ml', 'iot', 'data-analytics'], industries: ['agriculture technology', 'internet of things'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://semios.com/careers/', website: 'https://semios.com/',
    sources: [TECH_SOURCE, 'https://semios.com/'],
  },
  {
    id: 'terramera-vancouver', name: 'Terramera',
    industry: 'tech', secondaryIndustries: ['cleantech'], type: 'tech-scaleup', lat: 49.2840, lng: -123.0980, neighborhood: 'Railtown',
    oneLiner: 'Agtech company using science, AI, and field data to improve crop productivity and soil outcomes.',
    aiDomains: ['ai-ml', 'data-analytics'], industries: ['agriculture technology', 'climate technology'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://www.terramera.com/careers', website: 'https://www.terramera.com/',
    sources: [TECH_SOURCE, 'https://www.terramera.com/'],
  },
  {
    id: 'weir-motion-metrics-vancouver', name: 'Weir Motion Metrics',
    industry: 'tech', type: 'tech-enterprise', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'AI and machine-vision systems that monitor mining equipment, ore, and fragmentation in real time.',
    aiDomains: ['ai-ml', 'iot', 'data-analytics'], industries: ['mining technology', 'computer vision'],
    fundingStage: 'Subsidiary of Weir Group', hiring: true, careersUrl: 'https://www.global.weir/careers/', website: 'https://www.global.weir/brands/motion-metrics/',
    sources: [TECH_SOURCE, 'https://www.global.weir/brands/motion-metrics/'],
  },
  {
    id: 'intuitive-ai-vancouver', name: 'Intuitive AI',
    industry: 'tech', secondaryIndustries: ['cleantech'], type: 'tech-startup', lat: 49.2766, lng: -123.1154, neighborhood: 'Yaletown',
    oneLiner: 'AI-powered waste-sorting guidance designed to improve recycling decisions in public spaces.',
    aiDomains: ['ai-ml', 'computer-vision'], industries: ['waste technology', 'artificial intelligence'],
    fundingStage: 'Private', website: 'https://intuitiveai.ca/', sources: [TECH_SOURCE, 'https://intuitiveai.ca/'],
  },
  {
    id: 'photonic-coquitlam', name: 'Photonic',
    industry: 'tech', type: 'tech-scaleup', lat: 49.2838, lng: -122.7932, neighborhood: 'Coquitlam',
    oneLiner: 'Quantum-computing company developing distributed silicon-spin systems and quantum networking.',
    aiDomains: ['cloud-infra', 'devtools'], industries: ['quantum computing', 'semiconductors'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://photonic.com/careers/', website: 'https://photonic.com/',
    sources: ['https://photonic.com/careers/', 'https://wearebctech.com/bc-techmap-2026/'],
  },
  {
    id: 'ecoation-north-vancouver', name: 'ecoation',
    industry: 'tech', secondaryIndustries: ['cleantech'], type: 'tech-startup', lat: 49.3200, lng: -123.0720, neighborhood: 'North Vancouver',
    oneLiner: 'Greenhouse intelligence platform combining robotics, sensors, and AI-assisted crop monitoring.',
    aiDomains: ['ai-ml', 'robotics', 'iot'], industries: ['agriculture technology', 'greenhouses'],
    fundingStage: 'Private', website: 'https://ecoation.com/', sources: [TECH_SOURCE, 'https://ecoation.com/'],
  },
  {
    id: 'fujitsu-ai-vancouver', name: 'Fujitsu Vancouver',
    industry: 'tech', type: 'tech-enterprise', lat: 49.2820, lng: -123.1170, neighborhood: 'Downtown',
    oneLiner: 'Fujitsu’s Vancouver presence includes its global artificial-intelligence headquarters and enterprise technology teams.',
    aiDomains: ['ai-ml', 'cloud-infra', 'data-analytics'], industries: ['artificial intelligence', 'IT services'],
    fundingStage: 'Public company', hiring: true, careersUrl: 'https://www.fujitsu.com/ca/en/about/local/jobs/', website: 'https://www.fujitsu.com/ca/en/',
    sources: [TECH_SOURCE, 'https://www.fujitsu.com/ca/en/about/local/jobs/'],
  },

  // ── Gaming, animation, and visual effects ─────────────────────────────────
  {
    id: 'nintendo-canada-vancouver', name: 'Nintendo of Canada',
    industry: 'gaming', type: 'gaming-aaa', lat: 49.2835, lng: -123.1145, neighborhood: 'Downtown',
    oneLiner: 'Nintendo’s Canadian business operation supporting one of the world’s largest game platforms and franchises.',
    aiDomains: ['aaa-games', 'live-service'], industries: ['video games', 'consumer entertainment'],
    fundingStage: 'Subsidiary of Nintendo', hiring: true,
    careersUrl: 'https://careers.nintendo.com/', website: 'https://www.nintendo.com/en-ca/', sources: [GAMING_SOURCE, 'https://careers.nintendo.com/'],
  },
  {
    id: 'bardel-entertainment-vancouver', name: 'Bardel Entertainment',
    industry: 'gaming', type: 'gaming-vfx', lat: 49.2690, lng: -123.0690, neighborhood: 'East Vancouver',
    oneLiner: 'Vancouver animation studio producing series and feature work for major global entertainment brands.',
    aiDomains: ['animation', 'vfx-tv', 'vfx-film'], industries: ['animation', 'film and television'],
    fundingStage: 'Subsidiary of Rainbow', hiring: true,
    careersUrl: 'https://bardel.ca/careers/', website: 'https://bardel.ca/', sources: [GAMING_SOURCE, 'https://bardel.ca/careers/'],
  },
  {
    id: 'ilm-vancouver', name: 'Industrial Light & Magic Vancouver',
    industry: 'gaming', type: 'gaming-vfx', lat: 49.2840, lng: -123.1080, neighborhood: 'Gastown',
    oneLiner: 'ILM visual-effects and virtual-production studio serving major film and episodic productions.',
    aiDomains: ['vfx-film', 'vfx-tv', 'animation'], industries: ['visual effects', 'film'],
    fundingStage: 'Subsidiary of Disney', hiring: true,
    careersUrl: 'https://www.ilm.com/careers/', website: 'https://www.ilm.com/', sources: [GAMING_SOURCE, 'https://www.ilm.com/careers/'],
  },
  {
    id: 'framestore-vancouver', name: 'Framestore Vancouver',
    industry: 'gaming', type: 'gaming-vfx', lat: 49.2832, lng: -123.1090, neighborhood: 'Gastown',
    oneLiner: 'Vancouver studio of the global visual-effects, animation, and immersive-experience company.',
    aiDomains: ['vfx-film', 'vfx-tv', 'animation'], industries: ['visual effects', 'animation'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://www.framestore.com/careers', website: 'https://www.framestore.com/', sources: [GAMING_SOURCE, 'https://www.framestore.com/careers'],
  },
  {
    id: 'image-engine-vancouver', name: 'Image Engine',
    industry: 'gaming', type: 'gaming-vfx', lat: 49.2828, lng: -123.1080, neighborhood: 'Gastown',
    oneLiner: 'Vancouver visual-effects studio creating creatures, environments, and digital worlds for film and television.',
    aiDomains: ['vfx-film', 'vfx-tv', 'animation'], industries: ['visual effects', 'film'],
    fundingStage: 'Subsidiary of Cinesite', hiring: true,
    careersUrl: 'https://image-engine.com/careers/', website: 'https://image-engine.com/', sources: [GAMING_SOURCE, 'https://image-engine.com/careers/'],
  },
  {
    id: 'scanline-vfx-vancouver', name: 'Scanline VFX Vancouver',
    industry: 'gaming', type: 'gaming-vfx', lat: 49.2814, lng: -123.1095, neighborhood: 'Gastown',
    oneLiner: 'Netflix-owned visual-effects studio known for large-scale simulation and virtual production.',
    aiDomains: ['vfx-film', 'vfx-tv', 'animation'], industries: ['visual effects', 'streaming'],
    fundingStage: 'Subsidiary of Netflix', hiring: true,
    careersUrl: 'https://www.scanlinevfx.com/careers', website: 'https://www.scanlinevfx.com/', sources: ['https://www.scanlinevfx.com/careers'],
  },
  {
    id: 'atomic-cartoons-vancouver', name: 'Atomic Cartoons',
    industry: 'gaming', type: 'gaming-vfx', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'Vancouver animation studio producing original and partner-driven series for global audiences.',
    aiDomains: ['animation', 'vfx-tv'], industries: ['animation', 'television'],
    fundingStage: 'Subsidiary of Thunderbird Entertainment', hiring: true,
    careersUrl: 'https://atomiccartoons.com/careers/', website: 'https://atomiccartoons.com/', sources: ['https://digibc.org/2025/12/01/2025-member-highlights/', 'https://atomiccartoons.com/careers/'],
  },
  {
    id: 'wildbrain-studios-vancouver', name: 'WildBrain Studios Vancouver',
    industry: 'gaming', type: 'gaming-vfx', lat: 49.2660, lng: -123.1000, neighborhood: 'Mount Pleasant',
    oneLiner: 'Animation production studio working across kids’ and family entertainment franchises.',
    aiDomains: ['animation', 'vfx-tv'], industries: ['animation', 'television'],
    fundingStage: 'Public company', hiring: true,
    careersUrl: 'https://www.wildbrain.com/careers', website: 'https://www.wildbrain.com/', sources: ['https://www.wildbrain.com/careers'],
  },
  {
    id: 'mainframe-studios-vancouver', name: 'Mainframe Studios',
    industry: 'gaming', type: 'gaming-vfx', lat: 49.2488, lng: -122.9805, neighborhood: 'Burnaby',
    oneLiner: 'Computer-animation studio creating television, feature, and branded entertainment.',
    aiDomains: ['animation', 'vfx-tv', 'vfx-film'], industries: ['animation', 'film and television'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://www.mainframe.ca/careers/', website: 'https://www.mainframe.ca/', sources: ['https://www.mainframe.ca/careers/'],
  },
  {
    id: 'relic-entertainment-vancouver', name: 'Relic Entertainment',
    industry: 'gaming', type: 'gaming-mid', lat: 49.2670, lng: -123.1000, neighborhood: 'Mount Pleasant',
    oneLiner: 'Vancouver game studio known for strategy franchises including Company of Heroes and Age of Empires.',
    aiDomains: ['aaa-games', 'live-service'], industries: ['video games', 'strategy games'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://www.relic.com/careers', website: 'https://www.relic.com/', sources: ['https://www.relic.com/careers'],
  },
  {
    id: 'blackbird-interactive-vancouver', name: 'Blackbird Interactive',
    industry: 'gaming', type: 'gaming-mid', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'Independent Vancouver studio developing original and partner game projects.',
    aiDomains: ['aaa-games', 'co-development'], industries: ['video games', 'interactive entertainment'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://blackbirdinteractive.com/careers/', website: 'https://blackbirdinteractive.com/', sources: ['https://blackbirdinteractive.com/careers/'],
  },
  {
    id: 'east-side-games-vancouver', name: 'East Side Games',
    industry: 'gaming', type: 'gaming-mid', lat: 49.2810, lng: -123.0700, neighborhood: 'East Vancouver',
    oneLiner: 'Vancouver mobile-game studio and publishing platform focused on narrative idle games.',
    aiDomains: ['mobile-games', 'live-service', 'narrative'], industries: ['mobile games', 'publishing'],
    fundingStage: 'Subsidiary of East Side Games Group', hiring: true,
    careersUrl: 'https://www.eastsidegames.com/jobs/', website: 'https://www.eastsidegames.com/', sources: ['https://wearebctech.com/meet-the-company-of-the-year-scale-tia-finalists/', 'https://www.eastsidegames.com/jobs/'],
  },
  {
    id: 'kabam-vancouver', name: 'Kabam Vancouver',
    industry: 'gaming', type: 'gaming-mid', lat: 49.2825, lng: -123.1175, neighborhood: 'Downtown',
    oneLiner: 'Mobile-game studio operating globally recognized free-to-play titles and live services.',
    aiDomains: ['mobile-games', 'live-service'], industries: ['mobile games', 'interactive entertainment'],
    fundingStage: 'Subsidiary of Netmarble', hiring: true,
    careersUrl: 'https://kabam.com/careers/', website: 'https://kabam.com/', sources: ['https://kabam.com/careers/'],
  },
  {
    id: 'skybox-labs-vancouver', name: 'SkyBox Labs',
    industry: 'gaming', type: 'gaming-services', lat: 49.2488, lng: -122.9805, neighborhood: 'Burnaby',
    oneLiner: 'Game-development and co-development studio contributing to major console and PC franchises.',
    aiDomains: ['co-development', 'aaa-games'], industries: ['video games', 'co-development'],
    fundingStage: 'Subsidiary of NetEase', hiring: true,
    careersUrl: 'https://skyboxlabs.com/careers/', website: 'https://skyboxlabs.com/', sources: ['https://skyboxlabs.com/careers/'],
  },
  {
    id: 'larian-vancouver', name: 'Larian Studios Vancouver',
    industry: 'gaming', type: 'gaming-aaa', lat: 49.2830, lng: -123.1160, neighborhood: 'Downtown',
    oneLiner: 'Vancouver studio of the independent developer behind the Divinity series and Baldur’s Gate 3.',
    aiDomains: ['aaa-games', 'narrative'], industries: ['video games', 'role-playing games'],
    fundingStage: 'Private', hiring: true,
    careersUrl: 'https://larian.com/careers', website: 'https://larian.com/', sources: ['https://larian.com/careers'],
  },

  // ── Clean technology ──────────────────────────────────────────────────────
  {
    id: 'htec-vancouver', name: 'HTEC',
    industry: 'cleantech', type: 'cleantech-startup', lat: 49.2488, lng: -122.9805, neighborhood: 'Burnaby',
    oneLiner: 'Hydrogen infrastructure company developing production, distribution, and fuelling networks.',
    aiDomains: ['hydrogen', 'industrial-decarbonization'], industries: ['hydrogen', 'clean transportation'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://www.htec.ca/careers/', website: 'https://www.htec.ca/',
    sources: [CLEAN_SOURCE, 'https://www.htec.ca/careers/'],
  },
  {
    id: 'miru-vancouver', name: 'Miru Smart Technologies',
    industry: 'cleantech', type: 'cleantech-startup', lat: 49.2670, lng: -123.1000, neighborhood: 'Mount Pleasant',
    oneLiner: 'Electrochromic-window technology designed to reduce building energy use and improve occupant comfort.',
    aiDomains: ['energy-efficiency', 'industrial-decarbonization'], industries: ['smart glass', 'buildings'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://mirucorp.com/careers/', website: 'https://mirucorp.com/',
    sources: [CLEAN_SOURCE, 'https://mirucorp.com/'],
  },
  {
    id: 'axine-water-vancouver', name: 'Axine Water Technologies',
    industry: 'cleantech', type: 'cleantech-startup', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'Industrial wastewater treatment systems that destroy persistent organic contaminants on site.',
    aiDomains: ['clean-water', 'industrial-decarbonization'], industries: ['water treatment', 'industrial technology'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://www.axinewater.com/careers/', website: 'https://www.axinewater.com/',
    sources: [CLEAN_SOURCE, 'https://www.axinewater.com/'],
  },
  {
    id: 'saltworks-richmond', name: 'Saltworks Technologies',
    industry: 'cleantech', type: 'cleantech-startup', lat: 49.1666, lng: -123.1336, neighborhood: 'Richmond',
    oneLiner: 'Advanced water-treatment systems for desalination, industrial wastewater, and lithium processing.',
    aiDomains: ['clean-water', 'mining-tech'], industries: ['water treatment', 'resource technology'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://www.saltworkstech.com/careers/', website: 'https://www.saltworkstech.com/',
    sources: [CLEAN_SOURCE, 'https://www.saltworkstech.com/careers/'],
  },
  {
    id: 'co2lock-vancouver', name: 'CO2Lock',
    industry: 'cleantech', type: 'cleantech-startup', lat: 49.2820, lng: -123.1170, neighborhood: 'Downtown',
    oneLiner: 'Carbon-mineralization company developing permanent CO₂ storage in mine tailings and rocks.',
    aiDomains: ['carbon-capture', 'mining-tech'], industries: ['carbon removal', 'mining'],
    fundingStage: 'Private', website: 'https://co2lockcorp.com/', sources: [CLEAN_SOURCE, 'https://co2lockcorp.com/'],
  },
  {
    id: 'ideon-richmond', name: 'Ideon Technologies',
    industry: 'cleantech', type: 'cleantech-scaleup', lat: 49.1666, lng: -123.1336, neighborhood: 'Richmond',
    oneLiner: 'Muon-tomography and geoscience intelligence platform helping mines see beneath the surface.',
    aiDomains: ['mining-tech', 'data-analytics'], industries: ['mining technology', 'geophysics'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://ideon.ai/careers/', website: 'https://ideon.ai/',
    sources: [CLEAN_SOURCE, TECH_SOURCE, 'https://ideon.ai/'],
  },
  {
    id: 'hydra-energy-vancouver', name: 'Hydra Energy',
    industry: 'cleantech', type: 'cleantech-startup', lat: 49.2670, lng: -123.1000, neighborhood: 'Mount Pleasant',
    oneLiner: 'Hydrogen-as-a-service platform converting heavy-duty fleets to lower-carbon dual-fuel operation.',
    aiDomains: ['hydrogen', 'industrial-decarbonization'], industries: ['clean transportation', 'hydrogen'],
    fundingStage: 'Private', website: 'https://hydraenergy.com/', sources: [CLEAN_SOURCE, 'https://hydraenergy.com/'],
  },
  {
    id: 'invinity-vancouver', name: 'Invinity Energy Systems',
    industry: 'cleantech', type: 'cleantech-utility', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'Manufacturer of vanadium flow batteries for long-duration stationary energy storage.',
    aiDomains: ['energy-storage', 'grid-management', 'renewable-energy'], industries: ['energy storage', 'power systems'],
    fundingStage: 'Public company', hiring: true, careersUrl: 'https://invinity.com/careers/', website: 'https://invinity.com/',
    sources: [CLEAN_SOURCE, 'https://invinity.com/careers/'],
  },
  {
    id: 'westport-fuel-systems-vancouver', name: 'Westport Fuel Systems',
    industry: 'cleantech', type: 'cleantech-utility', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'Vancouver-headquartered clean-transport company developing alternative-fuel powertrain systems.',
    aiDomains: ['hydrogen', 'industrial-decarbonization'], industries: ['transportation', 'powertrain technology'],
    fundingStage: 'Public company', hiring: true, careersUrl: 'https://www.westport.com/careers', website: 'https://wfsinc.com/',
    sources: ['https://www.westport.com/careers'],
  },
  {
    id: 'corvus-energy-richmond', name: 'Corvus Energy',
    industry: 'cleantech', secondaryIndustries: ['marine'], type: 'cleantech-scaleup', lat: 49.1666, lng: -123.1336, neighborhood: 'Richmond',
    oneLiner: 'Marine battery systems and energy-storage solutions for hybrid and fully electric vessels.',
    aiDomains: ['energy-storage', 'green-shipping'], industries: ['marine technology', 'battery systems'],
    fundingStage: 'Subsidiary of Hydro', hiring: true, careersUrl: 'https://corvusenergy.teamtailor.com/', website: 'https://corvusenergy.com/',
    sources: ['https://corvusenergy.com/about', 'https://corvusenergy.teamtailor.com/'],
  },
  {
    id: 'powertech-labs-surrey', name: 'Powertech Labs',
    industry: 'cleantech', type: 'cleantech-research', lat: 49.1044, lng: -122.8011, neighborhood: 'Surrey',
    oneLiner: 'Testing and applied-research laboratory for clean energy, grid systems, hydrogen, and transportation.',
    aiDomains: ['hydrogen', 'grid-management', 'renewable-energy'], industries: ['testing', 'energy research'],
    fundingStage: 'Subsidiary of BC Hydro', hiring: true, careersUrl: 'https://www.powertechlabs.com/careers/', website: 'https://www.powertechlabs.com/',
    sources: ['https://www.powertechlabs.com/careers/'],
  },
  {
    id: 'moment-energy-coquitlam', name: 'Moment Energy',
    industry: 'cleantech', type: 'cleantech-startup', lat: 49.2838, lng: -122.7932, neighborhood: 'Coquitlam',
    oneLiner: 'Second-life battery company repurposing retired electric-vehicle packs into stationary storage.',
    aiDomains: ['energy-storage', 'grid-management'], industries: ['battery systems', 'circular economy'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://www.momentenergy.com/careers/', website: 'https://www.momentenergy.com/',
    sources: ['https://www.momentenergy.com/careers/'],
  },
  {
    id: 'mangrove-lithium-delta', name: 'Mangrove Lithium',
    industry: 'cleantech', type: 'cleantech-startup', lat: 49.0847, lng: -123.0580, neighborhood: 'Delta',
    oneLiner: 'Electrochemical refining technology for producing battery-grade lithium from diverse feedstocks.',
    aiDomains: ['battery-materials', 'industrial-decarbonization'], industries: ['battery materials', 'lithium refining'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://www.mangrovelithium.com/careers/', website: 'https://www.mangrovelithium.com/',
    sources: ['https://www.mangrovelithium.com/careers/'],
  },
  {
    id: 'clir-renewables-vancouver', name: 'Clir Renewables',
    industry: 'cleantech', type: 'cleantech-scaleup', lat: 49.2766, lng: -123.1154, neighborhood: 'Yaletown',
    oneLiner: 'Renewable-energy intelligence platform improving wind and solar asset performance through data analytics.',
    aiDomains: ['renewable-energy', 'data-analytics'], industries: ['renewable energy', 'asset analytics'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://www.clir.eco/careers', website: 'https://www.clir.eco/',
    sources: [TECH_SOURCE, 'https://www.clir.eco/'],
  },
  {
    id: 'viridis-research-vancouver', name: 'Viridis Research',
    industry: 'cleantech', type: 'cleantech-startup', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'Industrial water and resource-recovery technology company focused on difficult waste streams.',
    aiDomains: ['clean-water', 'industrial-decarbonization'], industries: ['water treatment', 'resource recovery'],
    fundingStage: 'Private', website: 'https://viridisresearch.com/', sources: [CLEAN_SOURCE, 'https://viridisresearch.com/'],
  },
  {
    id: 'nexterra-systems-vancouver', name: 'Nexterra Systems',
    industry: 'cleantech', type: 'cleantech-startup', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'Biomass gasification systems that convert waste feedstocks into usable heat and power.',
    aiDomains: ['renewable-energy', 'industrial-decarbonization'], industries: ['bioenergy', 'waste conversion'],
    fundingStage: 'Private', website: 'https://www.nexterra.ca/', sources: [CLEAN_SOURCE, 'https://www.nexterra.ca/'],
  },
  {
    id: 'anaconda-systems-vancouver', name: 'Anaconda Systems',
    industry: 'cleantech', type: 'cleantech-startup', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'Organic-waste processing systems that turn food and agricultural residues into useful products.',
    aiDomains: ['industrial-decarbonization', 'renewable-energy'], industries: ['waste technology', 'circular economy'],
    fundingStage: 'Private', website: 'https://anacondasystems.ca/', sources: [CLEAN_SOURCE, 'https://anacondasystems.ca/'],
  },

  // ── Life sciences, digital health, and medical devices ────────────────────
  {
    id: 'zymeworks-vancouver', name: 'Zymeworks',
    industry: 'lifesci', type: 'lifesci-biotech', lat: 49.2670, lng: -123.1000, neighborhood: 'Mount Pleasant',
    oneLiner: 'Clinical-stage biotechnology company developing multifunctional biotherapeutics for difficult cancers.',
    aiDomains: ['biotech-rd', 'drug-discovery', 'immunotherapy'], industries: ['biotechnology', 'oncology'],
    fundingStage: 'Public company', hiring: true, careersUrl: 'https://www.zymeworks.com/careers', website: 'https://www.zymeworks.com/',
    sources: [LIFE_SOURCE, 'https://www.zymeworks.com/careers'],
  },
  {
    id: 'well-health-vancouver', name: 'WELL Health Technologies',
    industry: 'lifesci', type: 'lifesci-pharma', lat: 49.2820, lng: -123.1170, neighborhood: 'Downtown',
    oneLiner: 'Vancouver-headquartered digital-health company operating clinics and healthcare software platforms.',
    aiDomains: ['medical-devices', 'diagnostics', 'precision-medicine'], industries: ['digital health', 'healthcare services'],
    fundingStage: 'Public company', hiring: true, careersUrl: 'https://well.company/careers/', website: 'https://well.company/',
    sources: [LIFE_SOURCE, 'https://well.company/careers/'],
  },
  {
    id: 'macrohealth-vancouver', name: 'MacroHealth',
    industry: 'lifesci', type: 'lifesci-biotech', lat: 49.2766, lng: -123.1154, neighborhood: 'Yaletown',
    oneLiner: 'Healthcare marketplace and analytics platform connecting payers with provider networks.',
    aiDomains: ['precision-medicine', 'diagnostics'], industries: ['digital health', 'health benefits'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://www.macrohealth.com/careers', website: 'https://www.macrohealth.com/',
    sources: [LIFE_SOURCE, 'https://www.macrohealth.com/'],
  },
  {
    id: 'healthtech-connex-surrey', name: 'HealthTech Connex',
    industry: 'lifesci', type: 'lifesci-biotech', lat: 49.1044, lng: -122.8011, neighborhood: 'Surrey',
    oneLiner: 'Health-technology company developing brain-health assessment, treatment, and clinical platforms.',
    aiDomains: ['medical-devices', 'diagnostics', 'neuroscience'], industries: ['brain health', 'medical technology'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://healthtechconnex.com/careers/', website: 'https://healthtechconnex.com/',
    sources: [LIFE_SOURCE, 'https://healthtechconnex.com/'],
  },
  {
    id: 'arbutus-medical-vancouver', name: 'Arbutus Medical',
    industry: 'lifesci', type: 'lifesci-biotech', lat: 49.2606, lng: -123.2466, neighborhood: 'UBC',
    oneLiner: 'Medical-device company designing practical surgical tools for trauma care worldwide.',
    aiDomains: ['medical-devices'], industries: ['medical devices', 'orthopaedics'],
    fundingStage: 'Private', website: 'https://arbutusmedical.com/', sources: [LIFE_SOURCE, 'https://arbutusmedical.com/'],
  },
  {
    id: 'kardium-burnaby', name: 'Kardium',
    industry: 'lifesci', type: 'lifesci-biotech', lat: 49.2488, lng: -122.9805, neighborhood: 'Burnaby',
    oneLiner: 'Medical-device company developing the Globe system for mapping and treating atrial fibrillation.',
    aiDomains: ['medical-devices', 'diagnostics'], industries: ['cardiology', 'medical devices'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://kardium.com/careers/', website: 'https://kardium.com/',
    sources: [LIFE_SOURCE, 'https://kardium.com/careers/'],
  },
  {
    id: 'corcym-burnaby', name: 'Corcym Canada',
    industry: 'lifesci', type: 'lifesci-pharma', lat: 49.2488, lng: -122.9805, neighborhood: 'Burnaby',
    oneLiner: 'Cardiovascular medical-device company developing and manufacturing surgical heart-valve technologies.',
    aiDomains: ['medical-devices'], industries: ['cardiovascular devices', 'manufacturing'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://corcym.com/careers/', website: 'https://corcym.com/',
    sources: [LIFE_SOURCE, 'https://corcym.com/'],
  },
  {
    id: 'clarius-vancouver', name: 'Clarius Mobile Health',
    industry: 'lifesci', secondaryIndustries: ['tech'], type: 'lifesci-biotech', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'AI-enabled handheld ultrasound systems connected to mobile devices and cloud software.',
    aiDomains: ['medical-devices', 'diagnostics', 'ai-ml'], industries: ['medical imaging', 'artificial intelligence'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://clarius.com/about/careers/', website: 'https://clarius.com/',
    sources: [TECH_SOURCE, 'https://clarius.com/about/careers/'],
  },
  {
    id: 'molecular-you-vancouver', name: 'Molecular You',
    industry: 'lifesci', secondaryIndustries: ['tech'], type: 'lifesci-biotech', lat: 49.2606, lng: -123.2466, neighborhood: 'UBC',
    oneLiner: 'Precision-health platform using multi-omics biomarkers and analytics to assess disease risk.',
    aiDomains: ['precision-medicine', 'diagnostics', 'ai-ml'], industries: ['precision health', 'biomarkers'],
    fundingStage: 'Private', website: 'https://molecularyou.com/', sources: [TECH_SOURCE, 'https://molecularyou.com/'],
  },
  {
    id: 'variational-ai-vancouver', name: 'Variational AI',
    industry: 'lifesci', secondaryIndustries: ['tech'], type: 'lifesci-biotech', lat: 49.2670, lng: -123.1000, neighborhood: 'Mount Pleasant',
    oneLiner: 'Generative-AI drug-discovery company designing novel small molecules for difficult targets.',
    aiDomains: ['drug-discovery', 'biotech-rd', 'ai-ml'], industries: ['artificial intelligence', 'drug discovery'],
    fundingStage: 'Private', website: 'https://variational.ai/',
    sources: [TECH_SOURCE, 'https://variational.ai/'],
  },
  {
    id: 'admare-vancouver', name: 'adMare BioInnovations Vancouver',
    industry: 'lifesci', type: 'lifesci-org', lat: 49.2606, lng: -123.2466, neighborhood: 'UBC',
    oneLiner: 'National life-sciences venture builder with a Vancouver innovation centre, labs, and company-creation programs.',
    aiDomains: ['biotech-rd', 'drug-discovery'], industries: ['life-science commercialization', 'venture building'],
    fundingStage: 'Non-profit', hiring: true, careersUrl: 'https://www.admarebio.com/en/culture', website: 'https://www.admarebio.com/',
    sources: [LIFE_SOURCE, 'https://www.admarebio.com/en/culture'],
  },
  {
    id: 'artms-burnaby', name: 'ARTMS',
    industry: 'lifesci', type: 'lifesci-biotech', lat: 49.2488, lng: -122.9805, neighborhood: 'Burnaby',
    oneLiner: 'Cyclotron technology for producing diagnostic and therapeutic medical isotopes.',
    aiDomains: ['medical-devices', 'diagnostics'], industries: ['medical isotopes', 'nuclear medicine'],
    fundingStage: 'Subsidiary of Telix', website: 'https://artms.ca/', sources: ['https://artms.ca/'],
  },
  {
    id: 'canary-medical-vancouver', name: 'Canary Medical',
    industry: 'lifesci', type: 'lifesci-biotech', lat: 49.2766, lng: -123.1154, neighborhood: 'Yaletown',
    oneLiner: 'Connected medical implants that collect and transmit patient recovery and device-performance data.',
    aiDomains: ['medical-devices', 'diagnostics'], industries: ['orthopaedics', 'connected health'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://canarymedical.com/careers/', website: 'https://canarymedical.com/',
    sources: ['https://lifesciencesbc.ca/membership/members-directory/', 'https://canarymedical.com/'],
  },
  {
    id: 'abdera-therapeutics-vancouver', name: 'Abdera Therapeutics',
    industry: 'lifesci', type: 'lifesci-biotech', lat: 49.2670, lng: -123.1000, neighborhood: 'Mount Pleasant',
    oneLiner: 'Biotechnology company developing precision radiopharmaceuticals for cancer.',
    aiDomains: ['drug-discovery', 'biotech-rd', 'precision-medicine'], industries: ['oncology', 'radiopharmaceuticals'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://abderatx.com/careers/', website: 'https://abderatx.com/',
    sources: ['https://abderatx.com/'],
  },
  {
    id: 'alpha9-theranostics-vancouver', name: 'Alpha-9 Theranostics',
    industry: 'lifesci', type: 'lifesci-biotech', lat: 49.2670, lng: -123.1000, neighborhood: 'Mount Pleasant',
    oneLiner: 'Clinical-stage company developing radiopharmaceutical therapies and diagnostics for cancer.',
    aiDomains: ['drug-discovery', 'clinical-trials', 'diagnostics'], industries: ['oncology', 'radiopharmaceuticals'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://alpha9therapeutics.com/careers/', website: 'https://alpha9therapeutics.com/',
    sources: ['https://alpha9therapeutics.com/'],
  },
  {
    id: 'evonik-vancouver', name: 'Evonik Vancouver Laboratories',
    industry: 'lifesci', type: 'lifesci-pharma', lat: 49.2675, lng: -123.0900, neighborhood: 'False Creek Flats',
    oneLiner: 'Evonik site developing lipid-based drug-delivery and formulation technologies for advanced medicines.',
    aiDomains: ['drug-discovery', 'biotech-rd'], industries: ['drug delivery', 'pharmaceuticals'],
    fundingStage: 'Public company', hiring: true, careersUrl: 'https://careers.evonik.com/', website: 'https://www.evonik.com/',
    sources: [LIFE_SOURCE, 'https://careers.evonik.com/'],
  },

  // ── Aerospace and aviation ────────────────────────────────────────────────
  {
    id: 'mda-space-richmond', name: 'MDA Space Richmond',
    industry: 'aerospace', type: 'space', lat: 49.1666, lng: -123.1336, neighborhood: 'Richmond',
    oneLiner: 'Space systems site working on satellite payloads, robotics, and geointelligence technology.',
    aiDomains: ['space', 'systems', 'manufacturing'], industries: ['space', 'satellites'],
    fundingStage: 'Public company', hiring: true, careersUrl: 'https://mda.space/en/careers/', website: 'https://mda.space/',
    sources: [AERO_SOURCE, 'https://mda.space/en/careers/'],
  },
  {
    id: 'boeing-vancouver', name: 'Boeing Vancouver',
    industry: 'aerospace', type: 'oem', lat: 49.1666, lng: -123.1336, neighborhood: 'Richmond',
    oneLiner: 'Boeing digital aviation and analytics teams supporting airline operations and flight services.',
    aiDomains: ['systems', 'simulation', 'avionics'], industries: ['aerospace', 'aviation software'],
    fundingStage: 'Public company', hiring: true, careersUrl: 'https://jobs.boeing.com/location/canada-jobs/185/6251999/2', website: 'https://www.boeing.ca/',
    sources: [AERO_SOURCE, 'https://jobs.boeing.com/location/canada-jobs/185/6251999/2'],
  },
  {
    id: 'mtu-maintenance-richmond', name: 'MTU Maintenance Canada',
    industry: 'aerospace', type: 'mro', lat: 49.1666, lng: -123.1336, neighborhood: 'Richmond',
    oneLiner: 'Engine maintenance, repair, and overhaul facility serving commercial aircraft operators.',
    aiDomains: ['mro', 'propulsion', 'manufacturing'], industries: ['aircraft engines', 'maintenance'],
    fundingStage: 'Subsidiary of MTU Aero Engines', hiring: true, careersUrl: 'https://www.mtu.de/careers/online-job-market/', website: 'https://www.mtu.de/',
    sources: ['https://www.mtu.de/careers/online-job-market/'],
  },
  {
    id: 'harbour-air-richmond', name: 'Harbour Air',
    industry: 'aerospace', type: 'oem', lat: 49.1760, lng: -123.1680, neighborhood: 'Richmond',
    oneLiner: 'Vancouver-founded seaplane airline connecting coastal communities and developing electric-flight capability.',
    aiDomains: ['systems', 'sustainable-aviation'], industries: ['aviation', 'regional transportation'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://harbourair.com/careers/', website: 'https://harbourair.com/',
    sources: ['https://harbourair.com/careers/'],
  },
  {
    id: 'helijet-vancouver', name: 'Helijet International',
    industry: 'aerospace', type: 'oem', lat: 49.2890, lng: -123.0940, neighborhood: 'Downtown',
    oneLiner: 'Scheduled helicopter airline and aviation-services operator connecting Vancouver and Vancouver Island.',
    aiDomains: ['systems', 'mro'], industries: ['aviation', 'regional transportation'],
    fundingStage: 'Public company', hiring: true, careersUrl: 'https://helijet.com/careers/', website: 'https://helijet.com/',
    sources: ['https://helijet.com/careers/'],
  },
  {
    id: 'ise-port-coquitlam', name: 'International Submarine Engineering',
    industry: 'aerospace', secondaryIndustries: ['marine'], type: 'defense', lat: 49.2625, lng: -122.7810, neighborhood: 'Port Coquitlam',
    oneLiner: 'Engineering company designing autonomous underwater vehicles, remotely operated systems, and subsea equipment.',
    aiDomains: ['defense', 'systems', 'uav'], industries: ['marine robotics', 'defense'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://ise.bc.ca/jobs/', website: 'https://ise.bc.ca/',
    sources: ['https://ise.bc.ca/jobs/'],
  },

  // ── Marine, shipping, terminals, and naval technology ─────────────────────
  {
    id: 'seaspan-corporation-vancouver', name: 'Seaspan Corporation',
    industry: 'marine', type: 'marine-shipping', lat: 49.2820, lng: -123.1170, neighborhood: 'Downtown',
    oneLiner: 'Vancouver-based containership owner and manager operating a large global fleet.',
    aiDomains: ['shipping', 'marine-logistics', 'green-shipping'], industries: ['shipping', 'asset management'],
    fundingStage: 'Subsidiary of Atlas', hiring: true, careersUrl: 'https://www.seaspancorp.com/careers/', website: 'https://www.seaspancorp.com/',
    sources: ['https://www.seaspancorp.com/careers/'],
  },
  {
    id: 'teekay-vancouver', name: 'Teekay',
    industry: 'marine', type: 'marine-shipping', lat: 49.2830, lng: -123.1175, neighborhood: 'Downtown',
    oneLiner: 'Vancouver-founded marine energy and shipping company managing vessels and maritime operations.',
    aiDomains: ['shipping', 'marine-logistics'], industries: ['shipping', 'marine energy'],
    fundingStage: 'Public company', hiring: true, careersUrl: 'https://www.teekay.com/offices/vancouver/', website: 'https://www.teekay.com/',
    sources: ['https://www.teekay.com/offices/vancouver/'],
  },
  {
    id: 'robert-allan-vancouver', name: 'Robert Allan Ltd.',
    industry: 'marine', type: 'marine-services', lat: 49.2832, lng: -123.1090, neighborhood: 'Gastown',
    oneLiner: 'Vancouver naval-architecture firm known globally for tugboat and specialized-vessel design.',
    aiDomains: ['ship-services', 'green-shipping'], industries: ['naval architecture', 'marine engineering'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://ral.ca/careers/', website: 'https://ral.ca/',
    sources: ['https://ral.ca/careers/'],
  },
  {
    id: 'vard-marine-vancouver', name: 'VARD Marine Vancouver',
    industry: 'marine', type: 'marine-services', lat: 49.2820, lng: -123.1170, neighborhood: 'Downtown',
    oneLiner: 'Naval-architecture and marine-engineering consultancy designing commercial and government vessels.',
    aiDomains: ['ship-services', 'green-shipping'], industries: ['naval architecture', 'ship design'],
    fundingStage: 'Subsidiary of Fincantieri', hiring: true, careersUrl: 'https://vardmarine.com/careers/', website: 'https://vardmarine.com/',
    sources: ['https://vardmarine.com/careers/'],
  },
  {
    id: 'osi-maritime-burnaby', name: 'OSI Maritime Systems',
    industry: 'marine', type: 'marine-services', lat: 49.2488, lng: -122.9805, neighborhood: 'Burnaby',
    oneLiner: 'Navigation and tactical situational-awareness systems for naval and coast-guard fleets.',
    aiDomains: ['ship-services', 'marine-logistics'], industries: ['defense technology', 'naval systems'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://osimaritime.com/careers/', website: 'https://osimaritime.com/',
    sources: ['https://osimaritime.com/careers/'],
  },
  {
    id: 'gct-deltaport', name: 'GCT Global Container Terminals',
    industry: 'marine', type: 'marine-port', lat: 49.0847, lng: -123.0580, neighborhood: 'Delta',
    oneLiner: 'Container-terminal operator running Deltaport and Vanterm in the Port of Vancouver.',
    aiDomains: ['port-operations', 'cargo-handling', 'marine-logistics'], industries: ['container terminals', 'logistics'],
    fundingStage: 'Private', hiring: true, careersUrl: 'https://globalterminals.com/careers/', website: 'https://globalterminals.com/',
    sources: [MARINE_SOURCE, 'https://globalterminals.com/careers/'],
  },
  {
    id: 'dp-world-vancouver', name: 'DP World Vancouver',
    industry: 'marine', type: 'marine-port', lat: 49.2890, lng: -123.0650, neighborhood: 'East Vancouver',
    oneLiner: 'Global terminal and logistics operator running Centerm and Fraser Surrey facilities.',
    aiDomains: ['port-operations', 'cargo-handling', 'marine-logistics'], industries: ['container terminals', 'logistics'],
    fundingStage: 'Subsidiary of DP World', hiring: true, careersUrl: 'https://careers.dpworld.com/', website: 'https://www.dpworld.com/canada',
    sources: [MARINE_SOURCE, 'https://careers.dpworld.com/'],
  },
  {
    id: 'western-stevedoring-north-vancouver', name: 'Western Stevedoring',
    industry: 'marine', type: 'marine-port', lat: 49.3200, lng: -123.0720, neighborhood: 'North Vancouver',
    oneLiner: 'Terminal operator and stevedoring company handling breakbulk, bulk, cruise, and project cargo.',
    aiDomains: ['cargo-handling', 'port-operations'], industries: ['stevedoring', 'terminal operations'],
    fundingStage: 'Private', website: 'https://westernstevedoring.com/', sources: [MARINE_SOURCE, 'https://westernstevedoring.com/'],
  },
  {
    id: 'haisea-marine-north-vancouver', name: 'HaiSea Marine',
    industry: 'marine', type: 'marine-services', lat: 49.3200, lng: -123.0720, neighborhood: 'North Vancouver',
    oneLiner: 'Indigenous-majority-owned marine-services company operating low-emission escort and harbour tugs.',
    aiDomains: ['towing-salvage', 'green-shipping', 'ship-services'], industries: ['tug operations', 'marine services'],
    fundingStage: 'Joint venture', hiring: true, careersUrl: 'https://haiseamarine.com/careers/', website: 'https://haiseamarine.com/',
    sources: ['https://haiseamarine.com/careers/'],
  },
  {
    id: 'bcmea-vancouver', name: 'BC Maritime Employers Association',
    industry: 'marine', type: 'marine-org', lat: 49.2840, lng: -123.0980, neighborhood: 'Railtown',
    oneLiner: 'Employer association coordinating labour, training, safety, and workforce systems across BC ports.',
    aiDomains: ['port-operations', 'marine-logistics'], industries: ['maritime workforce', 'port operations'],
    fundingStage: 'Non-profit association', hiring: true, careersUrl: 'https://www.bcmea.com/careers/', website: 'https://www.bcmea.com/',
    sources: [MARINE_SOURCE, 'https://www.bcmea.com/what-we-do/'],
  },
  {
    id: 'neptune-terminals-north-vancouver', name: 'Neptune Bulk Terminals',
    industry: 'marine', type: 'marine-port', lat: 49.3080, lng: -123.0350, neighborhood: 'North Vancouver',
    oneLiner: 'Bulk terminal handling Canadian potash, steelmaking coal, and agricultural products.',
    aiDomains: ['port-operations', 'cargo-handling'], industries: ['bulk terminals', 'logistics'],
    fundingStage: 'Private', website: 'https://neptuneterminals.com/',
    sources: [MARINE_SOURCE, 'https://neptuneterminals.com/'],
  },
  {
    id: 'pacific-coast-terminals-port-moody', name: 'Pacific Coast Terminals',
    industry: 'marine', type: 'marine-port', lat: 49.2849, lng: -122.8678, neighborhood: 'Port Moody',
    oneLiner: 'Bulk export terminal serving Canadian resource and agricultural supply chains.',
    aiDomains: ['port-operations', 'cargo-handling', 'marine-logistics'], industries: ['bulk terminals', 'exports'],
    fundingStage: 'Private', website: 'https://www.pct.ca/', sources: [MARINE_SOURCE, 'https://www.pct.ca/'],
  },
];

export const COMPANIES: AICompany[] = companies.map((company) => ({
  ...company,
  verifiedAt: '2026-08',
}));
