import type { AICompany } from './types';

// ── Montreal's AI scene ──────────────────────────────────────────────────────
// Every notable AI lab, startup and scaleup in the city. Hand-curated and then
// deepened by live web research (mid-2026) — "maximum knowledge about each, as
// much as is available". Coordinates are real Montreal locations; where a
// company's exact street number isn't public, the point sits on its
// neighbourhood with a small offset so markers don't overlap.
//
// This file is the single source of truth for the map.

export const COMPANIES: AICompany[] = [
  // ── Research labs & institutes ─────────────────────────────────────────────
  {
    id: 'mila',
    name: 'Mila — Quebec AI Institute',
    aka: 'Montreal Institute for Learning Algorithms',
    type: 'research-lab',
    lat: 45.53012,
    lng: -73.61388,
    address: '6650 Rue Saint-Urbain, Montréal, QC H2S 3G9',
    neighborhood: 'Mile-Ex',
    oneLiner: "One of the world's largest deep-learning research institutes, founded by Turing Award winner Yoshua Bengio.",
    problem: 'Advancing AI requires concentrated fundamental research and a talent pipeline no single university can build alone.',
    solution: 'Unites 140+ professors and 1,400+ researchers across Montreal to push deep-learning research and responsible AI.',
    aiDomains: ['research', 'reinforcement-learning', 'NLP', 'computer-vision', 'generative-ai', 'LLM'],
    industries: ['research', 'healthcare', 'climate'],
    founded: 1993,
    headcount: '500-1000',
    funding: { investors: ['Government of Quebec', 'Government of Canada', 'CIFAR'] },
    hiring: true,
    notable: 'Founded by Yoshua Bengio (2018 Turing Award); the anchor of the Montreal AI ecosystem.',
    status: 'active',
    website: 'https://mila.quebec/en',
    sources: ['https://mila.quebec/en/about/about-mila', 'https://en.wikipedia.org/wiki/Mila_(research_institute)'],
  },
  {
    id: 'ivado',
    name: 'IVADO',
    aka: 'Institut de valorisation des données',
    type: 'research-lab',
    lat: 45.49923,
    lng: -73.61742,
    address: 'Pavillon André-Aisenstadt, 2920 Chemin de la Tour, Montréal, QC H3T 1J4',
    neighborhood: 'Côte-des-Neiges / UdeM',
    oneLiner: 'Interdisciplinary AI research and mobilization consortium led by Université de Montréal.',
    problem: "Realizing AI's benefits across sectors means bridging academic research, industry adoption and trustworthy methods.",
    solution: 'Brings universities, government and industry together to co-build cross-sectoral AI and mobilize data-science knowledge.',
    aiDomains: ['research', 'ml-platform', 'forecasting', 'NLP'],
    industries: ['research', 'healthcare', 'finance', 'logistics'],
    founded: 2016,
    headcount: '51-200',
    funding: { investors: ['Canada First Research Excellence Fund', 'Government of Quebec', 'Université de Montréal'] },
    notable: 'Yoshua Bengio is founding scientific director and special advisor.',
    status: 'active',
    website: 'https://ivado.ca/en/',
    sources: ['https://ivado.ca/en/about-us/', 'https://www.umontreal.ca/en/artificialintelligence/'],
  },
  {
    id: 'mcgill-cim',
    name: 'McGill Centre for Intelligent Machines',
    aka: 'CIM',
    type: 'research-lab',
    lat: 45.50436,
    lng: -73.57608,
    address: 'McConnell Engineering Building, 3480 Rue University, Montréal, QC H3A 0E9',
    neighborhood: 'McGill / Downtown',
    oneLiner: "McGill's inter-departmental research centre for intelligent systems, robotics and vision since 1985.",
    problem: 'Building intelligent machines needs cross-disciplinary expertise individual departments lack.',
    solution: 'Unites 27 principal investigators across 15 labs spanning robotics, vision, control and medical imaging.',
    aiDomains: ['robotics', 'computer-vision', 'research', 'reinforcement-learning'],
    industries: ['research', 'robotics', 'healthcare'],
    founded: 1985,
    headcount: '51-200',
    notable: 'A world leader in intelligent-systems research with 15 laboratories.',
    status: 'active',
    website: 'https://www.mcgill.ca/cim/',
    sources: ['https://www.mcgill.ca/cim/', 'https://www.mcgill.ca/cim/research/labs'],
  },
  {
    id: 'real-lab',
    name: 'REAL — Robotics & Embodied AI Lab',
    aka: 'Montreal Robotics Lab',
    type: 'research-lab',
    lat: 45.52948,
    lng: -73.61452,
    neighborhood: 'Mile-Ex',
    oneLiner: 'UdeM/Mila robotics lab led by Liam Paull, building generalist robots and embodied agents.',
    problem: 'Robots remain narrow specialists, lacking the world models needed to generalize across real tasks.',
    solution: 'Researches SLAM, uncertainty, simulation and learning-from-demonstration toward generalist embodied AI.',
    aiDomains: ['robotics', 'reinforcement-learning', 'computer-vision', 'research'],
    industries: ['research', 'robotics'],
    founded: 2018,
    headcount: '11-50',
    funding: { investors: ['CIFAR', 'NSERC'] },
    notable: 'Led by Liam Paull (CIFAR AI Chair, ex-MIT CSAIL); creator of the Duckietown robotics platform.',
    status: 'active',
    website: 'https://montrealrobotics.ca/',
    sources: ['https://montrealrobotics.ca/', 'https://mila.quebec/en/directory/liam-paull'],
  },

  // ── Big-tech AI labs ───────────────────────────────────────────────────────
  {
    id: 'microsoft-research-montreal',
    name: 'Microsoft Research Montreal',
    aka: 'ex-Maluuba',
    type: 'big-tech-lab',
    lat: 45.53052,
    lng: -73.61348,
    address: '6795 Rue Marconi, Montréal, QC H2S 3J9',
    neighborhood: 'Mile-Ex',
    oneLiner: 'Fundamental AI lab teaching machines to read, reason and communicate; born from the 2017 Maluuba acquisition.',
    problem: 'Machines struggle to read, reason over and communicate in natural language the way humans do.',
    solution: 'Fundamental research on language understanding, reinforcement learning and machine reading.',
    aiDomains: ['NLP', 'reinforcement-learning', 'LLM', 'research'],
    industries: ['enterprise', 'research'],
    founded: 2017,
    headcount: '51-200',
    hiring: true,
    notable: "Created from Microsoft's 2017 acquisition of Maluuba, with Yoshua Bengio advising.",
    status: 'active',
    website: 'https://www.microsoft.com/en-us/research/lab/microsoft-research-montreal/',
    sources: ['https://www.microsoft.com/en-us/research/lab/microsoft-research-montreal/', 'https://blogs.microsoft.com/blog/2017/01/13/microsoft-acquires-deep-learning-startup-maluuba-ai-pioneer-yoshua-bengio-advisory-role/'],
  },
  {
    id: 'meta-fair-montreal',
    name: 'Meta FAIR Montreal',
    aka: 'Facebook AI Research',
    type: 'big-tech-lab',
    lat: 45.52972,
    lng: -73.61432,
    neighborhood: 'Mile-Ex',
    oneLiner: "Meta's Fundamental AI Research lab pursuing open, long-horizon AI research.",
    problem: 'Advancing AI to benefit everyone needs open, long-horizon research rather than purely product-driven work.',
    solution: 'Conducts and openly publishes research in reinforcement learning, representation learning and dialog.',
    aiDomains: ['reinforcement-learning', 'NLP', 'research', 'computer-vision', 'generative-ai'],
    industries: ['research'],
    founded: 2017,
    headcount: '51-200',
    hiring: true,
    notable: 'Founded in 2017 under Joëlle Pineau with $7M committed to the Canadian AI ecosystem.',
    status: 'active',
    website: 'https://ai.meta.com/research/',
    sources: ['https://about.fb.com/news/2017/09/fair-montreal/', 'https://about.fb.com/news/2022/09/five-years-of-ai-breakthroughs-from-metas-montreal-research-lab/'],
  },
  {
    id: 'google-deepmind-montreal',
    name: 'Google DeepMind Montreal',
    aka: 'ex-Google Brain Montreal',
    type: 'big-tech-lab',
    lat: 45.50112,
    lng: -73.55672,
    address: '425 Avenue Viger Ouest, Montréal, QC',
    neighborhood: 'Old Montreal',
    oneLiner: "Google DeepMind's Montreal lab for fundamental deep-learning research, established 2016 under Hugo Larochelle.",
    problem: 'Pushing the ML frontier needs deep fundamental research embedded in Montreal\'s deep-learning ecosystem.',
    solution: 'Fundamental deep-learning research in collaboration with the broader DeepMind team and Mila.',
    aiDomains: ['research', 'reinforcement-learning', 'generative-ai', 'LLM', 'computer-vision'],
    industries: ['research'],
    founded: 2016,
    headcount: '11-50',
    hiring: true,
    notable: 'Led by Hugo Larochelle; formerly Google Brain Montreal, now part of Google DeepMind.',
    status: 'active',
    website: 'https://deepmind.google/',
    sources: ['https://research.google/people/hugo-larochelle/', 'https://blog.google/inside-google/company-announcements/googles-new-viger-office-is-an-homage-to-montreal/'],
  },
  {
    id: 'samsung-ai-montreal',
    name: 'Samsung AI Center Montreal',
    aka: 'SAIT AI Lab Montreal',
    type: 'big-tech-lab',
    lat: 45.5048,
    lng: -73.576,
    neighborhood: 'Downtown',
    oneLiner: "Samsung's Montreal AI center for network intelligence, robotics and multimodal ML.",
    problem: 'Next-gen devices and networks need on-device and network AI that works reliably in the physical world.',
    solution: "Research in 'AI for 5G' network intelligence, robotics and machine learning, led by Gregory Dudek.",
    aiDomains: ['robotics', 'reinforcement-learning', 'ml-platform', 'research', 'computer-vision'],
    industries: ['consumer-electronics', 'telecommunications', 'robotics'],
    founded: 2018,
    notable: 'Led by McGill robotics professor Gregory Dudek; a separate SAIT lab also operates inside Mila.',
    status: 'active',
    website: 'https://research.samsung.com/aicenter_montreal',
    sources: ['https://research.samsung.com/aicenter_montreal', 'https://news.samsung.com/ca/samsung-ai-center-montreal-opens-a-modern-lab-to-develop-wireless-and-robotics-technologies'],
  },
  {
    id: 'borealis-ai',
    name: 'RBC Borealis',
    aka: 'Borealis AI',
    type: 'big-tech-lab',
    lat: 45.5308,
    lng: -73.6132,
    neighborhood: 'Mile-Ex',
    oneLiner: "RBC's AI research institute, with a Montreal lab focused on AI for finance and NLP.",
    problem: 'Banking needs trustworthy, state-of-the-art ML to model risk, language and customer needs.',
    solution: 'Develops NLP and ML research applied to finance, working closely with Mila.',
    aiDomains: ['NLP', 'LLM', 'forecasting', 'research', 'ml-platform'],
    industries: ['finance', 'fintech'],
    founded: 2018,
    notable: 'Backed by RBC; Montreal lab focuses on NLP with McGill professor Jackie Cheung advising.',
    status: 'active',
    website: 'https://rbcborealis.com/',
    sources: ['https://rbcborealis.com/news/rbc-borealis-open-new-artificial-intelligence-lab-montreal-mcgill-professor-jackie-cheung-act-academi/', 'https://betakit.com/borealis-ai-opening-montreal-lab-with-jackie-cheung-as-academic-advisor/'],
  },
  {
    id: 'servicenow-research',
    name: 'ServiceNow Research',
    aka: 'ex-Element AI',
    type: 'big-tech-lab',
    lat: 45.5292,
    lng: -73.6148,
    address: '6650 Rue Saint-Urbain, Suite 500, Montréal, QC H2S 3G9',
    neighborhood: 'Mile-Ex',
    oneLiner: "ServiceNow's AI research lab built on the former Element AI team, advancing enterprise LLMs and agents.",
    problem: 'Enterprises need AI agents that can learn, reason and act across complex workflows.',
    solution: 'Builds adaptive agentic systems, multimodal models and RL for agentic learning to power enterprise intelligence.',
    aiDomains: ['LLM', 'NLP', 'generative-ai', 'reinforcement-learning', 'research', 'ml-platform'],
    industries: ['enterprise'],
    founded: 2020,
    hiring: true,
    notable: "Created from ServiceNow's 2020 acquisition of Montreal's Element AI; partners with Nvidia on enterprise LLMs.",
    status: 'active',
    website: 'https://www.servicenow.com/research/',
    sources: ['https://www.servicenow.com/research/', 'https://en.wikipedia.org/wiki/Element_AI'],
  },
  {
    id: 'huawei-noahs-ark',
    name: "Huawei Noah's Ark Lab Montreal",
    aka: "Noah's Ark Lab Canada",
    type: 'big-tech-lab',
    lat: 45.5008,
    lng: -73.5692,
    neighborhood: 'Downtown',
    oneLiner: "The Montreal arm of Huawei's Noah's Ark Lab, researching NLP, speech, vision and data mining.",
    problem: 'Telecom and consumer products need advances in language understanding, vision and large-scale data analysis.',
    solution: 'Works on speech, vision, NLP and data mining, partnering with McGill, UdeM and Mila.',
    aiDomains: ['NLP', 'speech', 'computer-vision', 'recommendation', 'research'],
    industries: ['telecommunications', 'consumer-electronics'],
    founded: 2018,
    notable: "Part of Huawei's global Noah's Ark Lab network; directed locally by Yanhui Geng.",
    status: 'active',
    website: 'https://www.noahlab.com.hk/en',
    sources: ['https://www.noahlab.com.hk/en', 'https://github.com/huawei-noah'],
  },
  {
    id: 'cohere-montreal',
    name: 'Cohere Montreal',
    type: 'scaleup',
    lat: 45.5296,
    lng: -73.6156,
    address: '6650 Rue Saint-Urbain, Montréal (at Mila)',
    neighborhood: 'Mile-Ex',
    oneLiner: 'Enterprise LLM company (HQ Toronto) that opened a Montreal office inside Mila in 2025.',
    problem: 'Enterprises and governments need secure, private LLMs tailored to their data and sovereignty needs.',
    solution: 'Builds enterprise LLMs and agentic AI tools, with Montreal strengthening secure, private LLM development.',
    aiDomains: ['LLM', 'NLP', 'generative-ai', 'ml-platform', 'research'],
    industries: ['enterprise'],
    founded: 2019,
    headcount: '400+ (≈20 in Montreal at launch)',
    funding: { totalRaised: '~US$1.6B', lastRound: 'US$500M', lastRoundDate: '2025-08', investors: ['Radical Ventures', 'Inovia Capital', 'Nvidia', 'AMD Ventures', 'PSP Investments'] },
    hiring: true,
    notable: 'Opened at Mila in July 2025 planning to triple local headcount; raised US$500M at a ~US$7B valuation. Hired ex-Meta AI lead Joelle Pineau.',
    status: 'active',
    website: 'https://cohere.com/',
    sources: ['https://mila.quebec/en/news/cohere-partners-with-mila-and-opens-montreal-office', 'https://cohere.com/blog/montreal-office'],
  },
  {
    id: 'ericsson-gaia',
    name: 'Ericsson GAIA Montreal',
    aka: 'Global AI Accelerator',
    type: 'big-tech-lab',
    lat: 45.5058,
    lng: -73.6692,
    address: '8275 Route Transcanadienne, Saint-Laurent, QC H4S 0B6',
    neighborhood: 'Saint-Laurent',
    oneLiner: "Ericsson's global AI innovation hub applying AI to telecom networks and 5G.",
    problem: 'Mobile networks are too complex to optimize and operate manually at global scale.',
    solution: 'Develops AI/ML to automate, optimize and add intelligence to telecom networks.',
    aiDomains: ['ml-platform', 'forecasting', 'research', 'reinforcement-learning'],
    industries: ['telecommunications', 'networking'],
    founded: 2019,
    notable: 'Launched May 2019; partners with Concordia and other local universities.',
    status: 'active',
    website: 'https://www.ericsson.com/',
    sources: ['https://www.rcrwireless.com/20190507/internet-of-things/ericsson-opens-ai-accelerator-hub-montreal', 'https://www.montrealinternational.com/en/news/ericsson-devoile-son-accelerateur-dintelligence-artificielle-mondial-a-montreal/'],
  },
  {
    id: 'thales-cortaix',
    name: 'Thales cortAIx',
    type: 'big-tech-lab',
    lat: 45.5304,
    lng: -73.6164,
    address: '6650 Rue Saint-Urbain, Montréal',
    neighborhood: 'Mile-Ex',
    oneLiner: "Thales's AI Centre of Excellence building safe, trustworthy AI for critical systems.",
    problem: 'Mission-critical sectors like defense, aerospace and transport need AI that is safe, explainable and ethical.',
    solution: 'Develops trustworthy and explainable AI for critical systems, with Mila and IVADO.',
    aiDomains: ['research', 'computer-vision', 'ml-platform', 'NLP'],
    industries: ['aerospace', 'defense', 'transportation'],
    founded: 2017,
    notable: "Announced 2017 as Thales's global AI hub, co-located in the Mila ecosystem.",
    status: 'active',
    website: 'https://www.thalesgroup.com/en/countries/americas/canada',
    sources: ['https://www.thalesgroup.com/en/worldwide/group/press-release/thales-selects-canada-new-global-hub-boost-artificial-intelligence', 'https://www.montrealinternational.com/en/news/thales-picks-montreal-for-new-artificial-intelligence-global-hub/'],
  },

  // ── Scaleups ───────────────────────────────────────────────────────────────
  {
    id: 'coveo',
    name: 'Coveo',
    type: 'scaleup',
    lat: 45.4964,
    lng: -73.5711,
    address: '1100 Av des Canadiens-de-Montréal, Suite 401, Montréal, QC H3B 2S2',
    neighborhood: 'Downtown',
    oneLiner: 'AI relevance platform delivering enterprise search, recommendations and generative AI.',
    problem: 'Enterprises struggle to surface relevant content and products across fragmented digital experiences.',
    solution: 'A SaaS relevance platform unifying search, personalization and generative AI at scale.',
    aiDomains: ['NLP', 'recommendation', 'generative-ai', 'LLM', 'ml-platform'],
    industries: ['enterprise', 'retail', 'customer-service'],
    founded: 2005,
    headcount: '~800',
    funding: { totalRaised: '~$358M', lastRound: 'IPO', lastRoundDate: '2021-11', investors: ['OMERS', 'Evergreen Coast Capital', 'Salesforce Ventures'] },
    hiring: true,
    notable: 'Publicly traded (TSX: CVO); hit a US$1B+ valuation before its 2021 IPO.',
    status: 'public (TSX: CVO)',
    website: 'https://www.coveo.com',
    sources: ['https://en.wikipedia.org/wiki/Coveo', 'https://www.crunchbase.com/organization/coveo'],
  },
  {
    id: 'hopper',
    name: 'Hopper',
    type: 'scaleup',
    lat: 45.4981,
    lng: -73.5725,
    address: '1170 Rue Peel, Montréal, QC',
    neighborhood: 'Downtown',
    oneLiner: 'AI-powered travel app that predicts flight and hotel prices and sells travel fintech products.',
    problem: 'Travelers face volatile, opaque pricing and lack tools to know when and what to book.',
    solution: 'A mobile app using ML to forecast prices, plus fintech features like price freeze and cancel-for-any-reason.',
    aiDomains: ['forecasting', 'recommendation', 'ml-platform'],
    industries: ['travel', 'fintech'],
    founded: 2007,
    headcount: '~1,000',
    funding: { totalRaised: '~$740M+', lastRound: 'Series G', lastRoundDate: '2022-11', investors: ['Capital One', 'Goldman Sachs', 'Inovia Capital', 'WestCap'] },
    hiring: true,
    notable: 'Valued above US$5B; one of Canada\'s most-funded private tech companies via its HTS B2B arm.',
    status: 'active',
    website: 'https://www.hopper.com',
    sources: ['https://en.wikipedia.org/wiki/Hopper_(company)', 'https://www.crunchbase.com/organization/hopper'],
  },
  {
    id: 'botpress',
    name: 'Botpress',
    type: 'scaleup',
    lat: 45.5238,
    lng: -73.5968,
    neighborhood: 'Mile-End',
    oneLiner: 'LLM-powered platform for building, deploying and managing AI agents and chatbots in production.',
    problem: 'Companies need production-grade AI agents but lack the infrastructure and tooling to build them.',
    solution: 'A developer platform with the infrastructure, integrations and tooling to ship LLM-driven agents.',
    aiDomains: ['LLM', 'NLP', 'generative-ai', 'ml-platform'],
    industries: ['developer-tools', 'enterprise'],
    founded: 2017,
    headcount: '~120',
    funding: { totalRaised: '~US$45M', lastRound: 'Series B', lastRoundDate: '2025', investors: ['Framework Venture Partners', 'Inovia Capital', 'HubSpot Ventures'] },
    hiring: true,
    notable: 'Open-source roots with a large developer community; raised a US$25M Series B in 2025.',
    status: 'active',
    website: 'https://botpress.com',
    sources: ['https://betakit.com/botpress-closes-34-million-cad-series-b-to-help-companies-build-and-deploy-ai-agents/', 'https://botpress.com/company/about'],
  },
  {
    id: 'lightspeed',
    name: 'Lightspeed Commerce',
    type: 'scaleup',
    lat: 45.5101,
    lng: -73.5544,
    address: '700 Rue Saint-Antoine E, Montréal, QC',
    neighborhood: 'Old Montreal',
    oneLiner: 'Cloud commerce platform with AI-driven tools for retailers and restaurants worldwide.',
    problem: 'Small and mid-sized merchants need unified, modern software to run and grow complex operations.',
    solution: 'A one-stop cloud platform combining POS, payments, inventory and AI-powered insights.',
    aiDomains: ['recommendation', 'forecasting', 'ml-platform', 'generative-ai'],
    industries: ['retail', 'hospitality', 'fintech'],
    founded: 2005,
    headcount: '~3,300',
    funding: { totalRaised: '~$373M (pre-IPO)', lastRound: 'IPO', lastRoundDate: '2019-03', investors: ['Accel', 'iNovia Capital', 'CDPQ'] },
    hiring: true,
    notable: 'Dual-listed on NYSE and TSX (LSPD); a multi-billion-dollar global commerce company founded in Montreal.',
    status: 'public (NYSE/TSX: LSPD)',
    website: 'https://www.lightspeedhq.com',
    sources: ['https://en.wikipedia.org/wiki/Lightspeed_Commerce', 'https://www.crunchbase.com/organization/lightspeed-retail'],
  },
  {
    id: 'alayacare',
    name: 'AlayaCare',
    type: 'scaleup',
    lat: 45.5222,
    lng: -73.5952,
    neighborhood: 'Mile-End',
    oneLiner: 'End-to-end home-care software platform enhanced with predictive AI.',
    problem: 'Home-care agencies rely on fragmented manual processes for scheduling, care planning and outcomes.',
    solution: 'A cloud platform managing the full client lifecycle with predictive models for scheduling and care.',
    aiDomains: ['forecasting', 'ml-platform', 'LLM'],
    industries: ['healthcare', 'home-care'],
    founded: 2014,
    headcount: '~500+',
    funding: { totalRaised: '$225M+ CAD', lastRound: 'Series D', lastRoundDate: '2021', investors: ['Generation Investment Management', 'Inovia Capital', 'CDPQ'] },
    hiring: true,
    notable: 'Raised a C$225M Series D; launched a 2024 project bringing predictive models and LLMs to home care.',
    status: 'active',
    website: 'https://alayacare.com',
    sources: ['https://www.lacaisse.com/en/news/pressreleases/alayacare-raises-225-million-accelerate-digital-transformation-home-health-care', 'https://www.canhealth.com/2024/03/06/alayacare-in-3-2m-project-to-create-ai-for-home-care/'],
  },
  {
    id: 'dialogue',
    name: 'Dialogue',
    aka: 'Dialogue Health Technologies',
    type: 'scaleup',
    lat: 45.4996,
    lng: -73.5744,
    address: '2200 Rue Stanley, Montréal, QC H3A 3G3',
    neighborhood: 'Downtown',
    oneLiner: 'Virtual healthcare and wellness platform using AI-assisted triage to connect members with care.',
    problem: 'Employees and members lack fast, affordable, on-demand access to healthcare and mental wellness.',
    solution: 'A digital health platform with NLP-driven triage and human-in-the-loop clinical workflows.',
    aiDomains: ['NLP', 'ml-platform'],
    industries: ['healthcare', 'telehealth'],
    founded: 2016,
    headcount: '~870',
    funding: { lastRound: 'Acquired by Sun Life (C$365M)', lastRoundDate: '2023-10', investors: ['Sun Life Financial', 'CDPQ', 'National Bank'] },
    hiring: true,
    notable: 'Acquired by Sun Life for ~C$365M in 2023; serves ~2.8M members across 50,000 organizations.',
    status: 'acquired by Sun Life (2023)',
    website: 'https://www.dialogue.co',
    sources: ['https://www.sunlife.com/en/newsroom/news-releases/announcement/sun-life-completes-the-acquisition-of-dialogue-canadas-premier-health-and-wellness-virtual-care-platform/123792/', 'https://www.dialogue.co/en/about'],
  },
  {
    id: 'sportlogiq',
    name: 'Sportlogiq',
    type: 'scaleup',
    lat: 45.523,
    lng: -73.5964,
    neighborhood: 'Mile-End',
    oneLiner: 'Computer-vision sports analytics extracted from broadcast footage for teams and broadcasters.',
    problem: 'Teams and broadcasters lack granular, automated tracking and context from game video.',
    solution: 'CV and ML models that track players and recognize events on existing broadcast feeds.',
    aiDomains: ['computer-vision', 'ml-platform', 'research'],
    industries: ['sports', 'media'],
    founded: 2014,
    headcount: '~160',
    funding: { totalRaised: '~$27.2M', lastRound: 'Series A', lastRoundDate: '2017-08', investors: ['Rho Canada Ventures', 'Mark Cuban', 'TandemLaunch'] },
    notable: 'Founded by Olympian Craig Buntin and CV PhD Mehrsan Javan; acquired by Teamworks in January 2026.',
    status: 'acquired by Teamworks (2026)',
    website: 'https://www.sportlogiq.com',
    sources: ['https://www.crunchbase.com/organization/sportlogiq', 'https://www.sportlogiq.com/about-us/'],
  },
  {
    id: 'flinks',
    name: 'Flinks',
    type: 'scaleup',
    lat: 45.4798,
    lng: -73.5862,
    address: '1001 Rue Lenoir, Suite A-114, Montréal, QC H4C 2Z6',
    neighborhood: 'Saint-Henri',
    oneLiner: "Financial-data platform connecting apps to consumers' bank accounts with ML enrichment.",
    problem: 'Fintechs struggle to securely access and make sense of fragmented banking data.',
    solution: 'Open-banking connectivity plus ML-driven enrichment and analytics on financial transactions.',
    aiDomains: ['ml-platform', 'forecasting'],
    industries: ['fintech'],
    founded: 2016,
    headcount: '100-250',
    funding: { totalRaised: '$122M+ CAD', lastRound: 'National Bank majority stake (C$103M)', lastRoundDate: '2021-08', investors: ['National Bank of Canada', 'Luge Capital', 'Panache Ventures'] },
    notable: 'Majority owned by National Bank of Canada after a C$103M investment.',
    status: 'majority-owned by National Bank',
    website: 'https://flinks.com',
    sources: ['https://betakit.com/flinks-ceo-says-montreal-fintech-has-grand-plans-as-national-bank-takes-majority-stake/', 'https://www.prnewswire.com/news-releases/national-bank-of-canada-invests-103m-in-flinks-including-30m-in-growth-capital-301363011.html'],
  },
  {
    id: 'nesto',
    name: 'Nesto',
    type: 'scaleup',
    lat: 45.5006,
    lng: -73.5692,
    address: '2200 Stanley Street, Montréal, QC H3A 1R6',
    neighborhood: 'Downtown',
    oneLiner: 'Digital mortgage platform using data and ML to match Canadians with the best rates online.',
    problem: 'Getting a mortgage in Canada is slow, opaque and dependent on commission-driven brokers.',
    solution: 'A fully online, transparent mortgage experience with algorithmic rate-matching and a lending platform.',
    aiDomains: ['ml-platform', 'forecasting'],
    industries: ['fintech', 'mortgage', 'real-estate'],
    founded: 2018,
    headcount: '500-1000',
    funding: { totalRaised: '$130M+ CAD', lastRound: 'Series C (~$80M CAD)', lastRoundDate: '2022-12', investors: ['Power Corp / Portage', 'Diagram Ventures', 'BMO'] },
    notable: "Acquired CMLS's Canadian mortgage operations to become a major digital lender.",
    status: 'active',
    website: 'https://www.nesto.ca',
    sources: ['https://en.wikipedia.org/wiki/Nesto_(company)', 'https://www.crunchbase.com/organization/nesto'],
  },
  {
    id: 'nuvei',
    name: 'Nuvei',
    type: 'scaleup',
    lat: 45.4962,
    lng: -73.5718,
    address: '1100 Boul René-Lévesque Ouest, Montréal, QC H3B 4N4',
    neighborhood: 'Downtown',
    oneLiner: 'Global payments technology company with ML-based fraud prevention.',
    problem: 'Merchants must accept payments globally across many methods while minimizing fraud and false declines.',
    solution: 'A single payments platform spanning 200+ markets with real-time ML fraud detection.',
    aiDomains: ['ml-platform'],
    industries: ['fintech', 'payments'],
    founded: 2003,
    headcount: '1000+',
    funding: { lastRound: 'Taken private by Advent (~$6.3B)', lastRoundDate: '2024-04', investors: ['Advent International', 'Novacap', 'CDPQ'] },
    notable: 'Formerly Nasdaq/TSX listed (NVEI); taken private by Advent International in 2024.',
    status: 'private (Advent, 2024)',
    website: 'https://www.nuvei.com',
    sources: ['https://www.nuvei.com/posts/nuvei-launches-groundbreaking-machine-learning-solution-to-boost-risk-management', 'https://pitchbook.com/profiles/company/64245-70'],
  },
  {
    id: 'busbud',
    name: 'Busbud',
    type: 'scaleup',
    lat: 45.5238,
    lng: -73.5968,
    address: '5425 Avenue Casgrain, Suite 901, Montréal, QC H2T 1X6',
    neighborhood: 'Mile-End',
    oneLiner: 'Intercity bus marketplace to search, compare and book bus tickets worldwide.',
    problem: 'Booking intercity bus travel is fragmented across thousands of carriers with no unified interface.',
    solution: 'Aggregates global bus inventory into one marketplace, using data and ML to rank and price routes.',
    aiDomains: ['recommendation', 'forecasting'],
    industries: ['travel', 'mobility'],
    founded: 2011,
    headcount: '51-100',
    funding: { totalRaised: '$71.6M', investors: ['Vista Credit', 'Amadeus Ventures', 'iNovia Capital'] },
    notable: 'One of the largest global intercity bus booking marketplaces across the Americas and Europe.',
    status: 'active',
    website: 'https://www.busbud.com',
    sources: ['https://www.crunchbase.com/organization/busbud', 'https://pitchbook.com/profiles/company/57226-15'],
  },
  {
    id: 'mistplay',
    name: 'Mistplay',
    type: 'scaleup',
    lat: 45.5018,
    lng: -73.5576,
    address: '481 Avenue Viger Ouest, Suite 300, Montréal, QC H2Z 1G6',
    neighborhood: 'Old Montreal',
    oneLiner: 'Mobile gaming loyalty platform rewarding players for discovering and playing games.',
    problem: 'Mobile game publishers struggle to acquire and retain engaged, high-value players cost-effectively.',
    solution: 'ML-driven game recommendations plus a rewards layer that matches players to games.',
    aiDomains: ['recommendation', 'ml-platform'],
    industries: ['gaming', 'adtech'],
    founded: 2015,
    headcount: '201-500',
    funding: { lastRound: 'Majority investment by GrowthCurve Capital', lastRoundDate: '2021', investors: ['GrowthCurve Capital', 'L Catterton'] },
    notable: "Acquired Mobivity's loyalty platform to expand gamified rewards for brands.",
    status: 'active',
    website: 'https://www.mistplay.com',
    sources: ['https://www.crunchbase.com/organization/mistplay', 'https://www.growthcurvecapital.com/post/mistplay-majority-investment-by-growthcurve-capital'],
  },

  // ── Startups ───────────────────────────────────────────────────────────────
  {
    id: 'local-logic',
    name: 'Local Logic',
    type: 'startup',
    lat: 45.5246,
    lng: -73.5976,
    address: '5605 Avenue de Gaspé, Suite 304, Montréal, QC',
    neighborhood: 'Mile-End',
    oneLiner: 'Location-intelligence platform quantifying the lifestyle of any place using geospatial AI.',
    problem: 'Real-estate decisions still rely on intuition rather than objective data about what a place is like.',
    solution: 'Builds digital twins of cities from 85B+ data points to power predictive location analytics.',
    aiDomains: ['ml-platform', 'forecasting', 'research'],
    industries: ['proptech', 'real-estate', 'geospatial'],
    founded: 2015,
    headcount: '51-100',
    funding: { totalRaised: '$25M+ CAD', lastRound: 'Series B (C$17.5M)', lastRoundDate: '2023-06', investors: ['GroundBreak Ventures', 'Investissement Québec', 'Desjardins Capital'] },
    notable: 'Founded by McGill urban-planning grads; ~100 enterprise customers reaching 15M+ users monthly.',
    status: 'active',
    website: 'https://www.locallogic.co',
    sources: ['https://betakit.com/local-logic-raises-17-5-million-cad-to-develop-ai-decision-making-for-location-based-risks-and-opportunities-in-real-estate/', 'https://craft.co/local-logic/locations'],
  },
  {
    id: 'keatext',
    name: 'Keatext',
    type: 'applied-ai',
    lat: 45.5008,
    lng: -73.5692,
    neighborhood: 'Downtown',
    oneLiner: 'AI text-analytics platform turning unstructured customer feedback into recommended actions.',
    problem: 'Businesses collect huge volumes of unstructured feedback but cannot easily extract meaning from it.',
    solution: 'Deep-learning NLP and generative AI that consolidate feedback and surface themes and actions.',
    aiDomains: ['NLP', 'LLM', 'generative-ai'],
    industries: ['customer-experience', 'analytics'],
    founded: 2010,
    headcount: '11-50',
    funding: { totalRaised: '~$3.4M', lastRound: 'Seed', investors: ['Anges Québec', 'Real Ventures', 'Desjardins'] },
    notable: 'Founded by computational-linguistics PhD Narjès Boufaden.',
    status: 'active',
    website: 'https://www.keatext.ai',
    sources: ['https://www.keatext.ai/en/our-team-and-history/', 'https://www.crunchbase.com/organization/keatext'],
  },
  {
    id: 'deeplite',
    name: 'Deeplite',
    type: 'startup',
    lat: 45.5008,
    lng: -73.57,
    neighborhood: 'Downtown',
    oneLiner: 'Software that automatically compresses deep neural networks to run smaller and faster on edge devices.',
    problem: 'Deep neural nets are too large and compute-heavy to run efficiently on edge hardware.',
    solution: 'The Neutrino platform automatically shrinks and accelerates AI models for low-power edge deployment.',
    aiDomains: ['edge-ai', 'computer-vision', 'ml-platform'],
    industries: ['hardware', 'automotive'],
    founded: 2018,
    headcount: '11-50',
    funding: { totalRaised: '$6M (seed)', lastRound: 'Seed', lastRoundDate: '2021-04', investors: ['PJC', 'Innospark Ventures', 'BDC Capital'] },
    notable: 'Spun out of TandemLaunch; acquired by STMicroelectronics in April 2025.',
    status: 'acquired by STMicroelectronics (2025)',
    website: 'https://www.deeplite.ai/',
    sources: ['https://techcrunch.com/2021/04/13/deeplite-raises-6m-seed-to-deploy-ml-on-edge-with-fewer-compute-resources/', 'https://www.crunchbase.com/organization/deeplite'],
  },
  {
    id: 'brainbox-ai',
    name: 'BrainBox AI',
    type: 'scaleup',
    lat: 45.5043,
    lng: -73.5705,
    address: '2001 Boulevard Robert-Bourassa, Montréal, QC',
    neighborhood: 'Downtown',
    oneLiner: 'Autonomous AI that optimizes commercial-building HVAC to cut energy use and emissions.',
    problem: 'Commercial buildings waste energy because HVAC runs reactively rather than predictively.',
    solution: 'The ARIA generative-AI platform predicts energy needs and autonomously controls HVAC.',
    aiDomains: ['forecasting', 'ml-platform', 'generative-ai'],
    industries: ['climate', 'real-estate', 'energy'],
    founded: 2017,
    headcount: '190+',
    funding: { totalRaised: '$80M+ USD (est.)', lastRound: 'Series A', lastRoundDate: '2021-11', investors: ['ABB', 'Trane Technologies'] },
    notable: "ARIA named to TIME's Best Inventions of 2024; deployed across 14,000+ buildings.",
    status: 'acquired by Trane (2025)',
    website: 'https://brainboxai.com/',
    sources: ['https://brainboxai.com/en/newsroom/trane-technologies-to-acquire-brainbox-ai', 'https://investors.tranetechnologies.com/news-and-events/news-releases/news-release-details/2025/Trane-Technologies-Completes-Acquisition-of-BrainBox-AI/default.aspx'],
  },
  {
    id: 'fluent-ai',
    name: 'Fluent.ai',
    type: 'startup',
    lat: 45.4992,
    lng: -73.5692,
    neighborhood: 'Downtown',
    oneLiner: 'On-device speech-to-intent engine that turns voice commands into actions without the cloud.',
    problem: 'Voice assistants depend on the cloud and transcription, failing offline and with accents or noise.',
    solution: 'A patented offline, embedded speech-to-intent engine mapping speech directly to actions in any language.',
    aiDomains: ['speech', 'edge-ai', 'NLP'],
    industries: ['consumer-electronics', 'automotive', 'iot'],
    founded: 2015,
    funding: { totalRaised: '~$5.3M (est.)', lastRound: 'Seed', investors: ['Desjardins', 'BDC Capital', '500 Startups'] },
    notable: 'Spun out of TandemLaunch; CTO Vikrant Tomar holds a McGill PhD in speech recognition.',
    status: 'active',
    website: 'https://fluent.ai/',
    sources: ['https://fluent.ai/about/', 'https://www.crunchbase.com/organization/fluent-ai'],
  },
  {
    id: 'korbit',
    name: 'Korbit',
    aka: 'Korbit AI',
    type: 'startup',
    lat: 45.5308,
    lng: -73.6148,
    neighborhood: 'Mile-Ex',
    oneLiner: 'AI-powered intelligent tutors that teach STEM through interactive, personalized exercises.',
    problem: 'High-quality personalized education is expensive and inaccessible to most students.',
    solution: 'An AI tutor using ML, NLP and RL to deliver interactive one-on-one tutoring at scale.',
    aiDomains: ['NLP', 'reinforcement-learning', 'LLM'],
    industries: ['education'],
    founded: 2018,
    funding: { totalRaised: '$2.65M CAD (seed)', lastRound: 'Seed', lastRoundDate: '2020-05', investors: ['Khosla Ventures'] },
    notable: 'Mila spin-off backed by Yoshua Bengio; advisors include Joelle Pineau and Aaron Courville.',
    status: 'active',
    website: 'https://www.korbit.ai/',
    sources: ['https://mila.quebec/en/news/korbit-a-startup-born-in-mila-raises-2-million-to-transform-education', 'https://betakit.com/korbit-raises-2-65-million-for-its-ai-tutoring-platform/'],
  },
  {
    id: 'waverly',
    name: 'Waverly',
    type: 'startup',
    lat: 45.5238,
    lng: -73.5968,
    neighborhood: 'Mile-End',
    oneLiner: 'AI content-discovery app curating online content from a user\'s stated interests, not engagement bait.',
    problem: 'Engagement- and ad-driven feeds surface sensational content rather than what users value.',
    solution: "A natural-language app that funnels content based on a personal 'manifesto' of likes and dislikes.",
    aiDomains: ['NLP', 'recommendation', 'LLM'],
    industries: ['media', 'consumer'],
    founded: 2020,
    funding: { totalRaised: '$1.25M CAD (pre-seed)', lastRound: 'Pre-seed', lastRoundDate: '2020-10', investors: ['Panache Ventures', 'FounderFuel'] },
    notable: 'Founded by Element AI co-founder Philippe Beaudoin, who joined Bengio\'s LawZero in 2025.',
    status: 'likely inactive',
    website: 'https://www.waverly.ai/',
    sources: ['https://betakit.com/element-ai-co-founder-launches-waverly-to-fix-the-internet-by-changing-the-way-people-consume-content/', 'https://lawzero.org/en/news/lawzero-appoints-philippe-beaudoin-senior-director-research'],
  },
  {
    id: 'c2ro',
    name: 'C2RO',
    aka: 'C2RO Cloud Robotics',
    type: 'startup',
    lat: 45.5,
    lng: -73.5684,
    neighborhood: 'Downtown',
    oneLiner: 'Privacy-aware AI video analytics turning existing retail cameras into computer-vision tools.',
    problem: 'Retailers need actionable analytics from in-store cameras while complying with privacy rules.',
    solution: 'An edge-cloud CV platform (ENTERA) that analyzes existing camera video while staying privacy-compliant.',
    aiDomains: ['computer-vision', 'edge-ai', 'ml-platform'],
    industries: ['retail', 'security'],
    founded: 2016,
    funding: { totalRaised: '~$3.66M (est.)', lastRound: 'Series A', lastRoundDate: '2019', investors: ['Fonds Innovexport', 'TandemLaunch'] },
    notable: 'Founded by Soodeh Farokhi; incubated at TandemLaunch.',
    status: 'active',
    website: 'https://www.c2ro.com/',
    sources: ['https://www.crunchbase.com/organization/c2ro', 'https://betakit.com/ai-and-robotics-enterprise-startup-c2ro-raises-2-25-million-series-a/'],
  },
  {
    id: 'apex',
    name: 'Apex',
    aka: 'Apex Research',
    type: 'startup',
    lat: 45.5292,
    lng: -73.6132,
    neighborhood: 'Mile-Ex',
    oneLiner: 'Large-scale AI-based supply-and-demand market simulators for decision-making.',
    problem: 'Decision-makers lack tools to realistically simulate complex market dynamics before acting.',
    solution: 'AI-driven simulators that model large-scale supply and demand to support better decisions.',
    aiDomains: ['reinforcement-learning', 'forecasting', 'research'],
    industries: ['finance', 'supply-chain'],
    founded: 2022,
    notable: 'Mila startup co-founded by Manuel de Verme and Simone Totaro; Mila Startup status in 2022.',
    status: 'active',
    sources: ['https://mila.quebec/en/news/four-new-companies-obtain-the-mila-startup-status', 'https://mila.quebec/en/industry/mila-entrepreneurship-lab'],
  },
  {
    id: 'aifred-health',
    name: 'Aifred Health',
    type: 'startup',
    lat: 45.4956,
    lng: -73.5782,
    address: '1250 Rue Guy, Suite 600, Montréal, QC H3H 2T4',
    neighborhood: 'Downtown',
    oneLiner: 'AI clinical decision support that helps clinicians choose depression treatments.',
    problem: 'Choosing an effective depression treatment is largely trial-and-error, leaving patients on poor therapies.',
    solution: 'A deep-learning tool predicting which treatments are most likely to work for an individual patient.',
    aiDomains: ['ml-platform', 'research'],
    industries: ['healthcare', 'mental-health'],
    founded: 2016,
    headcount: '~16',
    funding: { totalRaised: '~US$4.4M', investors: ['Anges Québec', 'MEDTEQ', 'BDC'] },
    notable: 'Won a 2024 Health Canada licence for its AI decision-support device for major depression.',
    status: 'active',
    website: 'https://www.aifredhealth.com/',
    sources: ['https://www.crunchbase.com/organization/aifred-health', 'https://www.prnewswire.com/news-releases/aifred-health-announces-health-canada-approval-for-the-sale-and-commercialization-of-its-ai-driven-clinical-decision-support-device-to-optimize-treatment-choice-in-major-depression-302249847.html'],
  },
  {
    id: 'optable',
    name: 'Optable',
    type: 'startup',
    lat: 45.5069,
    lng: -73.5672,
    address: '1435 Rue Saint-Alexandre, Suite 700, Montréal, QC H3A 2G4',
    neighborhood: 'Downtown',
    oneLiner: 'Data clean-room technology letting advertisers and publishers match audiences privately.',
    problem: 'Cookie deprecation and privacy rules make it hard to safely match and activate audience data.',
    solution: 'A privacy-preserving clean-room platform with ML-driven audience matching for secure collaboration.',
    aiDomains: ['ml-platform', 'recommendation'],
    industries: ['adtech', 'martech'],
    founded: 2020,
    headcount: '~40',
    funding: { totalRaised: '~US$43.6M', lastRound: 'Series A (US$20M)', lastRoundDate: '2023-04', investors: ['Telus Global Ventures', 'Hearst Ventures', 'Brightspark Ventures'] },
    hiring: true,
    notable: 'Founded by ex-AdGear founders (AdGear was acquired by Samsung in 2016).',
    status: 'active',
    website: 'https://www.optable.co/',
    sources: ['https://betakit.com/optable-raises-28-8-million-to-grow-data-management-solution-in-united-states/', 'https://www.adexchanger.com/investment/with-data-fragmentation-on-the-rise-clean-room-optable-secures-20m-series-a/'],
  },
  {
    id: 'phyla',
    name: 'Phyla',
    aka: 'Injoy',
    type: 'startup',
    lat: 45.4928,
    lng: -73.5592,
    neighborhood: 'Griffintown',
    oneLiner: 'Combines AI, microbiome testing and sensors to turn at-home gut data into health insights.',
    problem: 'People with chronic gut conditions lack tools to track symptoms and microbiome data from home.',
    solution: 'A health app plus a microbiome AI platform that analyzes at-home testing data for GI conditions.',
    aiDomains: ['ml-platform', 'research'],
    industries: ['healthcare', 'microbiome'],
    founded: 2020,
    notable: 'Incubated at Centech and CDL; rebranded from Phyla to Injoy. Focus is gut, not skin, health.',
    status: 'active',
    website: 'https://www.injoy.bio/',
    sources: ['https://centech.co/en/startups/phyla/', 'https://creativedestructionlab.com/companies/injoy/'],
  },
  {
    id: 'valence-labs',
    name: 'Valence Labs',
    aka: 'ex-Valence Discovery',
    type: 'startup',
    lat: 45.5308,
    lng: -73.6132,
    neighborhood: 'Mile-Ex',
    oneLiner: "Recursion's AI research engine for deep-learning drug discovery, based at Mila.",
    problem: 'Designing novel small-molecule drugs is slow and limited by sparse, noisy experimental data.',
    solution: 'Molecular ML — generative chemistry, AI structural biology and low-data learning — to design candidates.',
    aiDomains: ['generative-ai', 'ml-platform', 'research'],
    industries: ['drug-discovery', 'biotech'],
    founded: 2018,
    funding: { totalRaised: 'Acquired for ~US$47.5M', lastRound: 'Acquisition by Recursion', lastRoundDate: '2023-05', investors: ['Recursion Pharmaceuticals'] },
    notable: 'Acquired by Recursion in 2023; operates as a semi-autonomous AI research engine, advised by Bengio.',
    status: 'acquired by Recursion (2023)',
    website: 'https://www.valencelabs.com/',
    sources: ['https://betakit.com/american-biotech-recursion-acquires-two-canadian-ai-drug-discovery-companies-cyclica-and-valence/', 'https://www.valencelabs.com/'],
  },
  {
    id: 'dreamfold',
    name: 'Dreamfold',
    type: 'startup',
    lat: 45.5292,
    lng: -73.6148,
    neighborhood: 'Mile-Ex',
    oneLiner: 'Generative AI models such as FoldFlow for designing functional proteins.',
    problem: 'Designing novel proteins is computationally hard and existing models often fail in the lab.',
    solution: 'Generative flow-matching models (FoldFlow / FoldFlow-2) that generate biologically relevant proteins.',
    aiDomains: ['generative-ai', 'research'],
    industries: ['biotech', 'drug-discovery'],
    founded: 2021,
    funding: { lastRound: 'Seed', investors: ['IQ Capital', 'OpenOcean'] },
    notable: 'Founded by Mila researchers; created the FoldFlow family of SE(3) flow-matching protein models.',
    status: 'active',
    website: 'https://www.dreamfold.ai/',
    sources: ['https://www.openocean.vc/articles/portfolio-spotlight-dreamfold', 'https://www.iqcapital.vc/company/dreamfold'],
  },

  // ── Applied AI (verticals & consultancies) ─────────────────────────────────
  {
    id: 'ventus-therapeutics',
    name: 'Ventus Therapeutics',
    type: 'applied-ai',
    lat: 45.5058,
    lng: -73.6692,
    neighborhood: 'Saint-Laurent',
    oneLiner: 'ML-enabled computational chemistry platform discovering small-molecule drugs for hard targets.',
    problem: 'Many disease-driving proteins are deemed undruggable because their binding pockets are poorly understood.',
    solution: 'The ReSOLVE platform fuses AI/ML, structural biology and biophysics to design precise small molecules.',
    aiDomains: ['generative-ai', 'ml-platform', 'research'],
    industries: ['drug-discovery', 'biotech'],
    founded: 2019,
    funding: { totalRaised: '~US$290M+', lastRound: 'Series C (US$140M)', lastRoundDate: '2023', investors: ['SoftBank Vision Fund 2', 'RA Capital', 'a16z', 'GV'] },
    notable: 'Struck a US$700M+ collaboration with Novo Nordisk; clinical candidates VENT-03 and VENT-02. Mila partner.',
    status: 'clinical-stage',
    website: 'https://www.ventustx.com/',
    sources: ['https://www.biospace.com/article/releases/ventus-therapeutics-closes-140-million-series-c-financing/', 'https://mila.quebec/en/news/mila-partners-with-ventus-therapeutics-to-industrialize-rational-drug-discovery'],
  },
  {
    id: 'congruence-therapeutics',
    name: 'Congruence Therapeutics',
    type: 'applied-ai',
    lat: 45.5004,
    lng: -73.5696,
    neighborhood: 'Downtown',
    oneLiner: 'AI-driven platform designing small-molecule correctors for protein-misfolding diseases.',
    problem: 'Diseases from misfolded proteins are hard to treat because such proteins are dynamic and elusive.',
    solution: 'The Revenir platform integrates protein dynamics, biophysics and ML to design stabilizing molecules.',
    aiDomains: ['ml-platform', 'research'],
    industries: ['drug-discovery', 'biotech', 'rare-disease'],
    founded: 2021,
    funding: { totalRaised: '~US$168.5M', lastRound: 'US$39.5M', lastRoundDate: '2026-03', investors: ['OrbiMed', 'Amplitude Ventures', 'FSTQ', 'BDC Capital'] },
    notable: 'Founded by Clarissa Desjardins (Clementia, acquired by Ipsen); lead candidate CGX-926 in the clinic.',
    status: 'active',
    website: 'https://congruencetx.com/',
    sources: ['https://betakit.com/canadian-biotech-leader-clarissa-desjardins-secures-63-million-cad-for-congruence-therapeutics/', 'https://congruencetx.com/'],
  },
  {
    id: 'moov-ai',
    name: 'Moov AI',
    type: 'applied-ai',
    lat: 45.53008,
    lng: -73.61408,
    address: '358 Rue de Beaubien Ouest, Suite 500, Montréal, QC H2V 4S6',
    neighborhood: 'Mile-Ex',
    oneLiner: 'Applied-AI and generative-AI consultancy helping enterprises build and deploy AI solutions.',
    problem: 'Many companies struggle to turn data into value and adopt generative AI responsibly at scale.',
    solution: 'AI strategy consulting, generative-AI training and end-to-end predictive and generative AI builds.',
    aiDomains: ['generative-ai', 'ml-platform', 'forecasting', 'NLP'],
    industries: ['consulting', 'retail', 'manufacturing', 'finance'],
    founded: 2018,
    headcount: '60+',
    funding: { lastRound: 'Acquired by Publicis', lastRoundDate: '2025-03', investors: ['Publicis Groupe'] },
    notable: "Forbes' #1 Best Startup Employer in Canada (2024); acquired by Publicis Groupe in 2025.",
    status: 'acquired by Publicis (2025)',
    website: 'https://moov.ai/en',
    sources: ['https://moov.ai/en/blog/publicis-acquires-moov-ai-canadas-leading-ai-company', 'https://strategyonline.ca/2025/03/28/publicis-moov-ai/'],
  },
  {
    id: 'airudi',
    name: 'Airudi',
    type: 'applied-ai',
    lat: 45.5008,
    lng: -73.5568,
    neighborhood: 'Old Montreal',
    oneLiner: 'Applies AI to human resources, workforce management and occupational health & safety.',
    problem: 'Workforce planning, recruitment and OHS challenges are hard to predict and optimize manually.',
    solution: 'AI for workforce prediction and allocation, occupational health & safety, and recruitment.',
    aiDomains: ['forecasting', 'ml-platform', 'NLP'],
    industries: ['hr-tech', 'workforce'],
    founded: 2019,
    headcount: '~50',
    notable: 'Partnered with Mila to advance AI in HR; used by more than 5,000 companies.',
    status: 'active',
    website: 'https://airudi.com/en',
    sources: ['https://airudi.com/en', 'https://mila.quebec/en/news/airudi-and-mila-announce-partnership-to-propel-ai-in-human-resources-management'],
  },
  {
    id: 'hectiq-ai',
    name: 'Hectiq.AI',
    type: 'applied-ai',
    lat: 45.5238,
    lng: -73.5968,
    neighborhood: 'Mile-End',
    oneLiner: 'AI solutions partner that researches and builds bespoke deep-learning technologies for businesses.',
    problem: 'Businesses need custom deep-learning solutions but lack the in-house scientific expertise.',
    solution: 'A team of scientists builds bespoke AI spanning text analysis, machine vision and image processing.',
    aiDomains: ['research', 'computer-vision', 'NLP', 'ml-platform'],
    industries: ['consulting', 'manufacturing'],
    founded: 2018,
    funding: { investors: ['Mirego', 'Premier Tech'] },
    notable: "Joint venture with Mirego; built the AI image processing for Celestron's Origin smart telescope.",
    status: 'active',
    website: 'https://hectiq.ai/',
    sources: ['https://hectiq.ai/en/about', 'https://www.premiertech.com/news/hectiq-ai-strategic-partnership'],
  },
  {
    id: 'nuenergy-ai',
    name: 'NuEnergy.ai',
    type: 'startup',
    lat: 45.5016,
    lng: -73.5576,
    neighborhood: 'Old Montreal',
    oneLiner: 'AI-governance firm whose Machine Trust Platform measures and manages AI trustworthiness.',
    problem: 'Organizations deploying AI lack standard tools to measure and govern trust, bias and transparency.',
    solution: 'The Machine Trust Platform and patented Machine Trust Index measure and govern AI trustworthiness.',
    aiDomains: ['ml-platform'],
    industries: ['ai-governance', 'government', 'enterprise'],
    notable: 'Platform approved for use across all Government of Canada departments; piloted with the RCMP.',
    status: 'active',
    website: 'https://www.nuenergy.ai/',
    sources: ['https://www.nuenergy.ai/ai-trust-platform/', 'https://communitech.ca/technews/ottawa-expands-use-of-nuenergy.ai-trust-platform.html'],
  },

  // ── Incubators, funds & venture builders ───────────────────────────────────
  {
    id: 'scale-ai',
    name: 'Scale AI',
    aka: "Canada's AI Supply-Chains Cluster",
    type: 'incubator',
    lat: 45.53052,
    lng: -73.61452,
    address: '6795 Rue Marconi, Suite 200, Montréal, QC H2S 3J9',
    neighborhood: 'Mile-Ex',
    oneLiner: "Canada's AI Global Innovation Cluster, accelerating AI adoption across supply chains.",
    problem: 'Canadian value chains need to adopt AI and robotics to be more resilient and competitive.',
    solution: 'Co-funds and supports AI projects across retail, manufacturing, transport and ICT, building the ecosystem.',
    aiDomains: ['forecasting', 'ml-platform', 'robotics', 'research'],
    industries: ['supply-chain', 'retail', 'manufacturing', 'transportation'],
    founded: 2018,
    funding: { totalRaised: 'CAD 673M+ project portfolio', investors: ['Government of Canada', 'Government of Quebec'] },
    notable: 'Leads ALL IN, Canada\'s largest AI conference; a project portfolio exceeding CAD 673M.',
    status: 'active',
    website: 'https://www.scaleai.ca/',
    sources: ['https://www.scaleai.ca/about-us/', 'https://ised-isde.canada.ca/site/global-innovation-clusters/en/canadas-ai-powered-supply-chains-cluster-scale-ai'],
  },
  {
    id: 'diagram-ventures',
    name: 'Diagram Ventures',
    aka: 'Diagram',
    type: 'incubator',
    lat: 45.5018,
    lng: -73.5768,
    address: '2200 Rue Stanley, Maison Atholstan, Montréal, QC',
    neighborhood: 'Downtown',
    oneLiner: 'Venture builder conceiving and funding AI companies in fintech, insurance and health.',
    problem: 'Building category-defining fintech, insurance and health startups needs capital, ops and ecosystem access.',
    solution: 'Combines VC investment, hands-on operational support and a partner ecosystem to co-create companies.',
    aiDomains: ['ml-platform', 'generative-ai'],
    industries: ['fintech', 'insurance', 'health'],
    founded: 2016,
    funding: { totalRaised: 'US$200M+ across 3 funds', lastRound: 'US$100M fund', investors: ['Power Corporation', 'Portag3 Ventures'] },
    notable: 'Since 2016 has launched 18+ companies creating over US$1B in shareholder value.',
    status: 'active',
    website: 'https://diagram.vc/',
    sources: ['https://diagram.vc/', 'https://betakit.com/diagram-ventures-closes-100-million-for-latest-fund-as-it-continues-to-bet-on-fintech/'],
  },
  {
    id: 'cdl-montreal',
    name: 'Creative Destruction Lab — Montreal',
    aka: 'CDL-Montreal',
    type: 'incubator',
    lat: 45.5011,
    lng: -73.6162,
    address: '3000 Chemin de la Côte-Sainte-Catherine, Montréal, QC (HEC Montréal)',
    neighborhood: 'Côte-des-Neiges',
    oneLiner: 'Seed-stage accelerator at HEC Montréal with a dedicated AI stream for deep-tech startups.',
    problem: 'Early-stage deep-tech founders lack the mentorship, judgment and investor access to scale.',
    solution: 'A 9-month, mentor-driven program pairing founders with entrepreneurs, investors and scientists.',
    aiDomains: ['ml-platform', 'research'],
    industries: ['deep-tech', 'supply-chain', 'enterprise'],
    founded: 2017,
    notable: 'Reached over $1B in equity value creation across its ventures by 2022.',
    status: 'active',
    website: 'https://creativedestructionlab.com/locations/montreal/',
    sources: ['https://creativedestructionlab.com/locations/montreal/', 'https://creativedestructionlab.com/streams/ai/cdl-montreal-artificial-intelligence/'],
  },
  {
    id: 'next-ai-montreal',
    name: 'Next AI Montreal',
    aka: 'NextAI',
    type: 'incubator',
    lat: 45.4996,
    lng: -73.6177,
    address: '3000 Chemin de la Côte-Sainte-Catherine, Montréal, QC (HEC Montréal)',
    neighborhood: 'Côte-des-Neiges',
    oneLiner: 'Accelerator at HEC Montréal developing AI-enabled startups from idea to market validation.',
    problem: 'Canadian AI founders need venture-building support and non-dilutive capital to commercialize research.',
    solution: 'A two-phase program with mentorship, AI upskilling, up to $25K non-dilutive funding and ecosystem access.',
    aiDomains: ['ml-platform', 'research'],
    industries: ['deep-tech', 'fintech', 'healthtech'],
    founded: 2018,
    notable: 'Its 2024 Montreal cohort had 32 startups and 63 entrepreneurs.',
    status: 'active',
    website: 'https://www.nextcanada.com/next-ai/',
    sources: ['https://www.nextcanada.com/next-ai/', 'https://executive-education.hec.ca/pages/next-ai-montreal'],
  },
  {
    id: 'centech',
    name: 'Centech',
    aka: 'Centech ÉTS',
    type: 'incubator',
    lat: 45.4956,
    lng: -73.5623,
    address: '1000 Rue Saint-Jacques, Montréal, QC (former Dow Planetarium)',
    neighborhood: 'Griffintown',
    oneLiner: 'Deep-tech startup incubator founded by ÉTS, commercializing hardware and science ventures.',
    problem: 'Deep-tech and hardware startups face long, capital-intensive paths from research to market.',
    solution: 'Acceleration and Propulsion programs with mentorship, labs and resources for deep-tech founders.',
    aiDomains: ['ml-platform', 'robotics', 'edge-ai'],
    industries: ['deep-tech', 'medtech', 'manufacturing', 'hardware'],
    founded: 1996,
    notable: 'Ranked among the world\'s top 10 university business incubators by UBI Global.',
    status: 'active',
    website: 'https://centech.co/',
    sources: ['https://centech.co/en/about-us/', 'https://betakit.com/quebec-grants-centech-4-5-million-to-boost-deep-tech-medtech-commercialization/'],
  },
  {
    id: 'district-3',
    name: 'District 3',
    aka: 'District 3 Innovation Hub',
    type: 'incubator',
    lat: 45.4957,
    lng: -73.5792,
    address: '1250 Rue Guy, Suite 600, Montréal, QC H3H 2L3 (Concordia)',
    neighborhood: 'Downtown',
    oneLiner: 'Free, equity-free startup incubator at Concordia for bio, health, tech and social-impact founders.',
    problem: 'Early-stage founders need hands-on coaching without giving up equity or IP.',
    solution: 'A free 12-week intensive with 1:1 coaching, prototyping facilities and downtown coworking.',
    aiDomains: ['ml-platform', 'research'],
    industries: ['biotech', 'health', 'deep-tech', 'fintech'],
    founded: 2014,
    notable: 'Has supported 600+ startups across AI, life sciences, robotics and fintech since 2014.',
    status: 'active',
    website: 'https://www.district3.co/',
    sources: ['https://www.district3.co/about', 'https://en.wikipedia.org/wiki/District_3_Innovation_Centre'],
  },
  {
    id: 'tandemlaunch',
    name: 'TandemLaunch',
    type: 'incubator',
    lat: 45.4796,
    lng: -73.5878,
    address: '780 Brewster Avenue, Montréal, QC H4C 2K1',
    neighborhood: 'Saint-Henri',
    oneLiner: 'Deep-tech venture foundry and seed fund building startups from top-university IP.',
    problem: 'Breakthrough university research rarely reaches market because inventors lack co-founders and capital.',
    solution: 'Acts as a dedicated co-founder — recruiting talent, licensing IP and providing seed capital.',
    aiDomains: ['computer-vision', 'ml-platform', 'edge-ai', 'research'],
    industries: ['deep-tech', 'consumer-electronics', 'iot'],
    founded: 2010,
    funding: { lastRound: '$37M CAD (Ventures IV Fund)', lastRoundDate: '2022', investors: [] },
    notable: 'Created 30+ ventures worth over $700M (Deeplite, Fluent.ai, C2RO, Sportlogiq); employs 800+ in Québec.',
    status: 'active',
    website: 'https://www.tandemlaunch.com/',
    sources: ['https://www.tandemlaunch.com/', 'https://betakit.com/tandemlaunch-closes-37-million-fund-iv-to-create-and-back-deep-tech-startups/'],
  },
];
