import type { AICompany } from './types';

// ── Victoria BC's industry scene ──────────────────────────────────────────────
// Six industries on one map: Tech, Defense, Ocean Tech, CleanTech, Government,
// and Life Sciences. Hand-curated and deepened by live web research (mid-2026).
// Coordinates are real Greater Victoria locations.
//
// This file is the single source of truth for the Victoria map.

export const COMPANIES: AICompany[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // ── Tech ecosystem ─────────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'telus-ocean',
    name: 'TELUS Ocean',
    industry: 'tech',
    type: 'tech-enterprise',
    lat: 48.4215,
    lng: -123.3657,
    address: '749 Douglas Street, Victoria, BC',
    neighborhood: 'Downtown',
    oneLiner: "TELUS's $150M innovation hub in downtown Victoria — 10-storey office tower with 250+ employees and room for 450.",
    problem: 'Victoria lacked a flagship tech campus to anchor the downtown innovation ecosystem.',
    solution: 'A 154,000 sqft purpose-built innovation centre housing TELUS teams plus leasable space for the broader tech community.',
    aiDomains: ['saas', 'data-analytics', 'ai-ml', 'iot'],
    industries: ['telecommunications', 'technology'],
    founded: 2022,
    headcount: '201-500',
    hiring: true,
    careersUrl: 'https://www.telus.com/en/about/careers',
    status: 'active',
    website: 'https://telusocean.com',
    sources: ['https://victoria.citified.ca/news/10-storey-telus-ocean-to-complete-in-2026-as-decades-sole-downtown-victoria-office-project/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'redbrick',
    name: 'Redbrick',
    industry: 'tech',
    type: 'tech-scaleup',
    lat: 48.4268,
    lng: -123.3648,
    address: '520-1515 Douglas Street, Victoria, BC',
    neighborhood: 'Downtown',
    oneLiner: 'Victoria-born software company that builds, acquires and scales digital publishing tools — $152M revenue in 2024.',
    problem: 'Digital entrepreneurs need powerful, reliable software to grow content-driven businesses.',
    solution: 'A portfolio of SaaS products for digital publishers, grown through a build-and-acquire model since 2011.',
    aiDomains: ['saas', 'martech', 'ecommerce'],
    industries: ['digital publishing', 'advertising'],
    founded: 2011,
    headcount: '51-200',
    notable: 'Acquired New York-based Paved in March 2025; revenue hit $152.2M in 2024. Certified B Corporation.',
    status: 'active',
    website: 'https://www.rdbrck.com',
    sources: ['https://www.rdbrck.com/redbrick', 'https://victoriarising.ca/sector-technology/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'vecima-networks',
    name: 'Vecima Networks',
    industry: 'tech',
    type: 'tech-enterprise',
    lat: 48.4635,
    lng: -123.3677,
    address: '201-771 Vanalman Avenue, Victoria, BC V8Z 3B8',
    neighborhood: 'Saanich',
    oneLiner: 'Public company (TSX: VCM) building broadband access and content-delivery technology used by major cable operators worldwide.',
    problem: 'Cable operators need next-gen hardware and software to deliver multi-gigabit broadband over existing hybrid networks.',
    solution: 'Entra family of DOCSIS and fibre platforms, plus Mediascape content-delivery infrastructure, deployed by 250+ customers globally.',
    aiDomains: ['cloud-infra', 'iot', 'data-analytics'],
    industries: ['telecommunications', 'broadband'],
    founded: 1988,
    headcount: '501-1000',
    hiring: true,
    careersUrl: 'https://vecima.com/careers/',
    notable: 'TSX-listed; founded in Saskatoon, HQ moved to Victoria. ~557 employees serving 250+ customers.',
    status: 'active',
    website: 'https://vecima.com',
    sources: ['https://en.wikipedia.org/wiki/Vecima_Networks', 'https://vecima.com/company/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'abebooks',
    name: 'AbeBooks',
    industry: 'tech',
    type: 'tech-platform',
    lat: 48.4310,
    lng: -123.3905,
    address: '655 Tyee Road, Victoria, BC V9A 6X5',
    neighborhood: 'Vic West',
    oneLiner: "The world's largest online marketplace for books, connecting thousands of independent booksellers to millions of buyers.",
    problem: 'Independent booksellers had no way to reach a global audience for rare, used, and out-of-print titles.',
    solution: 'An online marketplace where 10,000+ booksellers list over 200 million titles, from $1 paperbacks to $50,000 first editions.',
    aiDomains: ['ecommerce', 'data-analytics'],
    industries: ['e-commerce', 'publishing'],
    founded: 1995,
    headcount: '201-500',
    notable: 'Acquired by Amazon in 2008; still operates independently from Victoria with 300+ employees.',
    status: 'active',
    website: 'https://www.abebooks.com',
    sources: ['https://en.wikipedia.org/wiki/AbeBooks'],
    verifiedAt: '2026-07',
  },
  {
    id: 'certn',
    name: 'Certn',
    industry: 'tech',
    type: 'tech-scaleup',
    lat: 48.4248,
    lng: -123.3608,
    address: '1006 Fort Street, Unit 300, Victoria, BC V8V 3K4',
    neighborhood: 'Downtown',
    oneLiner: 'AI-powered background screening platform serving employers across 200+ countries — $114M in venture funding.',
    problem: 'Traditional background checks are slow, fragmented across jurisdictions, and a poor candidate experience.',
    solution: 'A single API connecting criminal, education, employment and identity checks in 200+ countries with same-day turnaround.',
    aiDomains: ['ai-ml', 'saas', 'data-analytics'],
    industries: ['HR tech', 'compliance'],
    founded: 2016,
    headcount: '201-500',
    funding: { totalRaised: '$114M', lastRound: 'Series B', investors: ['Information Venture Partners', 'Inovia Capital'] },
    notable: 'Raised $30M additional Series B financing in Feb 2025, bringing total to $114M.',
    status: 'active',
    website: 'https://certn.co',
    sources: ['https://victoriarising.ca/sector-technology/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'checkfront',
    name: 'Checkfront',
    industry: 'tech',
    type: 'tech-scaleup',
    lat: 48.4228,
    lng: -123.3659,
    address: '777 Broughton Street, 3rd Floor, Victoria, BC V8W 1E3',
    neighborhood: 'Downtown',
    oneLiner: 'Cloud-based booking management platform for tour operators, activity providers and rental businesses worldwide.',
    problem: 'Small and mid-size experience-economy operators struggle with manual booking, availability and payment management.',
    solution: 'An all-in-one SaaS platform handling online booking, availability, payments and waivers for thousands of operators.',
    aiDomains: ['saas', 'ecommerce'],
    industries: ['travel tech', 'hospitality'],
    founded: 2010,
    headcount: '51-200',
    hiring: true,
    careersUrl: 'https://www.checkfront.com/company/careers/',
    status: 'active',
    website: 'https://www.checkfront.com',
    sources: ['https://www.checkfront.com/company/press/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'metalab',
    name: 'MetaLab',
    industry: 'tech',
    type: 'tech-agency',
    lat: 48.4254,
    lng: -123.3631,
    address: '101-524 Yates Street, Victoria, BC V8W 1K8',
    neighborhood: 'Downtown',
    oneLiner: 'Design and product studio behind interfaces for Slack, Coinbase, Uber and other household names.',
    problem: "Fast-growing tech companies need world-class product design but can't always build the team in time.",
    solution: "A 100+ person design studio that ships product interfaces and design systems for some of the world's biggest tech brands.",
    aiDomains: ['saas', 'fintech'],
    industries: ['design', 'product development'],
    founded: 2006,
    headcount: '51-200',
    notable: "Designed the Slack interface; teams across 19 countries. One of Victoria's most celebrated tech exports.",
    status: 'active',
    website: 'https://metalab.com',
    sources: ['https://en.wikipedia.org/wiki/MetaLab,_Ltd.'],
    verifiedAt: '2026-07',
  },
  {
    id: 'llamazoo',
    name: 'LlamaZOO',
    industry: 'tech',
    type: 'tech-startup',
    lat: 48.4237,
    lng: -123.3700,
    address: '#200-1019 Wharf Street, Victoria, BC V8W 2Y9',
    neighborhood: 'Downtown',
    oneLiner: '3D data visualization platform helping enterprises see complex geospatial and industrial data in real-world context.',
    problem: "Resource, mining and energy companies drown in geospatial data they can't intuitively explore.",
    solution: 'An interactive 3D visualization engine that renders massive datasets (LiDAR, geology, IoT) into navigable digital twins.',
    aiDomains: ['gis-geospatial', 'data-analytics', 'ai-ml'],
    industries: ['mining', 'energy', 'forestry'],
    founded: 2014,
    headcount: '11-50',
    status: 'active',
    website: 'https://llamazoo.com',
    sources: ['https://llamazoo.com/contact/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'vivid-solutions',
    name: 'Vivid Solutions',
    industry: 'tech',
    type: 'tech-agency',
    lat: 48.4307,
    lng: -123.3619,
    address: '1A-2328 Government Street, Victoria, BC V8T 5G5',
    neighborhood: 'Downtown',
    oneLiner: 'Geospatial software consultancy and the creators of JTS Topology Suite, the geometry engine behind PostGIS and GeoServer.',
    problem: 'GIS platforms need a reliable, open-source computational geometry engine at their core.',
    solution: 'Built JTS, the industry-standard Java geometry library, and delivers custom geospatial applications on top of it.',
    aiDomains: ['gis-geospatial', 'devtools'],
    industries: ['geospatial', 'open source'],
    founded: 2001,
    headcount: '11-50',
    status: 'active',
    website: 'https://www.vividsolutions.com',
    sources: ['https://www.vividsolutions.com'],
    verifiedAt: '2026-07',
  },
  {
    id: 'viatec',
    name: 'VIATEC',
    aka: 'Victoria Innovation, Advanced Technology & Entrepreneurship Council',
    industry: 'tech',
    type: 'tech-govtech',
    lat: 48.4262,
    lng: -123.3616,
    address: '777 Fort Street, Victoria, BC',
    neighborhood: 'Downtown',
    oneLiner: "Victoria's tech industry association — connecting 1,172 tech companies and 20,000+ employees with talent, capital and community.",
    problem: 'A growing tech ecosystem needs coordinated support for talent, funding and policy advocacy.',
    solution: "BOOST funding, Tech Week, hiring events, startup mentorship and policy advocacy for Greater Victoria's $5.87B tech sector.",
    aiDomains: ['saas'],
    industries: ['industry association', 'economic development'],
    founded: 1989,
    headcount: '11-50',
    notable: 'Projecting Victoria tech revenues to hit $10B by 2030. Runs the BOOST initiative backing 33+ local startups.',
    status: 'active',
    website: 'https://www.viatec.ca',
    sources: ['https://victoriarising.ca/sector-technology/', 'https://www.viatec.ca'],
    verifiedAt: '2026-07',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Defense ecosystem ──────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'cfb-esquimalt',
    name: 'CFB Esquimalt',
    aka: 'Canadian Forces Base Esquimalt',
    industry: 'defense',
    type: 'defense-naval',
    lat: 48.4319,
    lng: -123.4334,
    address: 'CFB Esquimalt, Victoria, BC',
    neighborhood: 'Esquimalt',
    oneLiner: "Canada's Pacific naval base and home to Maritime Forces Pacific — the largest employer on Vancouver Island.",
    problem: 'Canada needs a year-round ice-free Pacific naval base for its fleet.',
    solution: 'A full-service military installation with dockyard, fleet school, damage-control training and housing for thousands of personnel.',
    aiDomains: ['naval-engineering', 'fleet-maintenance', 'simulation-training'],
    industries: ['military', 'naval'],
    founded: 1855,
    headcount: '1001-5000',
    hiring: true,
    careersUrl: 'https://forces.ca/en/careers',
    notable: "Established by the Royal Navy in 1855; Canada's Pacific naval headquarters. Home to frigates, submarines, and coastal defence vessels.",
    status: 'active',
    website: 'https://www.canada.ca/en/navy/corporate/our-organization/structure/marpac.html',
    sources: ['https://en.wikipedia.org/wiki/CFB_Esquimalt'],
    verifiedAt: '2026-07',
  },
  {
    id: 'babcock-canada',
    name: 'Babcock Canada',
    industry: 'defense',
    type: 'defense-contractor',
    lat: 48.4321,
    lng: -123.4230,
    address: '910 Devonshire Road, Victoria, BC V9A 6A9',
    neighborhood: 'Esquimalt',
    oneLiner: "Prime contractor for Victoria-class submarine support — a $1.1B contract keeping Canada's sub fleet operational.",
    problem: "Canada's four Victoria-class submarines need continuous, expert in-service support and deep maintenance.",
    solution: 'An 18-year partnership (VISSC) providing submarine maintenance, refit, and through-life technical support at Esquimalt.',
    aiDomains: ['submarine-support', 'fleet-maintenance', 'naval-engineering'],
    industries: ['defense', 'naval'],
    founded: 2008,
    headcount: '201-500',
    hiring: true,
    careersUrl: 'https://babcockcanada.com/careers/',
    notable: 'Won $1.1B six-year contract extension. Leads "Team Victoria-Class" with Seaspan and BMT.',
    status: 'active',
    website: 'https://babcockcanada.com',
    sources: ['https://babcockcanada.com/team-victoria-class/', 'https://www.abcmi.ca/companies/babcock-canada-inc'],
    verifiedAt: '2026-07',
  },
  {
    id: 'seaspan-victoria-shipyards',
    name: 'Seaspan Victoria Shipyards',
    industry: 'defense',
    type: 'defense-services',
    lat: 48.4319,
    lng: -123.4334,
    address: '825 Admirals Road, Victoria, BC V9A 2P1',
    neighborhood: 'Esquimalt',
    oneLiner: "The West Coast's largest ship repair and conversion facility, operating from the Esquimalt Graving Dock.",
    problem: 'Naval and commercial vessels on the Pacific coast need dry-dock repair and refit capacity.',
    solution: 'Operates the largest solid-bottom commercial drydock on the West Coast of the Americas, serving Navy and commercial fleets.',
    aiDomains: ['shipbuilding', 'fleet-maintenance', 'naval-engineering'],
    industries: ['marine', 'defense'],
    headcount: '201-500',
    notable: 'Prime subcontractor to Babcock for Victoria-class submarine support. Built the Orca-class patrol vessels.',
    status: 'active',
    website: 'https://www.seaspan.com/victoria-shipyards',
    sources: ['https://www.seaspan.com/seaspan-shipyards/repair-refit-and-maintenance/'],
    verifiedAt: '2026-07',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Ocean Tech ecosystem ───────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'ocean-networks-canada',
    name: 'Ocean Networks Canada',
    aka: 'ONC',
    industry: 'ocean',
    type: 'ocean-research',
    lat: 48.4634,
    lng: -123.3129,
    address: 'TEF160, 2300 McKenzie Avenue, University of Victoria, BC',
    neighborhood: 'Saanich',
    oneLiner: "Operates the world's most advanced cabled ocean observatories, delivering 140+ TB of real-time ocean data per year.",
    problem: 'Understanding ocean change requires continuous, real-time data from the deep sea — not periodic ship visits.',
    solution: 'Seafloor-cabled observatories on three Canadian coasts collecting biological, chemical, geological and physical data 24/7.',
    aiDomains: ['ocean-monitoring', 'ocean-instruments', 'marine-biology'],
    industries: ['oceanography', 'climate science'],
    founded: 2007,
    headcount: '51-200',
    hiring: true,
    careersUrl: 'https://www.oceannetworks.ca/careers/',
    notable: 'Hosted by University of Victoria; 1.2+ petabyte data archive accessible via Oceans 3.0 platform.',
    status: 'active',
    website: 'https://www.oceannetworks.ca',
    sources: ['https://en.wikipedia.org/wiki/Ocean_Networks_Canada', 'https://www.oceannetworks.ca/about-onc/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'open-ocean-robotics',
    name: 'Open Ocean Robotics',
    industry: 'ocean',
    type: 'ocean-tech',
    lat: 48.4589,
    lng: -123.3636,
    address: '2L-4476 Markham Street, Victoria, BC V8Z 7X8',
    neighborhood: 'Saanich',
    oneLiner: 'Solar-powered autonomous surface vessels for ocean monitoring — no crew, no fuel, zero emissions.',
    problem: 'Ocean data collection with crewed vessels is expensive, carbon-intensive and covers only a fraction of the ocean.',
    solution: 'Uncrewed, solar-electric surface vessels that patrol autonomously for months, streaming real-time environmental data.',
    aiDomains: ['autonomous-vessels', 'ocean-monitoring', 'coastal-intelligence'],
    industries: ['marine tech', 'environmental monitoring'],
    founded: 2018,
    headcount: '11-50',
    notable: 'Won SDTC funding; partnered with ASL Environmental Sciences for ocean data.',
    status: 'active',
    website: 'https://www.openoceanrobotics.com',
    sources: ['https://www.openoceanrobotics.com', 'https://www.abcmi.ca/companies/open-ocean-robotics'],
    verifiedAt: '2026-07',
  },
  {
    id: 'asl-environmental',
    name: 'ASL Environmental Sciences',
    industry: 'ocean',
    type: 'ocean-services',
    lat: 48.4252,
    lng: -123.3597,
    address: '777 Fort Street, Victoria, BC V8W 1G9',
    neighborhood: 'Downtown',
    oneLiner: 'Oceanographic and acoustic instrumentation firm providing data services for defense, energy and environmental clients.',
    problem: 'Subsea acoustic and environmental data requires specialized instrumentation and decades of domain expertise.',
    solution: 'Designs and deploys acoustic Doppler instruments and runs environmental monitoring programs for navies and offshore operators.',
    aiDomains: ['ocean-instruments', 'ocean-monitoring', 'hydrography'],
    industries: ['oceanography', 'defense', 'energy'],
    founded: 1977,
    headcount: '11-50',
    notable: 'Partnered with Open Ocean Robotics in 2025 for autonomous vessel-based data collection.',
    status: 'active',
    website: 'https://aslenv.com',
    sources: ['https://aslenv.com', 'https://members.viatec.ca/member-directory/Details/asl-environmental-sciences-inc-1392570'],
    verifiedAt: '2026-07',
  },
  {
    id: 'seamor-marine',
    name: 'Seamor Marine',
    industry: 'ocean',
    type: 'ocean-tech',
    lat: 48.7835,
    lng: -123.7088,
    address: 'Nanaimo, BC',
    neighborhood: 'Greater Victoria',
    locationPrecision: 'approximate',
    oneLiner: 'Long-time leader in remotely operated vehicle (ROV) technology, with submersibles deployed across dozens of countries.',
    problem: 'Subsea inspection and research demand reliable, portable ROVs that work in harsh ocean conditions.',
    solution: 'A range of observation-class ROVs for military, oil & gas, aquaculture and research — designed and built in BC.',
    aiDomains: ['autonomous-vessels', 'ocean-instruments'],
    industries: ['marine tech', 'aquaculture', 'defense'],
    headcount: '11-50',
    status: 'active',
    website: 'https://seamor.com',
    sources: ['https://www.douglasmagazine.com/victoria-ocean-tech-blue-economy-bc'],
    verifiedAt: '2026-07',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── CleanTech ecosystem ────────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'bc-hydro-victoria',
    name: 'BC Hydro (Victoria Office)',
    industry: 'cleantech',
    type: 'cleantech-utility',
    lat: 48.4759,
    lng: -123.4685,
    address: '4400 West Saanich Road, Victoria, BC',
    neighborhood: 'Saanich',
    oneLiner: "BC's crown utility — 98% of its power comes from renewable hydro, serving 2M+ customers across the province.",
    problem: 'British Columbia needs a reliable, clean electricity supply for 2 million customers and a growing economy.',
    solution: '30 hydro generating facilities and 80,000+ km of power lines delivering 98% renewable electricity across the province.',
    aiDomains: ['electric-utility', 'renewable-energy', 'grid-management'],
    industries: ['energy', 'utilities'],
    founded: 1961,
    headcount: '1001-5000',
    hiring: true,
    careersUrl: 'https://www.bchydro.com/careers.html',
    notable: 'Crown corporation. Recently issued purchase agreements for 9 wind and 1 solar project adding ~5,000 GWh/year.',
    status: 'active',
    website: 'https://www.bchydro.com',
    sources: ['https://en.wikipedia.org/wiki/BC_Hydro'],
    verifiedAt: '2026-07',
  },
  {
    id: 'besolar',
    name: 'BeSolar',
    industry: 'cleantech',
    type: 'cleantech-services',
    lat: 48.4500,
    lng: -123.3700,
    address: 'Victoria, BC',
    neighborhood: 'Saanich',
    locationPrecision: 'approximate',
    oneLiner: 'One of the largest solar system installers in the Greater Victoria area — residential and commercial PV.',
    problem: 'Vancouver Island homeowners and businesses want solar but need local design, installation and permitting expertise.',
    solution: 'End-to-end solar panel design, installation and grid interconnection for residential and commercial customers on the Island.',
    aiDomains: ['renewable-energy', 'energy-efficiency'],
    industries: ['solar', 'construction'],
    headcount: '11-50',
    status: 'active',
    website: 'https://besolar.ca',
    sources: ['https://cleanenergybc.org/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'harbour-renewables',
    name: 'Harbour Renewables',
    industry: 'cleantech',
    type: 'cleantech-services',
    lat: 48.4350,
    lng: -123.3500,
    address: 'Victoria, BC',
    neighborhood: 'Downtown',
    locationPrecision: 'approximate',
    oneLiner: 'Solar system supplier and installer serving the Greater Victoria region and Vancouver Island.',
    problem: 'Island communities need reliable local partners for solar system supply, design and installation.',
    solution: 'Supplies and installs residential and commercial solar systems with local permitting and grid-tie expertise.',
    aiDomains: ['renewable-energy'],
    industries: ['solar', 'construction'],
    headcount: '1-10',
    status: 'active',
    website: 'https://harbourrenewables.com',
    sources: ['https://cleanenergybc.org/'],
    verifiedAt: '2026-07',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Government ecosystem ───────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'bc-legislature',
    name: 'BC Provincial Government',
    aka: 'BC Public Service',
    industry: 'government',
    type: 'gov-provincial',
    lat: 48.4198,
    lng: -123.3656,
    address: '501 Belleville Street, Victoria, BC V8V 1X4',
    neighborhood: 'James Bay',
    oneLiner: "British Columbia's provincial capital — tens of thousands of public servants working across ministries in Victoria.",
    problem: 'Governing a province of 5.3 million people requires a concentrated, professional civil service.',
    solution: "Victoria is the capital of BC; the legislature buildings and surrounding blocks house the province's executive, legislative and judicial branches.",
    aiDomains: ['public-service', 'digital-services'],
    industries: ['government'],
    headcount: '5001-10000',
    hiring: true,
    careersUrl: 'https://www2.gov.bc.ca/gov/content/careers-myhr',
    notable: "Victoria's single largest employer category. The Parliament Buildings are a National Historic Site.",
    status: 'active',
    website: 'https://www2.gov.bc.ca',
    sources: ['https://en.wikipedia.org/wiki/British_Columbia_Parliament_Buildings'],
    verifiedAt: '2026-07',
  },
  {
    id: 'icbc',
    name: 'ICBC',
    aka: 'Insurance Corporation of British Columbia',
    industry: 'government',
    type: 'gov-crown',
    lat: 48.4218,
    lng: -123.3696,
    address: '955 Wharf Street, Victoria, BC',
    neighborhood: 'Downtown',
    oneLiner: "BC's provincial auto insurance crown corporation — the only public auto insurer in western Canada.",
    problem: 'British Columbians need a universal, no-fault auto insurance system.',
    solution: 'A government-owned insurer providing universal basic auto insurance, licensing, and vehicle registration for all BC drivers.',
    aiDomains: ['insurance-crown', 'digital-services'],
    industries: ['insurance', 'government'],
    founded: 1973,
    headcount: '1001-5000',
    hiring: true,
    careersUrl: 'https://www.icbc.com/about-icbc/careers',
    notable: 'Crown corporation headquartered in North Vancouver; major Victoria office on Wharf Street.',
    status: 'active',
    website: 'https://www.icbc.com',
    sources: ['https://livinginvictoriabc.com/general-info/victorias-biggest-job-sectors-and-employers'],
    verifiedAt: '2026-07',
  },
  {
    id: 'worksafebc-victoria',
    name: 'WorkSafeBC (Victoria)',
    industry: 'government',
    type: 'gov-crown',
    lat: 48.4711,
    lng: -123.3929,
    address: '4514 Chatterton Way, Victoria, BC V8X 5H2',
    neighborhood: 'Saanich',
    oneLiner: "BC's workplace health and safety regulator and workers' compensation insurer — major employer in Greater Victoria.",
    problem: 'Workers and employers need a unified system for workplace safety regulation, injury claims and return-to-work programs.',
    solution: 'A crown corporation managing workplace safety standards, injury compensation and employer assessments province-wide.',
    aiDomains: ['public-service', 'digital-services'],
    industries: ['government', 'insurance'],
    founded: 1917,
    headcount: '1001-5000',
    hiring: true,
    careersUrl: 'https://www.worksafebc.com/en/about-us/careers',
    status: 'active',
    website: 'https://www.worksafebc.com',
    sources: ['https://www.worksafebc.com/en/contact-us/office-locations'],
    verifiedAt: '2026-07',
  },
  {
    id: 'canada-revenue-agency-victoria',
    name: 'Canada Revenue Agency (Victoria)',
    aka: 'CRA Victoria',
    industry: 'government',
    type: 'gov-federal',
    lat: 48.4333,
    lng: -123.3636,
    address: '1415 Vancouver Street, Victoria, BC',
    neighborhood: 'North Park',
    oneLiner: 'Federal tax administration — one of the largest federal government employers in the Greater Victoria region.',
    problem: 'Collecting federal taxes and delivering benefit programs requires regional processing centres.',
    solution: 'A Victoria regional office handling tax processing, auditing and benefit administration for Vancouver Island.',
    aiDomains: ['public-service', 'digital-services'],
    industries: ['government', 'finance'],
    headcount: '501-1000',
    hiring: true,
    careersUrl: 'https://www.canada.ca/en/revenue-agency/corporate/careers-cra.html',
    status: 'active',
    website: 'https://www.canada.ca/en/revenue-agency.html',
    sources: ['https://livinginvictoriabc.com/general-info/victorias-biggest-job-sectors-and-employers'],
    verifiedAt: '2026-07',
  },
  {
    id: 'city-of-victoria',
    name: 'City of Victoria',
    industry: 'government',
    type: 'gov-municipal',
    lat: 48.4284,
    lng: -123.3656,
    address: '1 Centennial Square, Victoria, BC V8W 1P6',
    neighborhood: 'Downtown',
    oneLiner: 'The municipal government of the City of Victoria — planning, infrastructure, parks, and public services.',
    problem: 'A capital city of 95,000 needs coordinated municipal services, planning and infrastructure investment.',
    solution: 'City Hall and municipal departments managing urban planning, transit, parks, housing policy, and civic services.',
    aiDomains: ['public-service', 'digital-services'],
    industries: ['government', 'urban planning'],
    headcount: '501-1000',
    hiring: true,
    careersUrl: 'https://www.victoria.ca/careers',
    status: 'active',
    website: 'https://www.victoria.ca',
    sources: ['https://www.victoria.ca'],
    verifiedAt: '2026-07',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ── Life Sciences ecosystem ────────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'aurinia-pharmaceuticals',
    name: 'Aurinia Pharmaceuticals',
    industry: 'lifesci',
    type: 'lifesci-pharma',
    lat: 48.4589,
    lng: -123.3636,
    address: '1203-4464 Markham Street, Victoria, BC V8Z 7X8',
    neighborhood: 'Saanich',
    oneLiner: 'Public biopharmaceutical company (NASDAQ: AUPH) commercializing LUPKYNIS for lupus nephritis — ~$2B market cap.',
    problem: 'Lupus nephritis is a serious autoimmune kidney disease with limited effective treatment options.',
    solution: 'LUPKYNIS (voclosporin), an FDA-approved calcineurin inhibitor that significantly reduces proteinuria in lupus nephritis.',
    aiDomains: ['drug-discovery', 'immunotherapy'],
    industries: ['pharmaceuticals', 'autoimmune'],
    founded: 1993,
    headcount: '201-500',
    hiring: true,
    careersUrl: 'https://www.auriniapharma.com/company/careers',
    notable: 'NASDAQ-listed; ~$2B market cap. LUPKYNIS is the first oral therapy specifically approved for lupus nephritis.',
    status: 'active',
    website: 'https://www.auriniapharma.com',
    sources: ['https://ir.auriniapharma.com/profile', 'https://victoriarising.ca/life-sciences-sector/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'starfish-medical',
    name: 'StarFish Medical',
    industry: 'lifesci',
    type: 'lifesci-biotech',
    lat: 48.4526,
    lng: -123.3763,
    address: '455 Boleskine Road, Victoria, BC V8Z 1E7',
    neighborhood: 'Saanich',
    oneLiner: "Canada's largest medical device design company — takes devices from concept through regulatory approval to manufacturing.",
    problem: 'Medical device startups and multinationals need specialized design, prototyping and regulatory expertise to bring devices to market.',
    solution: 'A full-service design, development and contract manufacturing firm that has launched hundreds of medical devices.',
    aiDomains: ['medical-devices', 'biotech-rd'],
    industries: ['medical devices', 'healthcare'],
    founded: 1996,
    headcount: '51-200',
    hiring: true,
    careersUrl: 'https://starfishmedical.com/careers/',
    notable: "Canada's largest MedTech product development company. Offices in Victoria and Toronto.",
    status: 'active',
    website: 'https://starfishmedical.com',
    sources: ['https://starfishmedical.com/locations/victoria/', 'https://victoriarising.ca/life-sciences-sector/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'immunoprecise-antibodies',
    name: 'ImmunoPrecise Antibodies',
    aka: 'IPA',
    industry: 'lifesci',
    type: 'lifesci-biotech',
    lat: 48.4589,
    lng: -123.3640,
    address: '3204-4464 Markham Street, Victoria, BC V8Z 7X8',
    neighborhood: 'Saanich',
    oneLiner: 'Full-service antibody discovery company using AI-driven platforms to accelerate therapeutic antibody development.',
    problem: 'Discovering the right therapeutic antibody is slow, expensive and failure-prone without computational guidance.',
    solution: 'Combines wet-lab antibody discovery with proprietary AI platforms (LENSai) to predict and optimize antibody candidates.',
    aiDomains: ['drug-discovery', 'biotech-rd', 'precision-medicine'],
    industries: ['biotech', 'therapeutics'],
    founded: 1983,
    headcount: '51-200',
    notable: 'NASDAQ-listed (IPA). Labs in Victoria and Utrecht; HQ in Fargo, ND. Over $200M market cap.',
    status: 'active',
    website: 'https://www.ipatherapeutics.com',
    sources: ['https://vitp.ca/current-companies/company-directory/list/immunoprecise-antibodies/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'eupraxia-pharmaceuticals',
    name: 'Eupraxia Pharmaceuticals',
    industry: 'lifesci',
    type: 'lifesci-biotech',
    lat: 48.4456,
    lng: -123.3088,
    address: '201-2067 Cadboro Bay Road, Victoria, BC V8R 5G4',
    neighborhood: 'Oak Bay',
    oneLiner: 'Clinical-stage biotech developing targeted therapies using a proprietary extended-release drug delivery system.',
    problem: 'Many effective drugs cause systemic side effects because they circulate everywhere instead of staying at the treatment site.',
    solution: 'A proprietary DiffuSphere microsphere platform that delivers drugs locally with extended release, minimizing systemic exposure.',
    aiDomains: ['drug-discovery', 'precision-medicine'],
    industries: ['biotech', 'drug delivery'],
    founded: 2011,
    headcount: '11-50',
    notable: 'TSX-listed (EPRX). Lead candidate EP-104IAR in Phase 2 for knee osteoarthritis.',
    status: 'active',
    website: 'https://www.eupraxiapharma.com',
    sources: ['https://eupraxiapharma.com/about-us/', 'https://victoriarising.ca/life-sciences-sector/'],
    verifiedAt: '2026-07',
  },
  {
    id: 'vils',
    name: 'Victoria Innovation & Life Sciences',
    aka: 'VILS',
    industry: 'lifesci',
    type: 'lifesci-research',
    lat: 48.4284,
    lng: -123.3656,
    address: 'Victoria, BC',
    neighborhood: 'Downtown',
    locationPrecision: 'approximate',
    oneLiner: "Open nonprofit association supporting Victoria's 60+ life sciences companies with networking, advocacy and community.",
    problem: 'A fragmented life sciences sector needs a single community hub for talent, funding and collaboration.',
    solution: 'A nonprofit connecting biotech, diagnostics, medical device, pharma and software companies across the region.',
    aiDomains: ['biotech-rd'],
    industries: ['industry association', 'life sciences'],
    headcount: '1-10',
    status: 'active',
    website: 'https://www.vils.ca',
    sources: ['https://www.vils.ca/'],
    verifiedAt: '2026-07',
  },
];
