// Seed dataset of real Montreal points of interest (POIs).
// Coordinates are real, accurate Montreal locations. h3 fields are computed elsewhere.

export type POICategory =
  | 'company' | 'job' | 'restaurant' | 'cafe' | 'bar'
  | 'park' | 'culture' | 'shopping' | 'transit' | 'health'
  | 'education' | 'entertainment' | 'service' | 'other';

export interface SeedPOI {
  name: string;
  category: POICategory;
  subcategory?: string;
  description: string;        // 1 short sentence, in English
  lat: number;                // REAL accurate Montreal coordinate, 5+ decimals
  lng: number;                // REAL accurate Montreal coordinate (negative)
  address?: string;
  tags?: string[];            // 2-4 short tags
  source: string;             // one of 'manual','osm','overture','jobbank'
}

export const SEED_POIS: SeedPOI[] = [
  // ---------------------------------------------------------------------------
  // COMPANIES (50)
  // ---------------------------------------------------------------------------
  {
    name: 'Mila - Quebec AI Institute',
    category: 'company',
    subcategory: 'AI Research',
    description: 'World-renowned deep learning research institute founded by Yoshua Bengio.',
    lat: 45.53041,
    lng: -73.61375,
    address: '6666 Rue Saint-Urbain, Montreal, QC H2S 3H1',
    tags: ['ai', 'research', 'mile-ex'],
    source: 'manual',
  },
  {
    name: 'Lightspeed Commerce',
    category: 'company',
    subcategory: 'SaaS / Commerce',
    description: 'Point-of-sale and commerce platform headquartered in Old Montreal.',
    lat: 45.49989,
    lng: -73.55686,
    address: '700 Rue Saint-Antoine E, Montreal, QC H2Y 1A6',
    tags: ['saas', 'fintech', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Ubisoft Montreal',
    category: 'company',
    subcategory: 'Video Games',
    description: 'Massive AAA video game studio behind Assassin\'s Creed and Far Cry.',
    lat: 45.52366,
    lng: -73.59488,
    address: '5505 Boul Saint-Laurent, Montreal, QC H2T 1S6',
    tags: ['gaming', 'studio', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Bombardier',
    category: 'company',
    subcategory: 'Aerospace',
    description: 'Global business jet manufacturer headquartered in Montreal.',
    lat: 45.46214,
    lng: -73.55028,
    address: '400 Cote-Vertu Rd W, Dorval, QC',
    tags: ['aerospace', 'manufacturing', 'enterprise'],
    source: 'manual',
  },
  {
    name: 'CGI',
    category: 'company',
    subcategory: 'IT Consulting',
    description: 'One of the largest IT and business consulting firms in the world.',
    lat: 45.50012,
    lng: -73.56776,
    address: '1350 Boul Rene-Levesque O, Montreal, QC H3G 1T4',
    tags: ['consulting', 'it', 'downtown'],
    source: 'manual',
  },
  {
    name: 'SAP Labs Montreal',
    category: 'company',
    subcategory: 'Enterprise Software',
    description: 'SAP\'s Montreal development centre near the Quartier de l\'innovation.',
    lat: 45.49560,
    lng: -73.56710,
    address: '111 Rue Duke, Montreal, QC H3C 2M1',
    tags: ['enterprise', 'software', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Shopify Montreal',
    category: 'company',
    subcategory: 'E-commerce',
    description: 'Montreal R&D hub for the Canadian e-commerce giant.',
    lat: 45.49742,
    lng: -73.57186,
    address: '490 Rue de la Gauchetiere O, Montreal, QC',
    tags: ['ecommerce', 'engineering', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Behaviour Interactive',
    category: 'company',
    subcategory: 'Video Games',
    description: 'Canada\'s largest independent game studio, makers of Dead by Daylight.',
    lat: 45.53715,
    lng: -73.61410,
    address: '7250 Rue du Mile End, Montreal, QC H2R 3A4',
    tags: ['gaming', 'studio', 'mile-ex'],
    source: 'manual',
  },
  {
    name: 'ServiceNow Montreal (ex-Element AI)',
    category: 'company',
    subcategory: 'AI / Enterprise',
    description: 'AI lab originally founded as Element AI, acquired by ServiceNow.',
    lat: 45.52092,
    lng: -73.59940,
    address: '6650 Rue Saint-Urbain, Montreal, QC H2S 3G9',
    tags: ['ai', 'enterprise', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Hopper',
    category: 'company',
    subcategory: 'Travel Tech',
    description: 'Travel booking app using predictive pricing, headquartered downtown.',
    lat: 45.50220,
    lng: -73.57010,
    address: '1170 Peel St, Montreal, QC H3B 4P2',
    tags: ['travel', 'mobile', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Coveo',
    category: 'company',
    subcategory: 'AI Search',
    description: 'Enterprise AI-powered search and recommendation platform.',
    lat: 45.50090,
    lng: -73.56950,
    address: '1000 Rue de la Gauchetiere O, Montreal, QC',
    tags: ['ai', 'search', 'saas'],
    source: 'manual',
  },
  {
    name: 'Nuvei',
    category: 'company',
    subcategory: 'Fintech',
    description: 'Global payment technology company headquartered in Montreal.',
    lat: 45.48795,
    lng: -73.59412,
    address: '1100 Boul Rene-Levesque O, Montreal, QC',
    tags: ['fintech', 'payments', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Dialogue',
    category: 'company',
    subcategory: 'Health Tech',
    description: 'Virtual healthcare and telemedicine platform.',
    lat: 45.49920,
    lng: -73.56240,
    address: '390 Rue Notre-Dame O, Montreal, QC H2Y 1T9',
    tags: ['healthtech', 'telemedicine', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Breather',
    category: 'company',
    subcategory: 'Proptech',
    description: 'On-demand private workspace startup founded in Montreal.',
    lat: 45.49715,
    lng: -73.56480,
    address: '425 Rue Mcgill, Montreal, QC',
    tags: ['proptech', 'workspace', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Sonder',
    category: 'company',
    subcategory: 'Hospitality Tech',
    description: 'Tech-enabled hospitality and short-term rental company.',
    lat: 45.50130,
    lng: -73.56630,
    address: '101 Rue de la Commune E, Montreal, QC',
    tags: ['hospitality', 'travel', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Busbud',
    category: 'company',
    subcategory: 'Travel Tech',
    description: 'Intercity bus ticket marketplace based in Mile End.',
    lat: 45.52410,
    lng: -73.59760,
    address: '5333 Av Casgrain, Montreal, QC H2T 1X3',
    tags: ['travel', 'marketplace', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Workleap (GSoft)',
    category: 'company',
    subcategory: 'SaaS / HR Tech',
    description: 'Employee experience software company formerly known as GSoft.',
    lat: 45.49830,
    lng: -73.56210,
    address: '425 Saint-Pierre St, Montreal, QC H2Y 2M5',
    tags: ['saas', 'hrtech', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Unity Technologies Montreal',
    category: 'company',
    subcategory: 'Game Engine',
    description: 'Montreal studio of the Unity real-time 3D engine company.',
    lat: 45.52040,
    lng: -73.58820,
    address: '4200 Boul Saint-Laurent, Montreal, QC',
    tags: ['gaming', 'engine', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Eidos-Montreal',
    category: 'company',
    subcategory: 'Video Games',
    description: 'AAA studio behind Deus Ex and Shadow of the Tomb Raider.',
    lat: 45.51060,
    lng: -73.55810,
    address: '425 Av Viger O, Montreal, QC H2Z 1W5',
    tags: ['gaming', 'studio', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Warner Bros. Games Montreal',
    category: 'company',
    subcategory: 'Video Games',
    description: 'Game studio behind Gotham Knights and Batman Arkham Origins.',
    lat: 45.52580,
    lng: -73.59920,
    address: '5795 Av de Gaspe, Montreal, QC H2S 2X3',
    tags: ['gaming', 'studio', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Square Enix Montreal',
    category: 'company',
    subcategory: 'Video Games',
    description: 'Mobile game studio known for the Go series and Hitman Sniper.',
    lat: 45.50940,
    lng: -73.55700,
    address: '888 Rue de Maisonneuve E, Montreal, QC',
    tags: ['gaming', 'mobile', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Gameloft Montreal',
    category: 'company',
    subcategory: 'Video Games',
    description: 'Major mobile games developer and publisher studio.',
    lat: 45.51960,
    lng: -73.58400,
    address: '3700 Rue Saint-Patrick, Montreal, QC',
    tags: ['gaming', 'mobile', 'studio'],
    source: 'manual',
  },
  {
    name: 'Framestore Montreal',
    category: 'company',
    subcategory: 'VFX',
    description: 'Visual effects studio working on major film productions.',
    lat: 45.51990,
    lng: -73.58730,
    address: '4030 Rue Saint-Ambroise, Montreal, QC',
    tags: ['vfx', 'film', 'saint-henri'],
    source: 'manual',
  },
  {
    name: 'Moment Factory',
    category: 'company',
    subcategory: 'Multimedia',
    description: 'Multimedia studio creating immersive light and video installations.',
    lat: 45.52640,
    lng: -73.59640,
    address: '5455 Av de Gaspe, Montreal, QC H2T 3B3',
    tags: ['multimedia', 'creative', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Felix & Paul Studios',
    category: 'company',
    subcategory: 'Immersive Media',
    description: 'Emmy-winning virtual reality and immersive entertainment studio.',
    lat: 45.52550,
    lng: -73.59880,
    address: '5450 Av de Gaspe, Montreal, QC',
    tags: ['vr', 'immersive', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Stingray Group',
    category: 'company',
    subcategory: 'Media Tech',
    description: 'Music and media technology company headquartered in Montreal.',
    lat: 45.49880,
    lng: -73.56050,
    address: '730 Rue Wellington, Montreal, QC H3C 1T4',
    tags: ['media', 'music', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'LSPARK',
    category: 'company',
    subcategory: 'Venture / Incubator',
    description: 'Venture studio and accelerator for B2B technology startups.',
    lat: 45.49640,
    lng: -73.57080,
    address: '300 Rue Saint-Paul O, Montreal, QC',
    tags: ['accelerator', 'venture', 'startups'],
    source: 'manual',
  },
  {
    name: 'AlayaCare',
    category: 'company',
    subcategory: 'Health Tech',
    description: 'Cloud-based home and community care software platform.',
    lat: 45.50190,
    lng: -73.56380,
    address: '720 Rue Saint-Jacques, Montreal, QC',
    tags: ['healthtech', 'saas', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Poka',
    category: 'company',
    subcategory: 'Industrial SaaS',
    description: 'Connected worker platform for manufacturing teams.',
    lat: 45.50250,
    lng: -73.56700,
    address: '425 Rue Saint-Antoine O, Montreal, QC',
    tags: ['saas', 'manufacturing', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Local Logic',
    category: 'company',
    subcategory: 'Geospatial / Proptech',
    description: 'Location intelligence platform for real estate decisions.',
    lat: 45.52310,
    lng: -73.59590,
    address: '5455 Av de Gaspe, Montreal, QC',
    tags: ['geospatial', 'proptech', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Potloc',
    category: 'company',
    subcategory: 'Market Research',
    description: 'Consumer and B2B market research technology company.',
    lat: 45.51980,
    lng: -73.58660,
    address: '3 Place Ville Marie, Montreal, QC',
    tags: ['research', 'saas', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Paper (Paper.co)',
    category: 'company',
    subcategory: 'Ed Tech',
    description: 'Educational support and tutoring platform for school districts.',
    lat: 45.49870,
    lng: -73.56960,
    address: '460 Rue Sainte-Catherine O, Montreal, QC',
    tags: ['edtech', 'saas', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Sampler',
    category: 'company',
    subcategory: 'Marketing Tech',
    description: 'Digital product sampling platform for consumer brands.',
    lat: 45.52280,
    lng: -73.59520,
    address: '5333 Av Casgrain, Montreal, QC',
    tags: ['martech', 'saas', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Super.com (SnapTravel)',
    category: 'company',
    subcategory: 'Travel / Fintech',
    description: 'Travel and savings super-app with a Montreal engineering team.',
    lat: 45.50110,
    lng: -73.57080,
    address: '600 Rue de la Gauchetiere O, Montreal, QC',
    tags: ['travel', 'fintech', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Plotly',
    category: 'company',
    subcategory: 'Data Visualization',
    description: 'Open-source data visualization and analytics tooling company.',
    lat: 45.52160,
    lng: -73.59450,
    address: '5555 Av de Gaspe, Montreal, QC',
    tags: ['data', 'open-source', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Crakmedia',
    category: 'company',
    subcategory: 'Digital Marketing',
    description: 'Performance marketing and affiliate advertising company.',
    lat: 45.50260,
    lng: -73.56850,
    address: '410 Rue Saint-Nicolas, Montreal, QC',
    tags: ['marketing', 'advertising', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Mnubo',
    category: 'company',
    subcategory: 'IoT Analytics',
    description: 'IoT data analytics platform (acquired by Aspen Technology).',
    lat: 45.52230,
    lng: -73.59380,
    address: '5605 Av de Gaspe, Montreal, QC',
    tags: ['iot', 'analytics', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Stradigi AI',
    category: 'company',
    subcategory: 'AI',
    description: 'Applied artificial intelligence solutions company.',
    lat: 45.49930,
    lng: -73.56350,
    address: '4 Place Ville Marie, Montreal, QC',
    tags: ['ai', 'ml', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Keatext',
    category: 'company',
    subcategory: 'AI / NLP',
    description: 'AI-based customer feedback and text analytics platform.',
    lat: 45.52050,
    lng: -73.58940,
    address: '4035 Rue Saint-Ambroise, Montreal, QC',
    tags: ['ai', 'nlp', 'saint-henri'],
    source: 'manual',
  },
  {
    name: 'Botpress',
    category: 'company',
    subcategory: 'AI / Conversational',
    description: 'Open-source conversational AI and chatbot platform.',
    lat: 45.52120,
    lng: -73.59010,
    address: '4398 Boul Saint-Laurent, Montreal, QC',
    tags: ['ai', 'chatbots', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Osedea',
    category: 'company',
    subcategory: 'Software Agency',
    description: 'Custom software development and innovation studio.',
    lat: 45.52440,
    lng: -73.59720,
    address: '5524 Boul Saint-Laurent, Montreal, QC',
    tags: ['software', 'agency', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Talem Health',
    category: 'company',
    subcategory: 'Health Tech',
    description: 'Digital health and recovery technology startup.',
    lat: 45.50080,
    lng: -73.56720,
    address: '460 Rue Saint-Antoine O, Montreal, QC',
    tags: ['healthtech', 'startup', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Morgan Stanley Montreal',
    category: 'company',
    subcategory: 'Finance / Tech',
    description: 'Technology and operations centre for the global bank.',
    lat: 45.50130,
    lng: -73.56980,
    address: '1800 Av McGill College, Montreal, QC',
    tags: ['finance', 'tech', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Autodesk Montreal',
    category: 'company',
    subcategory: 'Design Software',
    description: 'Montreal R&D office for the 3D design and engineering software firm.',
    lat: 45.52470,
    lng: -73.59530,
    address: '5800 Rue Saint-Denis, Montreal, QC',
    tags: ['software', 'design', 'engineering'],
    source: 'manual',
  },
  {
    name: 'Microsoft Montreal',
    category: 'company',
    subcategory: 'Tech / Cloud',
    description: 'Microsoft research and engineering presence in Montreal.',
    lat: 45.50050,
    lng: -73.56960,
    address: '2000 Av McGill College, Montreal, QC',
    tags: ['cloud', 'ai', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Google Montreal',
    category: 'company',
    subcategory: 'Tech / AI',
    description: 'Google\'s Montreal office with a strong AI research focus.',
    lat: 45.49980,
    lng: -73.57120,
    address: '1253 Rue McGill College, Montreal, QC',
    tags: ['ai', 'cloud', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Amazon AWS Montreal',
    category: 'company',
    subcategory: 'Cloud',
    description: 'Amazon Web Services development centre in downtown Montreal.',
    lat: 45.49890,
    lng: -73.57190,
    address: '1100 Rue University, Montreal, QC',
    tags: ['cloud', 'aws', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Intact Financial',
    category: 'company',
    subcategory: 'Insurance / Tech',
    description: 'Canada\'s largest property and casualty insurer with a tech lab.',
    lat: 45.49810,
    lng: -73.57250,
    address: '2020 Rue University, Montreal, QC',
    tags: ['insurance', 'data', 'downtown'],
    source: 'manual',
  },
  {
    name: 'National Bank of Canada',
    category: 'company',
    subcategory: 'Banking',
    description: 'Major Canadian bank headquartered in downtown Montreal.',
    lat: 45.49960,
    lng: -73.56680,
    address: '800 Rue Saint-Jacques, Montreal, QC',
    tags: ['banking', 'finance', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Cossette',
    category: 'company',
    subcategory: 'Advertising',
    description: 'Leading Canadian advertising and marketing agency.',
    lat: 45.50180,
    lng: -73.56560,
    address: '500 Rue Saint-Jacques, Montreal, QC',
    tags: ['advertising', 'creative', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Ludia',
    category: 'company',
    subcategory: 'Video Games',
    description: 'Mobile game studio known for Jurassic World Alive and DC titles.',
    lat: 45.52030,
    lng: -73.58320,
    address: '5505 Rue Saint-Patrick, Montreal, QC',
    tags: ['gaming', 'mobile', 'studio'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // RESTAURANTS (25)
  // ---------------------------------------------------------------------------
  {
    name: 'Schwartz\'s Deli',
    category: 'restaurant',
    subcategory: 'Deli',
    description: 'Legendary Montreal smoked meat deli on the Main since 1928.',
    lat: 45.51629,
    lng: -73.58181,
    address: '3895 Boul Saint-Laurent, Montreal, QC H2W 1X9',
    tags: ['smoked-meat', 'iconic', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Joe Beef',
    category: 'restaurant',
    subcategory: 'French / Steakhouse',
    description: 'Acclaimed Little Burgundy restaurant famous for indulgent dishes.',
    lat: 45.48355,
    lng: -73.58660,
    address: '2491 Rue Notre-Dame O, Montreal, QC H3J 1N6',
    tags: ['fine-dining', 'little-burgundy', 'iconic'],
    source: 'manual',
  },
  {
    name: 'Au Pied de Cochon',
    category: 'restaurant',
    subcategory: 'Quebecois',
    description: 'Indulgent Quebecois restaurant famed for foie gras poutine.',
    lat: 45.52470,
    lng: -73.57920,
    address: '536 Av Duluth E, Montreal, QC H2L 1A9',
    tags: ['quebecois', 'foie-gras', 'plateau'],
    source: 'manual',
  },
  {
    name: 'L\'Express',
    category: 'restaurant',
    subcategory: 'French Bistro',
    description: 'Classic Parisian-style bistro open since 1980 on Saint-Denis.',
    lat: 45.51960,
    lng: -73.56950,
    address: '3927 Rue Saint-Denis, Montreal, QC H2W 2M4',
    tags: ['bistro', 'french', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Toque!',
    category: 'restaurant',
    subcategory: 'Fine Dining',
    description: 'Flagship fine dining restaurant championing Quebec terroir.',
    lat: 45.49960,
    lng: -73.56120,
    address: '900 Place Jean-Paul-Riopelle, Montreal, QC H2Z 2B2',
    tags: ['fine-dining', 'terroir', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Garde Manger',
    category: 'restaurant',
    subcategory: 'Seafood',
    description: 'Chuck Hughes\' Old Montreal seafood and comfort food spot.',
    lat: 45.50140,
    lng: -73.55360,
    address: '408 Rue Saint-Francois-Xavier, Montreal, QC H2Y 2S9',
    tags: ['seafood', 'old-montreal', 'iconic'],
    source: 'manual',
  },
  {
    name: 'Damas',
    category: 'restaurant',
    subcategory: 'Syrian',
    description: 'Upscale Syrian restaurant celebrated for refined Levantine cuisine.',
    lat: 45.52280,
    lng: -73.60340,
    address: '1201 Av Van Horne, Outremont, QC H2V 1K4',
    tags: ['syrian', 'levantine', 'outremont'],
    source: 'manual',
  },
  {
    name: 'Le Vin Papillon',
    category: 'restaurant',
    subcategory: 'Wine Bar',
    description: 'Vegetable-forward natural wine bar from the Joe Beef team.',
    lat: 45.48330,
    lng: -73.58710,
    address: '2519 Rue Notre-Dame O, Montreal, QC',
    tags: ['wine-bar', 'little-burgundy', 'natural-wine'],
    source: 'manual',
  },
  {
    name: 'Liverpool House',
    category: 'restaurant',
    subcategory: 'French / Italian',
    description: 'Sister restaurant to Joe Beef with a warm seasonal menu.',
    lat: 45.48345,
    lng: -73.58690,
    address: '2501 Rue Notre-Dame O, Montreal, QC',
    tags: ['fine-dining', 'little-burgundy', 'seasonal'],
    source: 'manual',
  },
  {
    name: 'Kazu',
    category: 'restaurant',
    subcategory: 'Japanese',
    description: 'Tiny, beloved Japanese izakaya with famously long lineups.',
    lat: 45.49160,
    lng: -73.58110,
    address: '1862 Rue Sainte-Catherine O, Montreal, QC H3H 1M1',
    tags: ['japanese', 'izakaya', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Tri Express',
    category: 'restaurant',
    subcategory: 'Japanese / Sushi',
    description: 'Lively Plateau sushi counter run by chef Tri Du.',
    lat: 45.53330,
    lng: -73.58800,
    address: '1650 Av Laurier E, Montreal, QC H2J 1J2',
    tags: ['sushi', 'japanese', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Maison Publique',
    category: 'restaurant',
    subcategory: 'Gastropub',
    description: 'British-influenced gastropub from chef Derek Dammann.',
    lat: 45.53470,
    lng: -73.58060,
    address: '4720 Rue Marquette, Montreal, QC H2J 3Y7',
    tags: ['gastropub', 'plateau', 'seasonal'],
    source: 'manual',
  },
  {
    name: 'Moishes Steakhouse',
    category: 'restaurant',
    subcategory: 'Steakhouse',
    description: 'Historic Montreal steakhouse institution since 1938.',
    lat: 45.51570,
    lng: -73.58210,
    address: '3961 Boul Saint-Laurent, Montreal, QC',
    tags: ['steakhouse', 'iconic', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Beautys Luncheonette',
    category: 'restaurant',
    subcategory: 'Diner',
    description: 'Classic Montreal breakfast diner serving since 1942.',
    lat: 45.51740,
    lng: -73.58720,
    address: '93 Av du Mont-Royal O, Montreal, QC H2T 2S5',
    tags: ['breakfast', 'diner', 'plateau'],
    source: 'manual',
  },
  {
    name: 'La Banquise',
    category: 'restaurant',
    subcategory: 'Poutine',
    description: 'Iconic 24-hour poutine spot with dozens of varieties.',
    lat: 45.52440,
    lng: -73.57400,
    address: '994 Rue Rachel E, Montreal, QC H2J 2J3',
    tags: ['poutine', 'late-night', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Restaurant Mon Nan',
    category: 'restaurant',
    subcategory: 'Chinese',
    description: 'Long-running Cantonese restaurant in Montreal Chinatown.',
    lat: 45.50760,
    lng: -73.55980,
    address: '1062 Boul Saint-Laurent, Montreal, QC',
    tags: ['chinese', 'chinatown', 'cantonese'],
    source: 'manual',
  },
  {
    name: 'Le Filet',
    category: 'restaurant',
    subcategory: 'Seafood',
    description: 'Elegant seafood-focused restaurant across from Parc Jeanne-Mance.',
    lat: 45.51480,
    lng: -73.58440,
    address: '219 Av du Mont-Royal O, Montreal, QC',
    tags: ['seafood', 'fine-dining', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Nora Gray',
    category: 'restaurant',
    subcategory: 'Italian',
    description: 'Southern Italian restaurant with a refined, cozy dining room.',
    lat: 45.49050,
    lng: -73.55790,
    address: '1391 Rue Saint-Jacques, Montreal, QC',
    tags: ['italian', 'griffintown', 'fine-dining'],
    source: 'manual',
  },
  {
    name: 'Pho Tay Ho',
    category: 'restaurant',
    subcategory: 'Vietnamese',
    description: 'Beloved Vietnamese pho house in Villeray.',
    lat: 45.54040,
    lng: -73.61960,
    address: '6414 Rue Saint-Denis, Montreal, QC',
    tags: ['vietnamese', 'pho', 'villeray'],
    source: 'manual',
  },
  {
    name: 'Tuck Shop',
    category: 'restaurant',
    subcategory: 'Bistro',
    description: 'Neighbourhood bistro with a market-driven menu in Saint-Henri.',
    lat: 45.47720,
    lng: -73.58880,
    address: '4662 Rue Notre-Dame O, Montreal, QC',
    tags: ['bistro', 'saint-henri', 'seasonal'],
    source: 'manual',
  },
  {
    name: 'Bouillon Bilk',
    category: 'restaurant',
    subcategory: 'Contemporary',
    description: 'Minimalist contemporary restaurant near the Quartier des spectacles.',
    lat: 45.51000,
    lng: -73.56380,
    address: '1595 Boul Saint-Laurent, Montreal, QC',
    tags: ['contemporary', 'downtown', 'fine-dining'],
    source: 'manual',
  },
  {
    name: 'Olive et Gourmando',
    category: 'restaurant',
    subcategory: 'Cafe / Bakery',
    description: 'Old Montreal cafe-bakery famous for sandwiches and pastries.',
    lat: 45.50130,
    lng: -73.55600,
    address: '351 Rue Saint-Paul O, Montreal, QC H2Y 2A7',
    tags: ['bakery', 'sandwiches', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Park Restaurant',
    category: 'restaurant',
    subcategory: 'Japanese',
    description: 'Inventive Japanese restaurant from chef Antonio Park in Westmount.',
    lat: 45.48830,
    lng: -73.59560,
    address: '378 Av Victoria, Westmount, QC',
    tags: ['japanese', 'westmount', 'fine-dining'],
    source: 'manual',
  },
  {
    name: 'Restaurant Su',
    category: 'restaurant',
    subcategory: 'Turkish',
    description: 'Modern Turkish restaurant in Verdun celebrated for mezze.',
    lat: 45.46190,
    lng: -73.56830,
    address: '5145 Rue Wellington, Verdun, QC',
    tags: ['turkish', 'verdun', 'mezze'],
    source: 'manual',
  },
  {
    name: 'Le Mousso',
    category: 'restaurant',
    subcategory: 'Fine Dining',
    description: 'Avant-garde tasting-menu restaurant from chef Antonin Mousseau-Rivard.',
    lat: 45.51790,
    lng: -73.55300,
    address: '1023 Rue Ontario E, Montreal, QC',
    tags: ['fine-dining', 'tasting-menu', 'downtown'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // CAFES (12)
  // ---------------------------------------------------------------------------
  {
    name: 'Fairmount Bagel',
    category: 'cafe',
    subcategory: 'Bakery',
    description: 'Wood-fired Montreal-style bagels baked 24 hours a day since 1919.',
    lat: 45.52260,
    lng: -73.59980,
    address: '74 Av Fairmount O, Montreal, QC H2T 2M2',
    tags: ['bagels', 'mile-end', 'iconic'],
    source: 'manual',
  },
  {
    name: 'St-Viateur Bagel',
    category: 'cafe',
    subcategory: 'Bakery',
    description: 'Famous wood-fired bagel shop, a Mile End institution since 1957.',
    lat: 45.52320,
    lng: -73.60350,
    address: '263 Rue Saint-Viateur O, Montreal, QC H2V 1Y1',
    tags: ['bagels', 'mile-end', 'iconic'],
    source: 'manual',
  },
  {
    name: 'Olive et Gourmando Cafe',
    category: 'cafe',
    subcategory: 'Cafe',
    description: 'Cozy Old Montreal cafe with house-baked goods and coffee.',
    lat: 45.50125,
    lng: -73.55595,
    address: '351 Rue Saint-Paul O, Montreal, QC',
    tags: ['coffee', 'bakery', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Cafe Olimpico',
    category: 'cafe',
    subcategory: 'Espresso Bar',
    description: 'Classic Italian espresso bar at the heart of Mile End since 1970.',
    lat: 45.52400,
    lng: -73.60080,
    address: '124 Rue Saint-Viateur O, Montreal, QC H2T 2L4',
    tags: ['espresso', 'mile-end', 'italian'],
    source: 'manual',
  },
  {
    name: 'Crew Collective & Cafe',
    category: 'cafe',
    subcategory: 'Cafe / Coworking',
    description: 'Stunning cafe in a former bank hall with coworking space.',
    lat: 45.50250,
    lng: -73.55880,
    address: '360 Rue Saint-Jacques, Montreal, QC H2Y 1P5',
    tags: ['coffee', 'coworking', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Tommy Cafe',
    category: 'cafe',
    subcategory: 'Cafe',
    description: 'Plant-filled, design-forward cafe popular in Old Montreal.',
    lat: 45.50330,
    lng: -73.55720,
    address: '200 Rue Notre-Dame O, Montreal, QC',
    tags: ['coffee', 'brunch', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Pikolo Espresso Bar',
    category: 'cafe',
    subcategory: 'Espresso Bar',
    description: 'Compact specialty coffee bar near McGill and the Plateau.',
    lat: 45.51230,
    lng: -73.57280,
    address: '3418B Av du Parc, Montreal, QC H2X 2H5',
    tags: ['specialty-coffee', 'milton-parc', 'espresso'],
    source: 'manual',
  },
  {
    name: 'Myriade',
    category: 'cafe',
    subcategory: 'Specialty Coffee',
    description: 'Pioneering specialty coffee roaster and cafe near Concordia.',
    lat: 45.49710,
    lng: -73.57860,
    address: '1432 Rue Mackay, Montreal, QC H3G 2H7',
    tags: ['specialty-coffee', 'downtown', 'roaster'],
    source: 'manual',
  },
  {
    name: 'Caffe in Gamba',
    category: 'cafe',
    subcategory: 'Specialty Coffee',
    description: 'Multi-roaster specialty cafe on Avenue du Parc.',
    lat: 45.51990,
    lng: -73.58860,
    address: '5263 Av du Parc, Montreal, QC',
    tags: ['specialty-coffee', 'mile-end', 'multi-roaster'],
    source: 'manual',
  },
  {
    name: 'Cafe Replika',
    category: 'cafe',
    subcategory: 'Cafe',
    description: 'Turkish-inspired neighbourhood cafe on Saint-Denis.',
    lat: 45.51950,
    lng: -73.56970,
    address: '252 Rue Rachel E, Montreal, QC',
    tags: ['coffee', 'plateau', 'turkish'],
    source: 'manual',
  },
  {
    name: 'Tunnel Espresso Bar',
    category: 'cafe',
    subcategory: 'Espresso Bar',
    description: 'Tiny hidden espresso bar in the downtown underground city.',
    lat: 45.50140,
    lng: -73.56880,
    address: '1253 Av McGill College, Montreal, QC',
    tags: ['espresso', 'downtown', 'hidden'],
    source: 'manual',
  },
  {
    name: 'Dispatch Coffee',
    category: 'cafe',
    subcategory: 'Roaster',
    description: 'Specialty coffee roaster with a flagship cafe in the Plateau.',
    lat: 45.51720,
    lng: -73.58250,
    address: '4021 Boul Saint-Laurent, Montreal, QC',
    tags: ['roaster', 'plateau', 'specialty-coffee'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // BARS (15)
  // ---------------------------------------------------------------------------
  {
    name: 'Dieu du Ciel!',
    category: 'bar',
    subcategory: 'Brewpub',
    description: 'Renowned craft brewpub famous for its Peche Mortel stout.',
    lat: 45.52310,
    lng: -73.59620,
    address: '29 Av Laurier O, Montreal, QC H2T 2N2',
    tags: ['craft-beer', 'brewpub', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Foufounes Electriques',
    category: 'bar',
    subcategory: 'Punk Bar / Venue',
    description: 'Legendary punk and alternative music bar and concert venue.',
    lat: 45.51360,
    lng: -73.56450,
    address: '87 Rue Sainte-Catherine E, Montreal, QC H2X 1K5',
    tags: ['punk', 'live-music', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Casa del Popolo',
    category: 'bar',
    subcategory: 'Bar / Venue',
    description: 'Intimate vegetarian-friendly bar and indie music venue.',
    lat: 45.51980,
    lng: -73.58430,
    address: '4873 Boul Saint-Laurent, Montreal, QC H2T 1R6',
    tags: ['live-music', 'plateau', 'indie'],
    source: 'manual',
  },
  {
    name: 'Le Mal Necessaire',
    category: 'bar',
    subcategory: 'Tiki Bar',
    description: 'Hidden Chinatown tiki bar serving drinks in carved pineapples.',
    lat: 45.50760,
    lng: -73.56080,
    address: '1106B Boul Saint-Laurent, Montreal, QC H2Z 1J5',
    tags: ['tiki', 'cocktails', 'chinatown'],
    source: 'manual',
  },
  {
    name: 'Bar Datcha',
    category: 'bar',
    subcategory: 'Nightclub',
    description: 'Late-night Mile End dance bar with eclectic DJ sets.',
    lat: 45.52320,
    lng: -73.60010,
    address: '98 Av Laurier O, Montreal, QC H2T 2N4',
    tags: ['nightlife', 'dancing', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Big in Japan Bar',
    category: 'bar',
    subcategory: 'Cocktail Bar',
    description: 'Moody candle-lit speakeasy-style cocktail bar on the Main.',
    lat: 45.51760,
    lng: -73.58320,
    address: '4175 Boul Saint-Laurent, Montreal, QC H2W 1Y7',
    tags: ['cocktails', 'speakeasy', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Vices & Versa',
    category: 'bar',
    subcategory: 'Craft Beer Bar',
    description: 'Quebec microbrewery taproom on the Petite-Italie stretch.',
    lat: 45.53690,
    lng: -73.61790,
    address: '6631 Boul Saint-Laurent, Montreal, QC H2S 3C5',
    tags: ['craft-beer', 'quebec', 'petite-italie'],
    source: 'manual',
  },
  {
    name: 'Bar Henrietta',
    category: 'bar',
    subcategory: 'Cocktail Bar',
    description: 'Mediterranean-leaning cocktail and wine bar on the Main.',
    lat: 45.52030,
    lng: -73.58660,
    address: '115 Av Laurier O, Montreal, QC',
    tags: ['cocktails', 'wine', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Le Majestique',
    category: 'bar',
    subcategory: 'Bar / Oysters',
    description: 'Quirky bar serving oysters and natural wine on the Main.',
    lat: 45.51420,
    lng: -73.57340,
    address: '4105 Boul Saint-Laurent, Montreal, QC',
    tags: ['oysters', 'natural-wine', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Le Saint-Bock',
    category: 'bar',
    subcategory: 'Brewpub',
    description: 'Brewpub with one of the largest beer selections in the city.',
    lat: 45.51460,
    lng: -73.56330,
    address: '1749 Rue Saint-Denis, Montreal, QC',
    tags: ['craft-beer', 'brewpub', 'quartier-latin'],
    source: 'manual',
  },
  {
    name: 'Pub Burgundy Lion',
    category: 'bar',
    subcategory: 'British Pub',
    description: 'Lively British-style pub anchoring Little Burgundy nightlife.',
    lat: 45.48400,
    lng: -73.58330,
    address: '2496 Rue Notre-Dame O, Montreal, QC',
    tags: ['pub', 'little-burgundy', 'whisky'],
    source: 'manual',
  },
  {
    name: 'Cloakroom Bar',
    category: 'bar',
    subcategory: 'Speakeasy',
    description: 'Hidden bespoke cocktail bar behind a tailor shop downtown.',
    lat: 45.49860,
    lng: -73.57180,
    address: '2175 Rue de la Montagne, Montreal, QC',
    tags: ['cocktails', 'speakeasy', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Pullman',
    category: 'bar',
    subcategory: 'Wine Bar',
    description: 'Stylish wine bar with an extensive by-the-glass list.',
    lat: 45.50630,
    lng: -73.57570,
    address: '3424 Av du Parc, Montreal, QC',
    tags: ['wine', 'downtown', 'tapas'],
    source: 'manual',
  },
  {
    name: 'Brutopia',
    category: 'bar',
    subcategory: 'Brewpub',
    description: 'Crescent Street brewpub with house beers and live music.',
    lat: 45.49560,
    lng: -73.57760,
    address: '1219 Rue Crescent, Montreal, QC',
    tags: ['craft-beer', 'downtown', 'live-music'],
    source: 'manual',
  },
  {
    name: 'Else\'s',
    category: 'bar',
    subcategory: 'Neighbourhood Bar',
    description: 'Beloved corner neighbourhood bar at the edge of the Plateau.',
    lat: 45.51900,
    lng: -73.57050,
    address: '156 Rue Roy E, Montreal, QC',
    tags: ['neighbourhood', 'plateau', 'casual'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // PARKS (20)
  // ---------------------------------------------------------------------------
  {
    name: 'Mount Royal Park',
    category: 'park',
    subcategory: 'Urban Park',
    description: 'Iconic mountain park designed by Frederick Law Olmsted.',
    lat: 45.50360,
    lng: -73.58740,
    address: '1260 Chemin Remembrance, Montreal, QC H3H 1A2',
    tags: ['mountain', 'lookout', 'iconic'],
    source: 'manual',
  },
  {
    name: 'Parc La Fontaine',
    category: 'park',
    subcategory: 'Urban Park',
    description: 'Large Plateau park with ponds, paths and summer theatre.',
    lat: 45.52680,
    lng: -73.56960,
    address: '3933 Av du Parc-La Fontaine, Montreal, QC H2L 3M6',
    tags: ['ponds', 'plateau', 'picnic'],
    source: 'manual',
  },
  {
    name: 'Parc Jean-Drapeau',
    category: 'park',
    subcategory: 'Island Park',
    description: 'Island park on Sainte-Helene and Notre-Dame with festivals.',
    lat: 45.51380,
    lng: -73.53270,
    address: '1 Circuit Gilles Villeneuve, Montreal, QC H3C 1A9',
    tags: ['island', 'festivals', 'cycling'],
    source: 'manual',
  },
  {
    name: 'Parc Maisonneuve',
    category: 'park',
    subcategory: 'Urban Park',
    description: 'Sprawling east-end park beside the Olympic Park and gardens.',
    lat: 45.55840,
    lng: -73.55470,
    address: '4601 Rue Sherbrooke E, Montreal, QC H1X 2B2',
    tags: ['green-space', 'hochelaga', 'running'],
    source: 'manual',
  },
  {
    name: 'Parc Jarry',
    category: 'park',
    subcategory: 'Urban Park',
    description: 'Big Villeray park with a lake, tennis stadium and trails.',
    lat: 45.53690,
    lng: -73.62680,
    address: '285 Rue Gary-Carter, Montreal, QC H2R 2W1',
    tags: ['lake', 'villeray', 'tennis'],
    source: 'manual',
  },
  {
    name: 'Lachine Canal',
    category: 'park',
    subcategory: 'Linear Park',
    description: 'Historic canal with a popular cycling and walking path.',
    lat: 45.48140,
    lng: -73.58840,
    address: 'Lachine Canal National Historic Site, Montreal, QC',
    tags: ['cycling', 'waterfront', 'historic'],
    source: 'manual',
  },
  {
    name: 'Old Port of Montreal',
    category: 'park',
    subcategory: 'Waterfront',
    description: 'Riverside promenade with attractions along the St. Lawrence.',
    lat: 45.50550,
    lng: -73.54870,
    address: '333 Rue de la Commune O, Montreal, QC H2Y 2E2',
    tags: ['waterfront', 'old-montreal', 'promenade'],
    source: 'manual',
  },
  {
    name: 'Parc Angrignon',
    category: 'park',
    subcategory: 'Urban Park',
    description: 'Large southwest park with lagoons and wooded trails.',
    lat: 45.44650,
    lng: -73.60390,
    address: '3400 Boul des Trinitaires, Montreal, QC H4E 4J3',
    tags: ['lagoon', 'sud-ouest', 'nature'],
    source: 'manual',
  },
  {
    name: 'Westmount Park',
    category: 'park',
    subcategory: 'Urban Park',
    description: 'Leafy Westmount park with a pond, library and conservatory.',
    lat: 45.48390,
    lng: -73.59820,
    address: '4574 Rue Sherbrooke O, Westmount, QC H3Z 1G1',
    tags: ['pond', 'westmount', 'family'],
    source: 'manual',
  },
  {
    name: 'Parc Laurier',
    category: 'park',
    subcategory: 'Neighbourhood Park',
    description: 'Plateau neighbourhood park with sports fields and a chalet.',
    lat: 45.53270,
    lng: -73.58240,
    address: '5200 Rue de Brebeuf, Montreal, QC H2J 3L7',
    tags: ['sports', 'plateau', 'family'],
    source: 'manual',
  },
  {
    name: 'Parc du Mont-Royal Lookout (Kondiaronk)',
    category: 'park',
    subcategory: 'Lookout',
    description: 'Belvedere offering the classic panoramic view of downtown.',
    lat: 45.50450,
    lng: -73.58740,
    address: 'Chalet du Mont-Royal, Montreal, QC',
    tags: ['lookout', 'panorama', 'iconic'],
    source: 'manual',
  },
  {
    name: 'Beaver Lake (Lac aux Castors)',
    category: 'park',
    subcategory: 'Lake',
    description: 'Man-made lake on Mount Royal for paddling and ice skating.',
    lat: 45.49570,
    lng: -73.59370,
    address: 'Lac aux Castors, Montreal, QC',
    tags: ['lake', 'mount-royal', 'skating'],
    source: 'manual',
  },
  {
    name: 'Parc Jeanne-Mance',
    category: 'park',
    subcategory: 'Urban Park',
    description: 'Open park at the foot of Mount Royal popular for sports.',
    lat: 45.51420,
    lng: -73.58620,
    address: '4422 Av de l\'Esplanade, Montreal, QC',
    tags: ['sports', 'plateau', 'tam-tams'],
    source: 'manual',
  },
  {
    name: 'Parc des Rapides',
    category: 'park',
    subcategory: 'Nature Park',
    description: 'Riverside nature park with bird sanctuary and rapids views.',
    lat: 45.42950,
    lng: -73.59870,
    address: '4001 Boul LaSalle, LaSalle, QC',
    tags: ['nature', 'birds', 'lasalle'],
    source: 'manual',
  },
  {
    name: 'Parc Frederic-Back',
    category: 'park',
    subcategory: 'Urban Park',
    description: 'Reclaimed quarry turned vast green park in Saint-Michel.',
    lat: 45.56640,
    lng: -73.62350,
    address: '3000 Rue Michel-Jurdant, Montreal, QC',
    tags: ['green-space', 'saint-michel', 'reclaimed'],
    source: 'manual',
  },
  {
    name: 'Parc Outremont',
    category: 'park',
    subcategory: 'Neighbourhood Park',
    description: 'Charming Outremont park with a small pond and fountain.',
    lat: 45.51800,
    lng: -73.60790,
    address: '999 Av McEachran, Outremont, QC',
    tags: ['pond', 'outremont', 'family'],
    source: 'manual',
  },
  {
    name: 'Square Saint-Louis',
    category: 'park',
    subcategory: 'Square',
    description: 'Victorian square ringed by colourful row houses.',
    lat: 45.51740,
    lng: -73.56680,
    address: 'Carre Saint-Louis, Montreal, QC',
    tags: ['square', 'plateau', 'historic'],
    source: 'manual',
  },
  {
    name: 'Parc du Bassin Bonsecours',
    category: 'park',
    subcategory: 'Waterfront',
    description: 'Old Port basin park for pedal boats and winter skating.',
    lat: 45.50800,
    lng: -73.54470,
    address: 'Quai Jacques-Cartier, Montreal, QC',
    tags: ['waterfront', 'skating', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Parc Pere-Marquette',
    category: 'park',
    subcategory: 'Neighbourhood Park',
    description: 'Rosemont park with sports facilities and an arena.',
    lat: 45.54200,
    lng: -73.59560,
    address: '1600 Rue de Bellechasse, Montreal, QC',
    tags: ['sports', 'rosemont', 'family'],
    source: 'manual',
  },
  {
    name: 'Promenade Bellerive',
    category: 'park',
    subcategory: 'Waterfront',
    description: 'Long riverside park in the east end facing the St. Lawrence.',
    lat: 45.61130,
    lng: -73.50640,
    address: '8300 Rue Bellerive, Montreal, QC',
    tags: ['waterfront', 'east-end', 'walking'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // CULTURE (20)
  // ---------------------------------------------------------------------------
  {
    name: 'Montreal Museum of Fine Arts (MBAM)',
    category: 'culture',
    subcategory: 'Art Museum',
    description: 'Canada\'s most-visited art museum, spanning several pavilions.',
    lat: 45.49870,
    lng: -73.57930,
    address: '1380 Rue Sherbrooke O, Montreal, QC H3G 1J5',
    tags: ['art', 'museum', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Musee d\'art contemporain (MAC)',
    category: 'culture',
    subcategory: 'Art Museum',
    description: 'Montreal\'s contemporary art museum in the Quartier des spectacles.',
    lat: 45.50760,
    lng: -73.56680,
    address: '185 Rue Sainte-Catherine O, Montreal, QC H2X 3X5',
    tags: ['contemporary-art', 'museum', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Place des Arts',
    category: 'culture',
    subcategory: 'Performing Arts',
    description: 'Major performing arts complex and heart of the festival district.',
    lat: 45.50790,
    lng: -73.56640,
    address: '175 Rue Sainte-Catherine O, Montreal, QC H2X 1Z8',
    tags: ['theatre', 'concerts', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Biodome de Montreal',
    category: 'culture',
    subcategory: 'Nature Museum',
    description: 'Indoor recreations of five Americas ecosystems near the stadium.',
    lat: 45.55980,
    lng: -73.54980,
    address: '4777 Av Pierre-De Coubertin, Montreal, QC H1V 1B3',
    tags: ['ecosystems', 'family', 'hochelaga'],
    source: 'manual',
  },
  {
    name: 'Rio Tinto Alcan Planetarium',
    category: 'culture',
    subcategory: 'Planetarium',
    description: 'Modern planetarium with immersive dome shows about the cosmos.',
    lat: 45.55870,
    lng: -73.55090,
    address: '4801 Av Pierre-De Coubertin, Montreal, QC H1V 3V4',
    tags: ['astronomy', 'family', 'space'],
    source: 'manual',
  },
  {
    name: 'Montreal Insectarium',
    category: 'culture',
    subcategory: 'Museum',
    description: 'Insect museum within the Botanical Garden grounds.',
    lat: 45.55980,
    lng: -73.56360,
    address: '4581 Rue Sherbrooke E, Montreal, QC H1X 2B2',
    tags: ['insects', 'family', 'nature'],
    source: 'manual',
  },
  {
    name: 'Montreal Botanical Garden',
    category: 'culture',
    subcategory: 'Garden',
    description: 'World-class botanical garden with themed gardens and greenhouses.',
    lat: 45.55980,
    lng: -73.56260,
    address: '4101 Rue Sherbrooke E, Montreal, QC H1X 2B2',
    tags: ['gardens', 'nature', 'hochelaga'],
    source: 'manual',
  },
  {
    name: 'Pointe-a-Calliere',
    category: 'culture',
    subcategory: 'History Museum',
    description: 'Archaeology and history museum on Montreal\'s birthplace site.',
    lat: 45.50230,
    lng: -73.55430,
    address: '350 Place Royale, Montreal, QC H2Y 3Y5',
    tags: ['archaeology', 'history', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'McCord Stewart Museum',
    category: 'culture',
    subcategory: 'History Museum',
    description: 'Museum of Montreal social history, costume and photography.',
    lat: 45.50430,
    lng: -73.57360,
    address: '690 Rue Sherbrooke O, Montreal, QC H3A 1E9',
    tags: ['history', 'museum', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Notre-Dame Basilica',
    category: 'culture',
    subcategory: 'Church',
    description: 'Ornate Gothic Revival basilica in the heart of Old Montreal.',
    lat: 45.50450,
    lng: -73.55630,
    address: '110 Rue Notre-Dame O, Montreal, QC H2Y 1T1',
    tags: ['basilica', 'old-montreal', 'iconic'],
    source: 'manual',
  },
  {
    name: 'Cinematheque quebecoise',
    category: 'culture',
    subcategory: 'Film Archive',
    description: 'Film archive and cinema dedicated to Quebec and world cinema.',
    lat: 45.51460,
    lng: -73.56360,
    address: '335 Boul de Maisonneuve E, Montreal, QC H2X 1K1',
    tags: ['cinema', 'archive', 'quartier-latin'],
    source: 'manual',
  },
  {
    name: 'Phi Centre',
    category: 'culture',
    subcategory: 'Arts Centre',
    description: 'Multidisciplinary arts and immersive technology centre.',
    lat: 45.50180,
    lng: -73.55310,
    address: '315 Rue Saint-Paul O, Montreal, QC H2Y 2A3',
    tags: ['immersive', 'arts', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Grande Bibliotheque (BAnQ)',
    category: 'culture',
    subcategory: 'Library',
    description: 'Quebec\'s flagship public library in the Quartier Latin.',
    lat: 45.51530,
    lng: -73.56130,
    address: '475 Boul de Maisonneuve E, Montreal, QC H2L 5C4',
    tags: ['library', 'quartier-latin', 'public'],
    source: 'manual',
  },
  {
    name: 'Saint Joseph\'s Oratory',
    category: 'culture',
    subcategory: 'Basilica',
    description: 'Monumental hilltop basilica with sweeping city views.',
    lat: 45.49230,
    lng: -73.61700,
    address: '3800 Chemin Queen Mary, Montreal, QC H3V 1H6',
    tags: ['basilica', 'cote-des-neiges', 'iconic'],
    source: 'manual',
  },
  {
    name: 'Notre-Dame-de-Bon-Secours Chapel',
    category: 'culture',
    subcategory: 'Church',
    description: 'Historic sailors\' chapel with a maritime museum and tower.',
    lat: 45.50820,
    lng: -73.55060,
    address: '400 Rue Saint-Paul E, Montreal, QC',
    tags: ['chapel', 'old-montreal', 'historic'],
    source: 'manual',
  },
  {
    name: 'Centre Canadien d\'Architecture (CCA)',
    category: 'culture',
    subcategory: 'Architecture Museum',
    description: 'Internationally important architecture museum and research centre.',
    lat: 45.49580,
    lng: -73.58040,
    address: '1920 Rue Baile, Montreal, QC H3H 2S6',
    tags: ['architecture', 'museum', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Theatre du Nouveau Monde',
    category: 'culture',
    subcategory: 'Theatre',
    description: 'Storied French-language theatre in the downtown core.',
    lat: 45.50800,
    lng: -73.56500,
    address: '84 Rue Sainte-Catherine O, Montreal, QC',
    tags: ['theatre', 'french', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Place Royale & Old Montreal',
    category: 'culture',
    subcategory: 'Heritage District',
    description: 'Cobblestoned historic district and the city\'s oldest public square.',
    lat: 45.50280,
    lng: -73.55420,
    address: 'Place Royale, Montreal, QC',
    tags: ['heritage', 'old-montreal', 'historic'],
    source: 'manual',
  },
  {
    name: 'DHC/PHI Foundation site',
    category: 'culture',
    subcategory: 'Art Gallery',
    description: 'Contemporary art foundation exhibition space in Old Montreal.',
    lat: 45.50150,
    lng: -73.55360,
    address: '451 Rue Saint-Jean, Montreal, QC',
    tags: ['contemporary-art', 'gallery', 'old-montreal'],
    source: 'manual',
  },
  {
    name: 'Marche Bonsecours',
    category: 'culture',
    subcategory: 'Heritage Building',
    description: 'Historic domed public market hall, now boutiques and galleries.',
    lat: 45.50840,
    lng: -73.55080,
    address: '350 Rue Saint-Paul E, Montreal, QC H2Y 1H2',
    tags: ['heritage', 'old-montreal', 'market'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // ENTERTAINMENT (15)
  // ---------------------------------------------------------------------------
  {
    name: 'Bell Centre',
    category: 'entertainment',
    subcategory: 'Arena',
    description: 'Home of the Montreal Canadiens and the city\'s biggest concerts.',
    lat: 45.49610,
    lng: -73.56930,
    address: '1909 Av des Canadiens-de-Montreal, Montreal, QC H4B 5G0',
    tags: ['hockey', 'concerts', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Olympic Stadium',
    category: 'entertainment',
    subcategory: 'Stadium',
    description: 'Iconic 1976 Olympic stadium with its leaning tower.',
    lat: 45.55810,
    lng: -73.55190,
    address: '4545 Av Pierre-De Coubertin, Montreal, QC H1V 0B2',
    tags: ['stadium', 'events', 'hochelaga'],
    source: 'manual',
  },
  {
    name: 'La Ronde',
    category: 'entertainment',
    subcategory: 'Amusement Park',
    description: 'Six Flags amusement park on Ile Sainte-Helene.',
    lat: 45.52180,
    lng: -73.53300,
    address: '22 Chemin Macdonald, Montreal, QC H3C 6A3',
    tags: ['amusement-park', 'rides', 'family'],
    source: 'manual',
  },
  {
    name: 'Theatre St-Denis',
    category: 'entertainment',
    subcategory: 'Theatre',
    description: 'Historic large-capacity theatre in the Quartier Latin.',
    lat: 45.51490,
    lng: -73.56340,
    address: '1594 Rue Saint-Denis, Montreal, QC H2X 3K2',
    tags: ['theatre', 'shows', 'quartier-latin'],
    source: 'manual',
  },
  {
    name: 'MTELUS',
    category: 'entertainment',
    subcategory: 'Concert Hall',
    description: 'Mid-size concert venue in the Quartier des spectacles.',
    lat: 45.51120,
    lng: -73.56300,
    address: '59 Rue Sainte-Catherine E, Montreal, QC H2X 1K5',
    tags: ['concerts', 'live-music', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Corona Theatre',
    category: 'entertainment',
    subcategory: 'Concert Hall',
    description: 'Restored heritage theatre and concert venue in Saint-Henri.',
    lat: 45.47700,
    lng: -73.59060,
    address: '2490 Rue Notre-Dame O, Montreal, QC H3J 1N5',
    tags: ['concerts', 'heritage', 'saint-henri'],
    source: 'manual',
  },
  {
    name: 'Place Bell',
    category: 'entertainment',
    subcategory: 'Arena',
    description: 'Laval arena hosting the Laval Rocket and major shows.',
    lat: 45.55720,
    lng: -73.71920,
    address: '1950 Rue Claude-Gagne, Laval, QC H7N 5H9',
    tags: ['arena', 'hockey', 'laval'],
    source: 'manual',
  },
  {
    name: 'Cinema Banque Scotia Montreal',
    category: 'entertainment',
    subcategory: 'Cinema',
    description: 'Large multiplex cinema in the downtown entertainment zone.',
    lat: 45.49620,
    lng: -73.57700,
    address: '977 Rue Sainte-Catherine O, Montreal, QC H3B 4W3',
    tags: ['cinema', 'movies', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Cinema du Parc',
    category: 'entertainment',
    subcategory: 'Cinema',
    description: 'Independent repertory cinema near McGill\'s ghetto.',
    lat: 45.50930,
    lng: -73.57700,
    address: '3575 Av du Parc, Montreal, QC H2X 3P9',
    tags: ['cinema', 'indie', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Saputo Stadium',
    category: 'entertainment',
    subcategory: 'Stadium',
    description: 'Home of CF Montreal soccer beside the Olympic Park.',
    lat: 45.56230,
    lng: -73.55190,
    address: '4750 Rue Sherbrooke E, Montreal, QC H1V 3S8',
    tags: ['soccer', 'stadium', 'hochelaga'],
    source: 'manual',
  },
  {
    name: 'Comedy Nest',
    category: 'entertainment',
    subcategory: 'Comedy Club',
    description: 'Long-running English-language stand-up comedy club.',
    lat: 45.49050,
    lng: -73.57730,
    address: '2313 Rue Sainte-Catherine O, Montreal, QC',
    tags: ['comedy', 'standup', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Salle Wilfrid-Pelletier',
    category: 'entertainment',
    subcategory: 'Concert Hall',
    description: 'Largest hall at Place des Arts, home to the OSM and opera.',
    lat: 45.50820,
    lng: -73.56600,
    address: '175 Rue Sainte-Catherine O, Montreal, QC',
    tags: ['symphony', 'opera', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Club Soda',
    category: 'entertainment',
    subcategory: 'Concert Hall',
    description: 'Beloved mid-size live music venue on the Main downtown.',
    lat: 45.51110,
    lng: -73.56350,
    address: '1225 Boul Saint-Laurent, Montreal, QC H2X 2S6',
    tags: ['concerts', 'live-music', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Theatre Rialto',
    category: 'entertainment',
    subcategory: 'Theatre',
    description: 'Ornate heritage theatre venue in Mile End.',
    lat: 45.52470,
    lng: -73.60490,
    address: '5723 Av du Parc, Montreal, QC',
    tags: ['theatre', 'heritage', 'mile-end'],
    source: 'manual',
  },
  {
    name: 'Le Studio TD (Maison du Festival)',
    category: 'entertainment',
    subcategory: 'Concert Hall',
    description: 'Intimate jazz and live music hall in the festival district.',
    lat: 45.50870,
    lng: -73.56660,
    address: '305 Rue Sainte-Catherine O, Montreal, QC',
    tags: ['jazz', 'live-music', 'downtown'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // TRANSIT (20) - Metro stations
  // ---------------------------------------------------------------------------
  {
    name: 'Berri-UQAM Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Central interchange linking the green, orange and yellow lines.',
    lat: 45.51510,
    lng: -73.56120,
    address: 'Rue Berri & Boul de Maisonneuve, Montreal, QC',
    tags: ['metro', 'interchange', 'downtown'],
    source: 'manual',
  },
  {
    name: 'McGill Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Green line station serving McGill University and downtown shops.',
    lat: 45.50420,
    lng: -73.57130,
    address: 'Rue McGill College & Boul de Maisonneuve, Montreal, QC',
    tags: ['metro', 'green-line', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Guy-Concordia Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Green line station serving Concordia\'s downtown campus.',
    lat: 45.49500,
    lng: -73.57870,
    address: 'Rue Guy & Boul de Maisonneuve, Montreal, QC',
    tags: ['metro', 'green-line', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Place-des-Arts Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Green line station beneath the festival and arts district.',
    lat: 45.50850,
    lng: -73.56690,
    address: 'Rue Jeanne-Mance, Montreal, QC',
    tags: ['metro', 'green-line', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Mont-Royal Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Orange line station at the heart of the Plateau.',
    lat: 45.52440,
    lng: -73.58210,
    address: 'Av du Mont-Royal & Rue Berri, Montreal, QC',
    tags: ['metro', 'orange-line', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Laurier Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Orange line station serving the eastern Plateau.',
    lat: 45.52740,
    lng: -73.58660,
    address: 'Av Laurier E & Rue Rivard, Montreal, QC',
    tags: ['metro', 'orange-line', 'plateau'],
    source: 'manual',
  },
  {
    name: 'Jean-Talon Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Orange and blue line interchange near the Jean-Talon Market.',
    lat: 45.53870,
    lng: -73.61450,
    address: 'Rue Jean-Talon & Rue Berri, Montreal, QC',
    tags: ['metro', 'interchange', 'villeray'],
    source: 'manual',
  },
  {
    name: 'Snowdon Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Orange and blue line interchange in Cote-des-Neiges.',
    lat: 45.48530,
    lng: -73.62280,
    address: 'Boul Decarie & Chemin Queen Mary, Montreal, QC',
    tags: ['metro', 'interchange', 'cote-des-neiges'],
    source: 'manual',
  },
  {
    name: 'Lionel-Groulx Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Green and orange line interchange in Little Burgundy.',
    lat: 45.48280,
    lng: -73.57940,
    address: 'Av Atwater & Rue Lionel-Groulx, Montreal, QC',
    tags: ['metro', 'interchange', 'sud-ouest'],
    source: 'manual',
  },
  {
    name: 'Atwater Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Green line station beside Atwater Market and Westmount.',
    lat: 45.49000,
    lng: -73.58420,
    address: 'Av Atwater & Rue Sainte-Catherine O, Montreal, QC',
    tags: ['metro', 'green-line', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Peel Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Green line station in the centre of downtown shopping.',
    lat: 45.50000,
    lng: -73.57440,
    address: 'Rue Peel & Boul de Maisonneuve, Montreal, QC',
    tags: ['metro', 'green-line', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Bonaventure Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Orange line station linked to Central Station and the train hub.',
    lat: 45.49930,
    lng: -73.56560,
    address: '900 Rue de la Gauchetiere O, Montreal, QC',
    tags: ['metro', 'orange-line', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Cote-Vertu Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Northwest terminus of the orange line in Saint-Laurent.',
    lat: 45.51290,
    lng: -73.68830,
    address: 'Boul Cote-Vertu, Saint-Laurent, QC',
    tags: ['metro', 'orange-line', 'saint-laurent'],
    source: 'manual',
  },
  {
    name: 'Angrignon Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Western terminus of the green line beside Parc Angrignon.',
    lat: 45.44640,
    lng: -73.60390,
    address: 'Boul des Trinitaires, Montreal, QC',
    tags: ['metro', 'green-line', 'sud-ouest'],
    source: 'manual',
  },
  {
    name: 'Honore-Beaugrand Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Eastern terminus of the green line in Mercier.',
    lat: 45.60390,
    lng: -73.52630,
    address: 'Rue Honore-Beaugrand, Montreal, QC',
    tags: ['metro', 'green-line', 'east-end'],
    source: 'manual',
  },
  {
    name: 'Sauve Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Orange line station in Ahuntsic in the north of the island.',
    lat: 45.55780,
    lng: -73.65510,
    address: 'Rue Sauve & Rue Berri, Montreal, QC',
    tags: ['metro', 'orange-line', 'ahuntsic'],
    source: 'manual',
  },
  {
    name: 'Henri-Bourassa Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Northern orange line hub serving Ahuntsic and Laval buses.',
    lat: 45.55580,
    lng: -73.66700,
    address: 'Boul Henri-Bourassa & Rue Lajeunesse, Montreal, QC',
    tags: ['metro', 'orange-line', 'ahuntsic'],
    source: 'manual',
  },
  {
    name: 'Vendome Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Orange line station connected to the MUHC Glen hospital site.',
    lat: 45.47390,
    lng: -73.60440,
    address: '5160 Boul de Maisonneuve O, Montreal, QC',
    tags: ['metro', 'orange-line', 'ndg'],
    source: 'manual',
  },
  {
    name: 'Pie-IX Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Green line station serving the Olympic Park area.',
    lat: 45.55310,
    lng: -73.55230,
    address: 'Boul Pie-IX & Av Pierre-De Coubertin, Montreal, QC',
    tags: ['metro', 'green-line', 'hochelaga'],
    source: 'manual',
  },
  {
    name: 'Frontenac Metro',
    category: 'transit',
    subcategory: 'Metro Station',
    description: 'Green line station in the Centre-Sud / Ville-Marie area.',
    lat: 45.53050,
    lng: -73.55600,
    address: 'Rue Ontario E & Rue du Havre, Montreal, QC',
    tags: ['metro', 'green-line', 'centre-sud'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // EDUCATION (20)
  // ---------------------------------------------------------------------------
  {
    name: 'McGill University',
    category: 'education',
    subcategory: 'University',
    description: 'World-renowned research university at the foot of Mount Royal.',
    lat: 45.50480,
    lng: -73.57720,
    address: '845 Rue Sherbrooke O, Montreal, QC H3A 0G4',
    tags: ['university', 'research', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Universite de Montreal',
    category: 'education',
    subcategory: 'University',
    description: 'Major French-language research university on Mount Royal\'s slope.',
    lat: 45.50450,
    lng: -73.61370,
    address: '2900 Boul Edouard-Montpetit, Montreal, QC H3T 1J4',
    tags: ['university', 'french', 'cote-des-neiges'],
    source: 'manual',
  },
  {
    name: 'Concordia University (Sir George Williams)',
    category: 'education',
    subcategory: 'University',
    description: 'Concordia\'s downtown campus around the Hall building.',
    lat: 45.49710,
    lng: -73.57880,
    address: '1455 Boul de Maisonneuve O, Montreal, QC H3G 1M8',
    tags: ['university', 'downtown', 'english'],
    source: 'manual',
  },
  {
    name: 'Concordia University (Loyola)',
    category: 'education',
    subcategory: 'University',
    description: 'Concordia\'s leafy west-end campus in NDG.',
    lat: 45.45830,
    lng: -73.64030,
    address: '7141 Rue Sherbrooke O, Montreal, QC H4B 1R6',
    tags: ['university', 'ndg', 'campus'],
    source: 'manual',
  },
  {
    name: 'Ecole de technologie superieure (ETS)',
    category: 'education',
    subcategory: 'Engineering School',
    description: 'Engineering school in Griffintown\'s innovation district.',
    lat: 45.49460,
    lng: -73.56270,
    address: '1100 Rue Notre-Dame O, Montreal, QC H3C 1K3',
    tags: ['engineering', 'griffintown', 'university'],
    source: 'manual',
  },
  {
    name: 'Polytechnique Montreal',
    category: 'education',
    subcategory: 'Engineering School',
    description: 'Leading engineering school affiliated with Universite de Montreal.',
    lat: 45.50450,
    lng: -73.61320,
    address: '2500 Chemin de Polytechnique, Montreal, QC H3T 1J4',
    tags: ['engineering', 'research', 'cote-des-neiges'],
    source: 'manual',
  },
  {
    name: 'HEC Montreal',
    category: 'education',
    subcategory: 'Business School',
    description: 'Prestigious French-language business school on the mountain.',
    lat: 45.50390,
    lng: -73.61730,
    address: '3000 Chemin de la Cote-Sainte-Catherine, Montreal, QC H3T 2A7',
    tags: ['business', 'mba', 'cote-des-neiges'],
    source: 'manual',
  },
  {
    name: 'Universite du Quebec a Montreal (UQAM)',
    category: 'education',
    subcategory: 'University',
    description: 'Large public French-language university in the Quartier Latin.',
    lat: 45.51470,
    lng: -73.56020,
    address: '405 Rue Sainte-Catherine E, Montreal, QC H2L 2C4',
    tags: ['university', 'french', 'quartier-latin'],
    source: 'manual',
  },
  {
    name: 'Dawson College',
    category: 'education',
    subcategory: 'CEGEP',
    description: 'Largest English-language CEGEP, housed in a former convent.',
    lat: 45.48910,
    lng: -73.58730,
    address: '3040 Rue Sherbrooke O, Montreal, QC H3Z 1A4',
    tags: ['cegep', 'downtown', 'english'],
    source: 'manual',
  },
  {
    name: 'Vanier College',
    category: 'education',
    subcategory: 'CEGEP',
    description: 'English-language CEGEP in the Saint-Laurent borough.',
    lat: 45.51750,
    lng: -73.66650,
    address: '821 Av Sainte-Croix, Saint-Laurent, QC H4L 3X9',
    tags: ['cegep', 'saint-laurent', 'english'],
    source: 'manual',
  },
  {
    name: 'Marianopolis College',
    category: 'education',
    subcategory: 'CEGEP',
    description: 'Selective English-language CEGEP in Westmount.',
    lat: 45.49210,
    lng: -73.60310,
    address: '4873 Westmount Ave, Westmount, QC H3Y 1X9',
    tags: ['cegep', 'westmount', 'english'],
    source: 'manual',
  },
  {
    name: 'College de Maisonneuve',
    category: 'education',
    subcategory: 'CEGEP',
    description: 'French-language CEGEP in the Rosemont area.',
    lat: 45.55860,
    lng: -73.56690,
    address: '3800 Rue Sherbrooke E, Montreal, QC',
    tags: ['cegep', 'french', 'rosemont'],
    source: 'manual',
  },
  {
    name: 'Cegep du Vieux Montreal',
    category: 'education',
    subcategory: 'CEGEP',
    description: 'French-language CEGEP near the Quartier Latin.',
    lat: 45.51410,
    lng: -73.56400,
    address: '255 Rue Ontario E, Montreal, QC',
    tags: ['cegep', 'french', 'quartier-latin'],
    source: 'manual',
  },
  {
    name: 'Cegep Ahuntsic',
    category: 'education',
    subcategory: 'CEGEP',
    description: 'Large French-language CEGEP in the north of the island.',
    lat: 45.54920,
    lng: -73.65040,
    address: '9155 Rue Saint-Hubert, Montreal, QC',
    tags: ['cegep', 'french', 'ahuntsic'],
    source: 'manual',
  },
  {
    name: 'John Abbott College',
    category: 'education',
    subcategory: 'CEGEP',
    description: 'English-language CEGEP on the West Island lakeshore.',
    lat: 45.40500,
    lng: -73.93870,
    address: '21275 Lakeshore Rd, Sainte-Anne-de-Bellevue, QC',
    tags: ['cegep', 'west-island', 'english'],
    source: 'manual',
  },
  {
    name: 'College Jean-de-Brebeuf',
    category: 'education',
    subcategory: 'College',
    description: 'Historic private college on Mount Royal\'s northern slope.',
    lat: 45.49860,
    lng: -73.62150,
    address: '3200 Chemin de la Cote-Sainte-Catherine, Montreal, QC',
    tags: ['college', 'private', 'cote-des-neiges'],
    source: 'manual',
  },
  {
    name: 'College LaSalle',
    category: 'education',
    subcategory: 'College',
    description: 'Private career college in the downtown core.',
    lat: 45.49680,
    lng: -73.57140,
    address: '2000 Rue Sainte-Catherine O, Montreal, QC',
    tags: ['college', 'career', 'downtown'],
    source: 'manual',
  },
  {
    name: 'McGill MacDonald Campus',
    category: 'education',
    subcategory: 'University Campus',
    description: 'McGill\'s agricultural and environmental sciences campus.',
    lat: 45.40640,
    lng: -73.93960,
    address: '21111 Lakeshore Rd, Sainte-Anne-de-Bellevue, QC',
    tags: ['university', 'agriculture', 'west-island'],
    source: 'manual',
  },
  {
    name: 'Concordia District 3 Innovation Hub',
    category: 'education',
    subcategory: 'Incubator',
    description: 'University startup incubator supporting student founders.',
    lat: 45.49530,
    lng: -73.57920,
    address: '1250 Rue Guy, Montreal, QC',
    tags: ['incubator', 'startups', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Centennial Academy',
    category: 'education',
    subcategory: 'School',
    description: 'Independent secondary school in the downtown area.',
    lat: 45.49680,
    lng: -73.58110,
    address: '3641 Rue Prudhomme, Montreal, QC',
    tags: ['school', 'private', 'ndg'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // HEALTH (15)
  // ---------------------------------------------------------------------------
  {
    name: 'Montreal General Hospital',
    category: 'health',
    subcategory: 'Hospital',
    description: 'Major adult trauma and teaching hospital of the MUHC.',
    lat: 45.49710,
    lng: -73.58840,
    address: '1650 Av Cedar, Montreal, QC H3G 1A4',
    tags: ['hospital', 'trauma', 'muhc'],
    source: 'manual',
  },
  {
    name: 'MUHC Glen Site',
    category: 'health',
    subcategory: 'Hospital',
    description: 'Modern superhospital complex of the McGill University Health Centre.',
    lat: 45.47350,
    lng: -73.60140,
    address: '1001 Boul Decarie, Montreal, QC H4A 3J1',
    tags: ['hospital', 'muhc', 'ndg'],
    source: 'manual',
  },
  {
    name: 'CHUM',
    category: 'health',
    subcategory: 'Hospital',
    description: 'University of Montreal\'s flagship downtown hospital.',
    lat: 45.51290,
    lng: -73.55780,
    address: '1051 Rue Sanguinet, Montreal, QC H2X 3E4',
    tags: ['hospital', 'university', 'downtown'],
    source: 'manual',
  },
  {
    name: 'CHU Sainte-Justine',
    category: 'health',
    subcategory: 'Children\'s Hospital',
    description: 'Major mother-and-child university hospital centre.',
    lat: 45.50140,
    lng: -73.62340,
    address: '3175 Chemin de la Cote-Sainte-Catherine, Montreal, QC H3T 1C5',
    tags: ['pediatric', 'hospital', 'cote-des-neiges'],
    source: 'manual',
  },
  {
    name: 'Jewish General Hospital',
    category: 'health',
    subcategory: 'Hospital',
    description: 'Major teaching hospital affiliated with McGill in Cote-des-Neiges.',
    lat: 45.49710,
    lng: -73.62980,
    address: '3755 Chemin de la Cote-Sainte-Catherine, Montreal, QC H3T 1E2',
    tags: ['hospital', 'teaching', 'cote-des-neiges'],
    source: 'manual',
  },
  {
    name: 'Royal Victoria Hospital (Glen)',
    category: 'health',
    subcategory: 'Hospital',
    description: 'Historic MUHC hospital now based at the Glen site.',
    lat: 45.47380,
    lng: -73.60230,
    address: '1001 Boul Decarie, Montreal, QC',
    tags: ['hospital', 'muhc', 'ndg'],
    source: 'manual',
  },
  {
    name: 'Maisonneuve-Rosemont Hospital',
    category: 'health',
    subcategory: 'Hospital',
    description: 'Large university-affiliated hospital in the east end.',
    lat: 45.58320,
    lng: -73.55280,
    address: '5415 Boul de l\'Assomption, Montreal, QC H1T 2M4',
    tags: ['hospital', 'east-end', 'teaching'],
    source: 'manual',
  },
  {
    name: 'Montreal Children\'s Hospital',
    category: 'health',
    subcategory: 'Children\'s Hospital',
    description: 'Pediatric teaching hospital of the MUHC at the Glen site.',
    lat: 45.47330,
    lng: -73.60060,
    address: '1001 Boul Decarie, Montreal, QC',
    tags: ['pediatric', 'muhc', 'ndg'],
    source: 'manual',
  },
  {
    name: 'Hopital Notre-Dame',
    category: 'health',
    subcategory: 'Hospital',
    description: 'General hospital serving the Plateau and Centre-Sud.',
    lat: 45.52520,
    lng: -73.56860,
    address: '1560 Rue Sherbrooke E, Montreal, QC H2L 4M1',
    tags: ['hospital', 'plateau', 'general'],
    source: 'manual',
  },
  {
    name: 'Hopital du Sacre-Coeur',
    category: 'health',
    subcategory: 'Hospital',
    description: 'Major trauma centre in the north of the island.',
    lat: 45.53870,
    lng: -73.71150,
    address: '5400 Boul Gouin O, Montreal, QC H4J 1C5',
    tags: ['hospital', 'trauma', 'north'],
    source: 'manual',
  },
  {
    name: 'St. Mary\'s Hospital',
    category: 'health',
    subcategory: 'Hospital',
    description: 'Community teaching hospital in Cote-des-Neiges.',
    lat: 45.49460,
    lng: -73.62500,
    address: '3830 Av Lacombe, Montreal, QC H3T 1M5',
    tags: ['hospital', 'community', 'cote-des-neiges'],
    source: 'manual',
  },
  {
    name: 'Lakeshore General Hospital',
    category: 'health',
    subcategory: 'Hospital',
    description: 'West Island community hospital in Pointe-Claire.',
    lat: 45.46340,
    lng: -73.81670,
    address: '160 Av Stillview, Pointe-Claire, QC H9R 2Y2',
    tags: ['hospital', 'west-island', 'community'],
    source: 'manual',
  },
  {
    name: 'Institut de Cardiologie de Montreal',
    category: 'health',
    subcategory: 'Specialty Hospital',
    description: 'Leading cardiology research and treatment institute.',
    lat: 45.57480,
    lng: -73.57920,
    address: '5000 Rue Belanger, Montreal, QC H1T 1C8',
    tags: ['cardiology', 'research', 'rosemont'],
    source: 'manual',
  },
  {
    name: 'Douglas Mental Health Institute',
    category: 'health',
    subcategory: 'Psychiatric Hospital',
    description: 'Psychiatric hospital and research centre in Verdun.',
    lat: 45.44380,
    lng: -73.60680,
    address: '6875 Boul LaSalle, Verdun, QC H4H 1R3',
    tags: ['psychiatry', 'research', 'verdun'],
    source: 'manual',
  },
  {
    name: 'Clinique Medicale du Quartier Latin',
    category: 'health',
    subcategory: 'Clinic',
    description: 'Walk-in and specialist medical clinic downtown.',
    lat: 45.51580,
    lng: -73.56250,
    address: '905 Rue Rene-Levesque E, Montreal, QC',
    tags: ['clinic', 'walk-in', 'downtown'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // SHOPPING (10)
  // ---------------------------------------------------------------------------
  {
    name: 'CF Montreal Eaton Centre',
    category: 'shopping',
    subcategory: 'Shopping Mall',
    description: 'Flagship downtown shopping centre on Sainte-Catherine.',
    lat: 45.50390,
    lng: -73.57010,
    address: '705 Rue Sainte-Catherine O, Montreal, QC H3B 4G5',
    tags: ['mall', 'downtown', 'shopping'],
    source: 'manual',
  },
  {
    name: 'Place Montreal Trust',
    category: 'shopping',
    subcategory: 'Shopping Mall',
    description: 'Multi-level downtown mall with a tall indoor fountain.',
    lat: 45.50140,
    lng: -73.57240,
    address: '1500 Av McGill College, Montreal, QC H3A 3J5',
    tags: ['mall', 'downtown', 'shopping'],
    source: 'manual',
  },
  {
    name: 'Marche Jean-Talon',
    category: 'shopping',
    subcategory: 'Public Market',
    description: 'Vibrant open-air market in Little Italy with local produce.',
    lat: 45.53670,
    lng: -73.61490,
    address: '7070 Av Henri-Julien, Montreal, QC H2S 3S3',
    tags: ['market', 'food', 'little-italy'],
    source: 'manual',
  },
  {
    name: 'Marche Atwater',
    category: 'shopping',
    subcategory: 'Public Market',
    description: 'Art Deco market hall beside the Lachine Canal.',
    lat: 45.47900,
    lng: -73.57650,
    address: '138 Av Atwater, Montreal, QC H4C 2H6',
    tags: ['market', 'food', 'sud-ouest'],
    source: 'manual',
  },
  {
    name: 'Complexe Desjardins',
    category: 'shopping',
    subcategory: 'Shopping Mall',
    description: 'Downtown mixed-use complex with shops and an atrium.',
    lat: 45.50840,
    lng: -73.56630,
    address: '150 Rue Sainte-Catherine O, Montreal, QC H5B 1B5',
    tags: ['mall', 'downtown', 'atrium'],
    source: 'manual',
  },
  {
    name: 'Marche Bonsecours Boutiques',
    category: 'shopping',
    subcategory: 'Boutiques',
    description: 'Heritage market hall full of Quebec designer boutiques.',
    lat: 45.50835,
    lng: -73.55085,
    address: '350 Rue Saint-Paul E, Montreal, QC',
    tags: ['boutiques', 'old-montreal', 'design'],
    source: 'manual',
  },
  {
    name: 'Les Cours Mont-Royal',
    category: 'shopping',
    subcategory: 'Shopping Mall',
    description: 'Upscale shopping arcade in a former grand hotel downtown.',
    lat: 45.50070,
    lng: -73.57350,
    address: '1455 Rue Peel, Montreal, QC H3A 1T5',
    tags: ['mall', 'luxury', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Carrefour Angrignon',
    category: 'shopping',
    subcategory: 'Shopping Mall',
    description: 'Large regional shopping mall in the LaSalle borough.',
    lat: 45.44980,
    lng: -73.59700,
    address: '7077 Boul Newman, LaSalle, QC H8N 1X1',
    tags: ['mall', 'lasalle', 'shopping'],
    source: 'manual',
  },
  {
    name: 'Place Ville Marie Shops',
    category: 'shopping',
    subcategory: 'Shopping Mall',
    description: 'Underground retail concourse beneath the iconic cruciform tower.',
    lat: 45.50130,
    lng: -73.56870,
    address: '1 Place Ville Marie, Montreal, QC H3B 3Y1',
    tags: ['mall', 'underground', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Galeries d\'Anjou',
    category: 'shopping',
    subcategory: 'Shopping Mall',
    description: 'Major regional shopping centre in the east-end Anjou borough.',
    lat: 45.61130,
    lng: -73.56750,
    address: '7999 Boul des Galeries-d\'Anjou, Anjou, QC',
    tags: ['mall', 'anjou', 'shopping'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // SERVICE (8)
  // ---------------------------------------------------------------------------
  {
    name: 'Montreal Central Station (Gare Centrale)',
    category: 'service',
    subcategory: 'Train Station',
    description: 'Main intercity and commuter rail terminal downtown.',
    lat: 45.50020,
    lng: -73.56680,
    address: '895 Rue de la Gauchetiere O, Montreal, QC H3B 4G1',
    tags: ['train', 'via-rail', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Montreal City Hall',
    category: 'service',
    subcategory: 'Government',
    description: 'Second Empire-style seat of Montreal\'s municipal government.',
    lat: 45.50880,
    lng: -73.55410,
    address: '275 Rue Notre-Dame E, Montreal, QC H2Y 1C6',
    tags: ['government', 'old-montreal', 'civic'],
    source: 'manual',
  },
  {
    name: 'Palais des congres de Montreal',
    category: 'service',
    subcategory: 'Convention Centre',
    description: 'Colourful glass convention centre near Chinatown.',
    lat: 45.50420,
    lng: -73.56120,
    address: '1001 Place Jean-Paul-Riopelle, Montreal, QC H2Z 1H5',
    tags: ['convention', 'events', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Notarius / WeWork Place Ville Marie',
    category: 'service',
    subcategory: 'Coworking',
    description: 'Downtown coworking and flexible office space hub.',
    lat: 45.50100,
    lng: -73.56890,
    address: '3 Place Ville Marie, Montreal, QC',
    tags: ['coworking', 'office', 'downtown'],
    source: 'manual',
  },
  {
    name: 'Notman House',
    category: 'service',
    subcategory: 'Tech Hub',
    description: 'Historic house turned hub for Montreal\'s startup community.',
    lat: 45.51020,
    lng: -73.57140,
    address: '51 Rue Sherbrooke O, Montreal, QC H2X 1X2',
    tags: ['startups', 'coworking', 'community'],
    source: 'manual',
  },
  {
    name: 'Bibliotheque Saint-Sulpice',
    category: 'service',
    subcategory: 'Library',
    description: 'Beaux-Arts heritage library building in the Quartier Latin.',
    lat: 45.51420,
    lng: -73.56230,
    address: '1700 Rue Saint-Denis, Montreal, QC',
    tags: ['library', 'heritage', 'quartier-latin'],
    source: 'manual',
  },
  {
    name: 'Bonaventure Postal Station',
    category: 'service',
    subcategory: 'Post Office',
    description: 'Central Canada Post office serving downtown Montreal.',
    lat: 45.49890,
    lng: -73.56480,
    address: '1 Place Bonaventure, Montreal, QC',
    tags: ['post-office', 'service', 'downtown'],
    source: 'manual',
  },
  {
    name: 'SAAQ Service Centre Henri-Bourassa',
    category: 'service',
    subcategory: 'Government',
    description: 'Quebec automobile insurance and licensing service centre.',
    lat: 45.55650,
    lng: -73.66520,
    address: '855 Boul Henri-Bourassa O, Montreal, QC',
    tags: ['government', 'service', 'ahuntsic'],
    source: 'manual',
  },

  // ---------------------------------------------------------------------------
  // JOBS (4) - postings tied to companies
  // ---------------------------------------------------------------------------
  {
    name: 'Senior ML Engineer @ Mila',
    category: 'job',
    subcategory: 'Machine Learning',
    description: 'Senior machine learning engineer role at the Quebec AI Institute.',
    lat: 45.53041,
    lng: -73.61375,
    address: '6666 Rue Saint-Urbain, Montreal, QC',
    tags: ['ml-engineer', 'ai', 'senior'],
    source: 'jobbank',
  },
  {
    name: 'Full-Stack Developer @ Lightspeed',
    category: 'job',
    subcategory: 'Software Engineering',
    description: 'Full-stack developer position on the commerce platform team.',
    lat: 45.49989,
    lng: -73.55686,
    address: '700 Rue Saint-Antoine E, Montreal, QC',
    tags: ['full-stack', 'saas', 'engineering'],
    source: 'jobbank',
  },
  {
    name: 'Game Programmer @ Ubisoft Montreal',
    category: 'job',
    subcategory: 'Game Development',
    description: 'Gameplay programmer role on a AAA open-world project.',
    lat: 45.52366,
    lng: -73.59488,
    address: '5505 Boul Saint-Laurent, Montreal, QC',
    tags: ['gameplay', 'gaming', 'programmer'],
    source: 'jobbank',
  },
  {
    name: 'Data Scientist @ Hopper',
    category: 'job',
    subcategory: 'Data Science',
    description: 'Data scientist role working on travel price prediction models.',
    lat: 45.50220,
    lng: -73.57010,
    address: '1170 Peel St, Montreal, QC',
    tags: ['data-science', 'travel', 'ml'],
    source: 'jobbank',
  },
];
